//! ModernBERT sliding-window parity against HuggingFace `transformers`.
//!
//! The oracle is `cookbook/fixtures/tiny_modernbert_local/`, generated by
//! `tests/fixtures/generate_tiny_modernbert_local.py`: a tiny real ModernBERT
//! whose config actually exercises local attention
//! (`num_hidden_layers=4`, `global_attn_every_n_layers=3` → layers 1 and 2 are
//! sliding, `local_attention=16` → a ±8 band over a 64-token sequence), plus the
//! `last_hidden_state` and pooled embedding PyTorch produces for two pinned
//! inputs.
//!
//! **Why a dedicated fixture.** Every other ModernBERT fixture in this repo is
//! `num_hidden_layers=1` / `global_attn_every_n_layers=1`. Layer 0 is global
//! under ModernBERT's own rule, so those fixtures compute identical output
//! whether or not sliding-window attention exists — they cannot express this
//! divergence, and no test built on them can.
//!
//! **Why this runs in the default lane.** It is the regression test for a
//! silent-wrong-output defect. The goldens are committed and need neither torch
//! nor a network, so there is nothing to gate behind a feature — and the repo's
//! two existing parity harnesses (`parity-test`, `golden-parity`) are referenced
//! by no CI workflow, which is precisely the failure mode to avoid here.
//!
//! The generator asserts its own discriminating power on every regeneration: a
//! window-ignoring build diverges from these goldens by ~8.5e-2 and a
//! theta-ignoring build by ~9.5e-3, against the 1e-4 tolerance below.

use std::collections::HashMap;
use std::path::PathBuf;

use candle_core::{DType, Device, Tensor};
use candle_nn::VarMap;
use jammi_encoders::modernbert::ModernBertConfig;
use jammi_encoders::{ModernBert, Pooling};

/// Max-abs tolerance against the PyTorch goldens.
///
/// Matches the HTSAT golden harness: looser than same-framework parity because
/// the oracle is a different framework, whose fp32 kernel and reduction order
/// differ, yet ~90x tighter than the smallest divergence either half of the
/// defect produces. Never loosened per-test.
const TOL_ABS: f32 = 1e-4;

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../cookbook/fixtures/tiny_modernbert_local")
}

fn load_config() -> ModernBertConfig {
    let raw = std::fs::read_to_string(fixture_dir().join("config.json"))
        .expect("read tiny_modernbert_local config");
    serde_json::from_str(&raw).expect("parse ModernBertConfig")
}

fn goldens(device: &Device) -> HashMap<String, Tensor> {
    candle_core::safetensors::load(fixture_dir().join("goldens.safetensors"), device)
        .expect("load tiny_modernbert_local goldens")
}

fn build_encoder(device: &Device) -> ModernBert {
    let varmap = VarMap::new();
    let weights = fixture_dir().join("model.safetensors");
    ModernBert::builder()
        .pooling(Pooling::Mean)
        .backbone_dtype(DType::F32)
        .build(&[weights.as_path()], &load_config(), device, &varmap)
        .expect("build ModernBert from tiny_modernbert_local")
}

/// Every element finite, counted rather than compared.
///
/// A NaN fails both `x < tol` and `x > tol`, so an all-NaN tensor satisfies any
/// comparison-based "matches the golden" assertion vacuously. A masking bug is
/// exactly how NaN gets produced here (a fully-masked softmax row), so the
/// finiteness check must not itself be a comparison.
fn assert_all_finite(t: &Tensor, what: &str) {
    let v = t.flatten_all().unwrap().to_vec1::<f32>().unwrap();
    let finite = v.iter().filter(|x| x.is_finite()).count();
    assert_eq!(
        finite,
        v.len(),
        "{what}: {} non-finite elements",
        v.len() - finite
    );
}

fn max_abs_diff(a: &Tensor, b: &Tensor) -> f32 {
    let a = a.flatten_all().unwrap().to_vec1::<f32>().unwrap();
    let b = b.flatten_all().unwrap().to_vec1::<f32>().unwrap();
    assert_eq!(a.len(), b.len(), "shape mismatch");
    a.iter()
        .zip(&b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

/// The fixture must actually be a local-attention fixture. If someone
/// regenerates it into an all-global config, every assertion below still passes
/// while testing nothing — so pin the property the fixture exists for.
#[test]
fn fixture_exercises_local_attention() {
    let cfg = load_config();
    assert_eq!(cfg.global_attn_every_n_layers, 3);
    assert_eq!(cfg.num_hidden_layers, 4);
    let local: Vec<usize> = (0..cfg.num_hidden_layers)
        .filter(|&n| cfg.is_local_layer(n))
        .collect();
    assert_eq!(
        local,
        vec![1, 2],
        "expected layers 1 and 2 to be sliding-attention"
    );
    assert_eq!(cfg.half_window(), 8, "local_attention=16 -> half window 8");
    assert!(
        cfg.local_rope_theta != cfg.global_rope_theta,
        "fixture cannot detect a dual-RoPE regression when both thetas agree"
    );
}

/// The band is a pure function of geometry, so assert its shape exhaustively
/// rather than inferring it from a model output.
#[test]
fn sliding_window_band_is_symmetric_and_keeps_the_diagonal() {
    let cfg = load_config();
    let half = cfg.half_window();
    let seq = 64usize;
    for q in 0..seq {
        let in_band: Vec<usize> = (0..seq).filter(|k| q.abs_diff(*k) <= half).collect();
        assert!(
            in_band.contains(&q),
            "query {q} must always attend to itself"
        );
        assert_eq!(
            in_band.first().copied().unwrap(),
            q.saturating_sub(half),
            "band start at query {q}"
        );
        assert_eq!(
            in_band.last().copied().unwrap(),
            (q + half).min(seq - 1),
            "band end at query {q}"
        );
    }
}

#[test]
fn hidden_states_match_huggingface_on_unpadded_input() {
    assert_case_matches("unpadded", false);
}

/// The padded case proves the window and the padding mask compose. An
/// implementation that applies the band but drops padding — or that lets a pad
/// token contribute — passes `unpadded` and fails here.
#[test]
fn hidden_states_match_huggingface_on_padded_input() {
    assert_case_matches("padded", false);
}

/// The C4 (fused masked softmax) training-arm variant of the two tests
/// above: same PyTorch goldens, same sliding-window-exercising fixture,
/// but with `set_training(true)` so `ModernBertAttention::forward` takes
/// the fused-softmax-or-fallback path (`softmax_apply_training`) instead
/// of the eager composition. This fixture's local-attention layers (1 and
/// 2) mean the training arm ALSO exercises the mask-precombination this
/// commit's call-site restructuring adds (`extended_mask.broadcast_add(&band)`
/// before the fused kernel runs) — the sliding-band fixture's own
/// discriminating power (its doc: "a window-ignoring build diverges by
/// ~8.5e-2 and a theta-ignoring one by ~9.5e-3, against the 1e-4
/// tolerance") stays green on this arm too, proving the fused path did not
/// silently drop the window or the dual-theta RoPE it also exercises.
#[test]
fn training_mode_hidden_states_match_huggingface_on_unpadded_input() {
    assert_case_matches("unpadded", true);
}

#[test]
fn training_mode_hidden_states_match_huggingface_on_padded_input() {
    assert_case_matches("padded", true);
}

fn assert_case_matches(case: &str, training: bool) {
    // Shares `crate::modernbert`'s dispatch-counter test lock (see its
    // doc): this function drives `set_training(true)` on the training
    // arm, touching the SAME process-wide fused/eager dispatch counters
    // `tests/it/modernbert.rs`'s own counter tests read under exact-
    // equality assertions -- taking the lock here (unconditionally, even
    // for the eval-arm calls, for simplicity) prevents this test from
    // ever running concurrently with those and disturbing their windows.
    let _guard = crate::modernbert::DISPATCH_COUNTER_TEST_LOCK
        .lock()
        .unwrap_or_else(|e| e.into_inner());
    let device = Device::Cpu;
    let g = goldens(&device);
    let mut encoder = build_encoder(&device);
    encoder.set_training(training);

    let softmax_before = jammi_encoders::softmax_dispatch_snapshot();

    let ids = g[&format!("{case}.input_ids")]
        .to_dtype(DType::U32)
        .unwrap();
    let mask = g[&format!("{case}.attention_mask")]
        .to_dtype(DType::U32)
        .unwrap();

    let hidden = encoder.forward_hidden(&ids, &mask).expect("forward_hidden");
    let golden_hidden = &g[&format!("{case}.last_hidden_state")];
    assert_all_finite(&hidden, &format!("{case} hidden states"));
    assert_all_finite(golden_hidden, &format!("{case} golden hidden states"));

    let got = hidden.squeeze(0).unwrap().to_vec2::<f32>().unwrap();
    let want = golden_hidden.squeeze(0).unwrap().to_vec2::<f32>().unwrap();
    let m = mask.squeeze(0).unwrap().to_vec1::<u32>().unwrap();
    let half = load_config().half_window();

    // Non-vacuity: the golden must carry real signal. An all-zero or constant
    // golden would make agreement meaningless.
    let flat: Vec<f32> = want.iter().flatten().copied().collect();
    let spread =
        flat.iter().fold(f32::MIN, |a, b| a.max(*b)) - flat.iter().fold(f32::MAX, |a, b| a.min(*b));
    assert!(
        spread > 1e-2,
        "{case} golden is degenerate (spread {spread})"
    );

    let row_diff = |i: usize| -> f32 {
        got[i]
            .iter()
            .zip(&want[i])
            .map(|(a, b)| (a - b).abs())
            .fold(0.0f32, f32::max)
    };

    // The contract is the real tokens. Every one of them must match.
    let mut worst_real = 0.0f32;
    let mut real_count = 0usize;
    for (i, &flag) in m.iter().enumerate() {
        if flag == 1 {
            real_count += 1;
            worst_real = worst_real.max(row_diff(i));
        }
    }
    assert!(real_count > 0, "{case}: no real tokens to assert on");
    assert!(
        worst_real <= TOL_ABS,
        "{case}: real-token hidden states diverge from HuggingFace by {worst_real:.6} \
         (tolerance {TOL_ABS:.0e}). A window-ignoring implementation diverges by ~8.5e-2 \
         and a theta-ignoring one by ~9.5e-3."
    );

    // Pad positions are NOT part of the contract, but the exemption is bounded
    // rather than blanket: a pad query may differ ONLY when its window contains
    // no unmasked key at all. Such a row has nothing legitimate to attend to,
    // and the two stacks resolve it differently for a reason that is an artifact
    // of the masking constant, not of attention: HuggingFace masks with
    // `finfo.min`, which saturates, so every entry collapses to the same value
    // and softmax is uniform; this encoder masks with a finite `MASKED_LOGIT`,
    // which cancels in softmax and leaves the raw scores ranked.
    //
    // A real query always attends to at least itself (`|i - i| = 0`), so its row
    // can never be fully masked -- which is why the assertion above is exact.
    // Any pad position that diverges while still having a valid key in band is a
    // genuine bug and fails here.
    for (i, &flag) in m.iter().enumerate() {
        if flag == 1 || row_diff(i) <= TOL_ABS {
            continue;
        }
        let has_valid_key = m
            .iter()
            .enumerate()
            .any(|(k, &km)| i.abs_diff(k) <= half && km == 1);
        assert!(
            !has_valid_key,
            "{case}: pad position {i} diverges by {:.6} despite having an unmasked key \
             within its window -- that is a real masking bug, not the fully-masked-row artifact",
            row_diff(i)
        );
    }

    // The pooled embedding is what consumers actually receive, and pooling masks
    // pad positions out -- so this must match exactly regardless of the above.
    let pooled = encoder.forward(&ids, &mask).expect("forward");
    assert_all_finite(&pooled, &format!("{case} pooled"));
    let pooled_delta = max_abs_diff(&pooled, &g[&format!("{case}.pooled")]);
    assert!(
        pooled_delta <= TOL_ABS,
        "{case}: pooled embedding diverges by {pooled_delta:.6}"
    );

    // Non-vacuity for the training arm: this fixture's `scores` shape
    // (rank 4, small `last`) is fused-eligible on CPU, so a training-mode
    // forward must actually have dispatched the fused softmax kernel at
    // least once -- otherwise this test would silently only be re-proving
    // the eval path under a different name.
    if training {
        let softmax_after = jammi_encoders::softmax_dispatch_snapshot();
        assert!(
            softmax_after.fused > softmax_before.fused,
            "{case} (training): must actually dispatch the fused softmax kernel, not \
             silently fall back (before={softmax_before:?}, after={softmax_after:?})"
        );
    }
}

/// A config this port cannot honour must be refused at load, not reinterpreted.
///
/// `global_attn_every_n_layers = 0` has no meaning — upstream raises on `i % 0`.
/// Treating it as "all layers global" would be the same silent-wrong-function
/// class that sliding-window support exists to remove, so it fails loudly.
#[test]
fn zero_global_attn_every_n_layers_is_refused_at_load() {
    let device = Device::Cpu;
    let mut cfg = load_config();
    cfg.global_attn_every_n_layers = 0;
    let varmap = VarMap::new();
    let weights = fixture_dir().join("model.safetensors");
    let built = ModernBert::builder().backbone_dtype(DType::F32).build(
        &[weights.as_path()],
        &cfg,
        &device,
        &varmap,
    );
    let Err(err) = built else {
        panic!("global_attn_every_n_layers = 0 must be refused, not reinterpreted");
    };
    let msg = err.to_string();
    assert!(
        msg.contains("global_attn_every_n_layers"),
        "the error must name the field it refuses: {msg}"
    );
}

/// The band is memoised per sequence length, so repeated forwards at one length
/// do not rebuild it. Without the cache each forward allocated and uploaded a
/// `seq * seq` host buffer.
#[test]
fn sliding_band_is_reused_across_forwards() {
    let device = Device::Cpu;
    let g = goldens(&device);
    let encoder = build_encoder(&device);
    let ids = g["unpadded.input_ids"].to_dtype(DType::U32).unwrap();
    let mask = g["unpadded.attention_mask"].to_dtype(DType::U32).unwrap();

    // Two forwards at the same length must agree exactly — a rebuilt band that
    // differed would show here, and a cached band that went stale would too.
    let a = encoder.forward_hidden(&ids, &mask).unwrap();
    let b = encoder.forward_hidden(&ids, &mask).unwrap();
    assert_eq!(
        max_abs_diff(&a, &b),
        0.0,
        "repeated forwards must be identical"
    );

    // A different length must still be correct, proving the cache is keyed by
    // length rather than serving the first band to every caller.
    let short_ids = ids.narrow(1, 0, 32).unwrap();
    let short_mask = mask.narrow(1, 0, 32).unwrap();
    let s = encoder.forward_hidden(&short_ids, &short_mask).unwrap();
    assert_eq!(s.dims()[1], 32, "short forward keeps its own length");
    assert_all_finite(&s, "short-sequence hidden states");
}
