#!/usr/bin/env bash
# Campaign #446 W2-A leg driver — the CUDA profile that decides scope item 1
# (`Axpy` wire-or-delete) under the PRE-REGISTERED rule in
# `crates/jammi-kernels/artifacts/cuda-runs/`'s own W2 axpy census artifact
# (`decision_rule` block, written BEFORE any number was measured).
#
# THIS IS A GPU-POD DRIVER, not a CI step, exactly like its sibling
# `profile_356_legs.sh` — real legs need an A100 (or equivalent), an
# installed `nsys`, and a real ModernBERT-large checkpoint directory
# (`$MODEL_DIR`).
#
# ## Relationship to `profile_356_legs.sh`
#
# Every measurement-shaping decision here is COPIED from that script rather
# than re-derived, because the census this produces is differenced by the
# SAME `kernel_census.py`, whose validity contract is stated in terms of
# unit-356's own `## Declared workload` pins:
#
#   - the traced command is `nsys profile --trace=cuda -o <prefix>
#     --force-overwrite=true -- <bench cmd>`, with the bench cmd wrapped in
#     `bash -c 'exec "$1" "${@:2}" > "$0"'` so ONLY the bench child's stdout
#     reaches the report JSON, regardless of what nsys prints to its own;
#   - the export is `nsys export --type=sqlite --output=<f>
#     --force-overwrite=true <prefix>.nsys-rep`;
#   - the declared-workload pins are VERBATIM: `--validation-fraction 0
#     --early-stopping-metric train_loss --epochs 1 --grad-accum 1`, a fixed
#     `--eval-cadence`, `--early-stopping-patience 10000`. These are what
#     make the non-training-step work (init probe, held-out eval,
#     checkpointing) IDENTICAL across the (N, M) pair so it cancels in the
#     subtraction — `kernel_census.py`'s own module doc;
#   - steps are `rows/batch` at `--epochs 1` (there is no `--steps` flag);
#     the corpus is generated by `gen_fixed_width_corpus.py --rows
#     $((batch*M)) --min-wordpieces $WIDTH --seed 42`, width-pinned, with
#     `--verify-tokenizer $MODEL_DIR/tokenizer.json` so the width guarantee
#     is MECHANICALLY checked against the actual tokenizer rather than
#     assumed, and the N-step corpus is `head -n $((batch*N))` of it (a
#     PREFIX, so the two runs train the identical rows in the identical
#     order for their shared first N steps);
#   - N=100, M=600, both multiples of 50 (`trainer.rs`'s norm-check
#     cadence), M>N with a wide separation for a clean per-step average;
#   - `--wall-a`/`--wall-b` are each run's own
#     `tiers.finetune_run.train_run_wall_s`, so `wall_s_per_step` is the
#     SAME (M-N)-step differencing applied to the wall clock, and
#     `--steps-measured-a`/`-b` feed `kernel_census.py`'s own domain check
#     that the measured step count matches the declared one.
#
# ## What is NEW here (and why)
#
#   - the model is ModernBERT-large with the CLI's own DEFAULT LoRA
#     selectors (`Wqkv,Wo,Wi` — ModernBERT-native; unit-356's legs were
#     bert-base/distilbert, whose selector sets do not exist on this
#     architecture);
#   - a THIRD shipped dtype leg, `f16` (L3) — unit-356 measured f32/bf16
#     only, and campaign #443 landed the f16 CUDA dispatch arms this
#     decision has to cover;
#   - an eager-optimizer CONTROL leg (L4) driven by
#     `JAMMI_KERNELS_DISABLE=adamw_step_fused` with `--arm fused`. NOT
#     `--arm alloff`: that arm is defined as
#     `attention_block_flash,adamw_step_fused` TOGETHER
#     (`finetune_run.rs`'s `ALLOFF_KEYS`) and `run()` hard-refuses any
#     other resolved value, so it would also force the attention arm eager
#     and confound the optimizer contrast. `--arm fused` explicitly permits
#     unrelated op keys being disabled ("an operator may legitimately run
#     it with OTHER, unrelated op keys disabled" — `finetune_run.rs`'s own
#     comment on that check), which is exactly this leg.
#
# ## Env vars
#   NSYS_BIN    path to the nsys binary (REQUIRED)
#   BENCH_BIN   path to the jammi-bench binary (default:
#               `$CARGO_TARGET_DIR/release/jammi-bench`)
#   MODEL_DIR   ModernBERT-large checkpoint dir (REQUIRED)
#   OUT_DIR     output directory for every leg's artifacts (REQUIRED)
#   AXPY_LEGS_ONLY  optional comma-separated leg-id filter (default: all)
#   AXPY_STEPS_N / AXPY_STEPS_M  the (N, M) pin (default 100 / 600)
#   AXPY_BATCH      shared batch for every leg (default 4 — see BATCH below)
#   AXPY_GIT_SHA    REQUIRED on a pushed pod tree: the 40-hex measured tip
#   AXPY_KEEP_RAW   "1" keeps the .nsys-rep/.sqlite captures (default: delete
#                   after both consumers have read them — disk budget)
#
# A leg-level failure NEVER aborts the sweep and ALWAYS produces a
# manifest recording `status`/`reason` (same posture as
# `profile_356_legs.sh`'s `run_leg`): a partial verdict is worse than a
# recorded INVALID leg.

set -uo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DIR/../../.." && pwd)"

NSYS_BIN="${NSYS_BIN:-}"
TARGET_DIR="${CARGO_TARGET_DIR:-$REPO_ROOT/target}"
BENCH_BIN="${BENCH_BIN:-$TARGET_DIR/release/jammi-bench}"
MODEL_DIR="${MODEL_DIR:-}"
OUT_DIR="${OUT_DIR:-}"
AXPY_LEGS_ONLY="${AXPY_LEGS_ONLY:-}"
STEPS_N="${AXPY_STEPS_N:-100}"
STEPS_M="${AXPY_STEPS_M:-600}"

# The one fixed eval cadence every leg shares (unit-356's `## Declared
# workload` "fixed eval cadence" — a script-level constant, not a per-leg
# column, so it cancels in the N/M differencing like every other pin).
EVAL_CADENCE=1
# BATCH -- a RECORDED DEVIATION from the W2-A leg table's declared `b=8`.
# ModernBERT-large at `b=8, W=512` does not fit on an A100 80GB in ANY of
# the four leg configurations: the live probe on this pod OOMs
# (`DriverError(CUDA_ERROR_OUT_OF_MEMORY)` out of `Encoder forward: LoRA`)
# with a sampled device-memory high-water mark of 75757 MiB of 81920 MiB,
# on an otherwise-idle GPU (0 MiB used, no other compute apps). `b=4`
# clears for all four (f32/f16/bf16 fused and the eager-AdamW control), and
# `b=2` also clears. `b=4` is taken as the largest that fits, and it is
# SHARED by every leg: a per-leg batch would make the per-step
# denominators, and therefore `P`, incomparable across legs. `P` is a RATIO
# of per-step GPU time, so it remains exactly the pre-registered quantity
# under a smaller batch; only the absolute per-step times move. 4 also
# still divides the held-out fixture's 128 pairs, which `finetune_run`
# refuses otherwise.
BATCH="${AXPY_BATCH:-4}"
WIDTH=512
# ModernBERT-native default selectors (`main.rs`'s own
# `target_modules` default) — "LoRA default selectors" in the leg table.
TARGET_MODULES="Wqkv,Wo,Wi"

FIXTURE_DIR="$REPO_ROOT/cookbook/fixtures/finetune_heldout"
HELDOUT_IDS="$FIXTURE_DIR/heldout_ids.txt"
HELDOUT_JSONL="$FIXTURE_DIR/heldout_pairs.jsonl"

for v in NSYS_BIN MODEL_DIR OUT_DIR; do
  if [ -z "${!v}" ]; then
    echo "::error::$v is required" >&2
    exit 1
  fi
done
for f in "$BENCH_BIN" "$NSYS_BIN" "$HELDOUT_IDS" "$HELDOUT_JSONL"; do
  if [ ! -e "$f" ]; then
    echo "::error::missing required path: $f" >&2
    exit 1
  fi
done
for f in config.json model.safetensors tokenizer.json; do
  if [ ! -s "$MODEL_DIR/$f" ]; then
    echo "::error::checkpoint incomplete: $MODEL_DIR/$f missing or empty" >&2
    exit 1
  fi
done

mkdir -p "$OUT_DIR" || { echo "::error::could not create $OUT_DIR" >&2; exit 1; }

NSYS_VERSION="$("$NSYS_BIN" --version 2>&1 | head -1)" || NSYS_VERSION="unknown (nsys --version failed)"
# `gpu-dev.sh push` rsyncs the WORKING TREE, not `.git`, so `git rev-parse`
# inside the pushed tree has nothing to resolve — the caller passes the
# measured tip explicitly. REFUSED rather than defaulted to "unknown": an
# artifact whose `git_sha` is unresolvable is evidence about the oracle, not
# about the code (`check_cuda_run_artifacts.py`'s own rule (d)).
SHA="${AXPY_GIT_SHA:-$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || true)}"
if ! printf '%s' "$SHA" | grep -Eq '^[0-9a-f]{40}$'; then
  echo "::error::AXPY_GIT_SHA must name the measured tip as 40 lowercase hex chars (got '${SHA}') — the pushed tree carries no .git for this to be derived from" >&2
  exit 1
fi
# PROVENANCE CROSS-CHECK (unification contract C5.1, the same shape
# profile_356_legs.sh / finetune_run_ab.sh / fa2_ab.sh / encode_ab.sh /
# stacked_sweep.sh / clip_artifact_producer.sh use): refuse BEFORE any leg
# runs if the binary's own baked identity is not the sha this artifact will
# stamp. Without it the artifact could truthfully name a tip while the
# numbers came from a differently-built binary — the artifact would be
# evidence about the oracle, not about the code.
BIN_PROV_JSON="$("$BENCH_BIN" provenance 2>&1)" || {
  echo "::error::'$BENCH_BIN provenance' failed: $BIN_PROV_JSON" >&2; exit 1; }
BIN_PROV_SHA="$(printf '%s' "$BIN_PROV_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["build_sha"])' 2>&1)" || {
  echo "::error::could not parse build_sha from '$BENCH_BIN provenance' output: $BIN_PROV_JSON" >&2; exit 1; }
if [ -z "$BIN_PROV_SHA" ] || [ "$BIN_PROV_SHA" != "$SHA" ]; then
  echo "::error::'$BENCH_BIN provenance' reports build_sha=$BIN_PROV_SHA, but this run stamps sha=$SHA -- refusing before any leg." >&2
  exit 1
fi

echo "=== nsys: $NSYS_VERSION"
echo "=== tip: $SHA (binary build_sha matches)"
echo "=== bench: $BENCH_BIN"

# "id|dtype|disable_keys"  (disable_keys empty = default admission)
LEGS=(
  "L1|f32|"
  "L2|bf16|"
  "L3|f16|"
  "L4|bf16|adamw_step_fused"
)

_print_cmd() { printf '+ %q' "$1"; shift; printf ' %q' "$@"; printf '\n'; } >&2

# One traced run. Shape copied VERBATIM from `profile_356_legs.sh`'s own
# `run_traced` (see this file's header for the full list of what that
# means and why); the only additions are the leg's `JAMMI_KERNELS_DISABLE`
# value (passed through `env`, so it reaches the traced child and nothing
# else) and the ModernBERT-native selector default.
run_traced() {
  local train_jsonl="$1" dtype="$2" disable_keys="$3" work_dir="$4" \
        run_prefix="$5" out_json="$6" out_sqlite="$7"

  mkdir -p "$work_dir" || { echo "::error::run_traced: could not create $work_dir" >&2; return 1; }

  local -a cmd=(
    "$BENCH_BIN" finetune-run
    --model-dir "$MODEL_DIR" --arm fused
    --train-jsonl "$train_jsonl" --heldout-ids "$HELDOUT_IDS" --heldout-jsonl "$HELDOUT_JSONL"
    --seed 42 --epochs 1 --batch "$BATCH" --objective mnrl
    --validation-fraction 0 --early-stopping-metric train_loss --grad-accum 1
    --early-stopping-patience 10000 --backbone-dtype "$dtype"
    --lora-rank 8 --lora-alpha 16 --lora-dropout 0.05
    --target-modules "$TARGET_MODULES"
    --max-seq-length "$WIDTH"
    --eval-cadence "$EVAL_CADENCE"
    --work-dir "$work_dir" --cuda 0
  )

  # `env -u` for the default-admission legs so a stray inherited
  # JAMMI_KERNELS_DISABLE can never silently make a SHIPPED leg measure the
  # eager path (which would be indistinguishable from a real fused
  # measurement in the census — the exact confusion the L4 control exists
  # to isolate).
  local -a envwrap
  if [ -n "$disable_keys" ]; then
    envwrap=(env "JAMMI_KERNELS_DISABLE=$disable_keys")
  else
    envwrap=(env -u JAMMI_KERNELS_DISABLE)
  fi

  local -a wrapped=(bash -c 'exec "$1" "${@:2}" > "$0"' "$out_json" "${envwrap[@]}" "${cmd[@]}")

  # The REAL, would-be production command line, printed for operator
  # visibility (stderr only) — `env` wraps the TRACED CHILD, not nsys, so it
  # is printed after the `--` separator exactly where it actually applies.
  _print_cmd "$NSYS_BIN" profile --trace=cuda -o "$run_prefix" --force-overwrite=true -- \
    "${envwrap[@]}" "${cmd[@]}"
  local rc=0
  "$NSYS_BIN" profile --trace=cuda -o "$run_prefix" --force-overwrite=true -- "${wrapped[@]}" \
    2> "$run_prefix.stderr" || rc=$?

  if [ "$rc" -eq 0 ]; then
    _print_cmd "$NSYS_BIN" export --type=sqlite --output="$out_sqlite" --force-overwrite=true "$run_prefix.nsys-rep"
    "$NSYS_BIN" export --type=sqlite --output="$out_sqlite" --force-overwrite=true "$run_prefix.nsys-rep" \
      2>> "$run_prefix.stderr" || rc=$?
  fi

  if [ "$rc" -eq 0 ] && [ ! -s "$out_json" ]; then
    echo "::error::run_traced: $out_json is empty -- the traced child wrote no report" >&2
    rc=1
  fi
  return "$rc"
}

_json_field() {
  python3 -c '
import json, sys
d = json.load(open(sys.argv[1]))
tier = d.get("tiers", {}).get("finetune_run")
if tier is None or sys.argv[2] not in tier:
    print("::error::_json_field: no tiers.finetune_run." + sys.argv[2] + " in " + sys.argv[1], file=sys.stderr)
    sys.exit(1)
print(tier[sys.argv[2]])
' "$1" "$2"
}

run_leg() {
  local leg_id="$1" dtype="$2" disable_keys="$3"
  local leg_dir="$OUT_DIR/$leg_id"
  local status="ok" reason=""

  echo "=== leg $leg_id: dtype=$dtype disable=${disable_keys:-<none>} batch=$BATCH width=$WIDTH steps=$STEPS_N/$STEPS_M ==="
  mkdir -p "$leg_dir" || { echo "::error::$leg_id: could not create $leg_dir" >&2; return 0; }

  # STALE-CAPTURE GUARD (a live incident, not a hypothetical): an earlier,
  # interrupted sweep's `nsys` was still finalizing when its output
  # directory was deleted and recreated, and it then wrote a 692 MB
  # `run_m.nsys-rep` from the OLD, killed run into the NEW directory. A
  # fresh N-run differenced against a stale, half-finished M-run export is
  # silent corruption of exactly the kind the census cannot detect (both
  # exports parse, both have kernel tables, and the deltas can even come
  # out positive). `--force-overwrite=true` usually saves this, but "usually"
  # is not a validity argument, so a leg directory that already carries a
  # capture is REFUSED rather than overwritten -- the operator points at a
  # fresh OUT_DIR, the same posture profile_356_legs.sh takes for an
  # existing manifest.
  local stale
  stale="$(ls "$leg_dir"/*.nsys-rep "$leg_dir"/*.sqlite 2>/dev/null | head -3 | tr '\n' ' ')"
  if [ -n "$stale" ]; then
    status="invalid"
    reason="leg dir already carries capture file(s) ($stale) -- refusing to overwrite a foreign/stale capture; use a fresh OUT_DIR"
    echo "::error::$leg_id: $reason" >&2
  fi

  local corpus_m="$leg_dir/corpus_m${STEPS_M}.jsonl"
  local corpus_n="$leg_dir/corpus_n${STEPS_N}.jsonl"
  # `--verify-tokenizer` IS supported by the generator, and it is ATTEMPTED
  # here — but its outcome is RECORDED, not required, and the width pin is
  # separately MEASURED below. Reason: that flag asserts every `_VOCAB` word
  # is a SINGLE wordpiece, an assumption written for BERT-style WordPiece;
  # ModernBERT ships a BPE tokenizer, where a vocab word may encode to more
  # than one token. That direction is HARMLESS to the pin the corpus exists
  # to satisfy (`every text > --min-wordpieces`, so that truncation at
  # `--max-seq-length` makes every row exactly W wide): a multi-token vocab
  # word only ever INCREASES a text's token count. Treating the flag's
  # refusal as fatal would discard a corpus that satisfies the pin; ignoring
  # the pin entirely would be worse. So the pin itself is measured directly,
  # against this checkpoint's own tokenizer, and a leg whose MEASURED
  # minimum is not > W is INVALID.
  local verify_tok_status="not-run"
  if [ "$status" = "ok" ]; then
    if python3 "$DIR/gen_fixed_width_corpus.py" --rows "$(( BATCH * STEPS_M ))" \
        --min-wordpieces "$WIDTH" --seed 42 --out "$corpus_m" \
        --verify-tokenizer "$MODEL_DIR/tokenizer.json" > "$leg_dir/corpus.stdout" 2>&1; then
      verify_tok_status="pass"
    else
      verify_tok_status="refused"
      echo "::warning::$leg_id: gen_fixed_width_corpus --verify-tokenizer refused (see $leg_dir/corpus.stdout) -- regenerating WITHOUT it; the width pin is measured directly below" >&2
      if ! python3 "$DIR/gen_fixed_width_corpus.py" --rows "$(( BATCH * STEPS_M ))" \
          --min-wordpieces "$WIDTH" --seed 42 --out "$corpus_m" \
          >> "$leg_dir/corpus.stdout" 2>&1; then
        status="invalid"; reason="gen_fixed_width_corpus.py failed even without --verify-tokenizer -- see $leg_dir/corpus.stdout"
      fi
    fi
  fi
  if [ "$status" = "ok" ]; then
    head -n "$(( BATCH * STEPS_N ))" "$corpus_m" > "$corpus_n" || {
      status="invalid"; reason="head -n slicing the N-step corpus failed"
    }
  fi

  # MEASURED width pin: encode a deterministic sample of the generated texts
  # with THIS checkpoint's own tokenizer and assert the MINIMUM exceeds
  # $WIDTH. This is the property the census depends on (every batch exactly
  # W wide after truncation), measured rather than inherited from the
  # generator's docstring.
  local width_min="" width_max=""
  if [ "$status" = "ok" ]; then
    if python3 - "$corpus_m" "$MODEL_DIR/tokenizer.json" "$WIDTH" \
        > "$leg_dir/width_probe.json" 2> "$leg_dir/width_probe.stderr" <<'PY'
import json, sys
from tokenizers import Tokenizer
corpus, tok_path, width = sys.argv[1], sys.argv[2], int(sys.argv[3])
tok = Tokenizer.from_file(tok_path)
lo, hi, n = None, None, 0
with open(corpus) as f:
    for i, line in enumerate(f):
        if i % 97:                      # deterministic stride sample
            continue
        row = json.loads(line)
        for k in ("anchor_text", "positive_text", "negative_text"):
            m = len(tok.encode(row[k], add_special_tokens=False).ids)
            lo = m if lo is None else min(lo, m)
            hi = m if hi is None else max(hi, m)
            n += 1
if lo is None:
    print("::error::width probe sampled zero texts", file=sys.stderr)
    sys.exit(1)
json.dump({"texts_sampled": n, "min_tokens": lo, "max_tokens": hi, "width": width}, sys.stdout)
if lo <= width:
    print(f"::error::width pin VIOLATED: min token count {lo} <= --max-seq-length {width}",
          file=sys.stderr)
    sys.exit(1)
PY
    then
      width_min="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["min_tokens"])' "$leg_dir/width_probe.json")"
      width_max="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["max_tokens"])' "$leg_dir/width_probe.json")"
    else
      status="invalid"
      reason="measured width pin failed -- see $leg_dir/width_probe.stderr"
      cat "$leg_dir/width_probe.stderr" >&2
    fi
  fi

  local out_n="$leg_dir/run_n.json" out_m="$leg_dir/run_m.json"
  local sq_n="$leg_dir/run_n.sqlite" sq_m="$leg_dir/run_m.sqlite"

  if [ "$status" = "ok" ]; then
    run_traced "$corpus_n" "$dtype" "$disable_keys" "$leg_dir/work_n" "$leg_dir/run_n" "$out_n" "$sq_n" || {
      status="invalid"; reason="run_traced (N-step) failed -- see $leg_dir/run_n.stderr"
    }
  fi
  if [ "$status" = "ok" ]; then
    run_traced "$corpus_m" "$dtype" "$disable_keys" "$leg_dir/work_m" "$leg_dir/run_m" "$out_m" "$sq_m" || {
      status="invalid"; reason="run_traced (M-step) failed -- see $leg_dir/run_m.stderr"
    }
  fi

  local wall_n="" wall_m="" sm_n="" sm_m=""
  if [ "$status" = "ok" ]; then
    wall_n="$(_json_field "$out_n" train_run_wall_s)" || { status="invalid"; reason="no train_run_wall_s on the N run"; }
    wall_m="$(_json_field "$out_m" train_run_wall_s)" || { status="invalid"; reason="no train_run_wall_s on the M run"; }
    sm_n="$(_json_field "$out_n" steps_measured 2>/dev/null)" || sm_n=""
    sm_m="$(_json_field "$out_m" steps_measured 2>/dev/null)" || sm_m=""
  fi

  local census_json="$leg_dir/census.json" census_ok="false" census_exit=""
  if [ "$status" = "ok" ]; then
    local -a census_cmd=(
      python3 "$DIR/kernel_census.py" "$sq_n" "$sq_m" "$STEPS_N" "$STEPS_M" "$census_json"
      --wall-a "$wall_n" --wall-b "$wall_m"
    )
    [ -n "$sm_n" ] && census_cmd+=(--steps-measured-a "$sm_n")
    [ -n "$sm_m" ] && census_cmd+=(--steps-measured-b "$sm_m")
    _print_cmd "${census_cmd[@]}"
    census_exit=0
    "${census_cmd[@]}" > "$leg_dir/census.stdout" 2> "$leg_dir/census.stderr" || census_exit=$?
    cat "$leg_dir/census.stdout"
    cat "$leg_dir/census.stderr" >&2
    if [ "$census_exit" -eq 0 ] && [ -s "$census_json" ]; then
      census_ok="true"
    else
      status="invalid"
      reason="kernel_census.py refused (exit $census_exit) -- see $leg_dir/census.stderr"
    fi
  fi

  # The axpy-pair analysis + the fused/eager adamw SANITY check. Runs only
  # on a census-ok leg: a P computed off a refused census would be a number
  # with no validity behind it.
  local pairs_json="$leg_dir/axpy_pairs.json" pairs_ok="false"
  if [ "$status" = "ok" ]; then
    local pairs_exit=0
    python3 "$DIR/axpy_pair_census.py" \
      --sqlite-a "$sq_n" --sqlite-b "$sq_m" \
      --steps-a "$STEPS_N" --steps-b "$STEPS_M" \
      --census "$census_json" --leg-id "$leg_id" --dtype "$dtype" \
      --disable-keys "$disable_keys" \
      --run-json-a "$out_n" --run-json-b "$out_m" \
      --out "$pairs_json" > "$leg_dir/pairs.stdout" 2> "$leg_dir/pairs.stderr" || pairs_exit=$?
    cat "$leg_dir/pairs.stdout"
    cat "$leg_dir/pairs.stderr" >&2
    if [ "$pairs_exit" -eq 0 ] && [ -s "$pairs_json" ]; then
      pairs_ok="true"
    else
      status="invalid"
      reason="axpy_pair_census.py refused (exit $pairs_exit) -- see $leg_dir/pairs.stderr"
    fi
  fi

  # Attribution EVIDENCE, produced while the captures still exist: the
  # ordered kernel neighbourhood of every axpy-shaped pair, grouped into
  # signatures. Descriptive only — it decides nothing, so a failure here
  # degrades the evidence, never the leg's status or its P.
  local context_json="$leg_dir/axpy_pair_context.json"
  if [ "$status" = "ok" ]; then
    python3 "$DIR/axpy_pair_context.py" --sqlite "$sq_m" --out "$context_json" \
      > "$leg_dir/context.stdout" 2> "$leg_dir/context.stderr" \
      || echo "::warning::$leg_id: axpy_pair_context.py failed -- see $leg_dir/context.stderr (evidence only; the leg's P is unaffected)" >&2
    head -20 "$leg_dir/context.stdout" 2>/dev/null || true
  fi

  # Recorded BEFORE the disk-budget cleanup below deletes them: the two
  # corpora are regenerable byte-for-byte (`--seed 42`), and these digests
  # are what makes that claim checkable rather than asserted.
  local corpus_sha_n="" corpus_sha_m=""
  [ -f "$corpus_n" ] && corpus_sha_n="$(sha256sum "$corpus_n" | awk '{print $1}')"
  [ -f "$corpus_m" ] && corpus_sha_m="$(sha256sum "$corpus_m" | awk '{print $1}')"

  # DISK BUDGET: a 600-step W=512 trace is multi-GB as a `.nsys-rep` and
  # again as a `.sqlite`; four legs would exhaust the pod's free space
  # mid-sweep and turn a later leg INVALID for a reason that has nothing to
  # do with the measurement. The raw captures are deleted only AFTER both
  # consumers (kernel_census.py, axpy_pair_census.py) have run — the same
  # "census.json + manifest are the records" deviation unit-356's own
  # close-out artifact recorded. `AXPY_KEEP_RAW=1` keeps them.
  if [ "${AXPY_KEEP_RAW:-0}" != "1" ]; then
    rm -f "$leg_dir/run_n.nsys-rep" "$leg_dir/run_m.nsys-rep" "$sq_n" "$sq_m"
    rm -rf "$leg_dir/work_n" "$leg_dir/work_m"
    # The corpora are regenerable byte-for-byte from
    # `gen_fixed_width_corpus.py --seed 42` and are the bulk of what is
    # left; their sha256 is recorded in the manifest instead.
    rm -f "$corpus_m" "$corpus_n"
  fi

  # Every value crosses into python as an ENVIRONMENT VARIABLE, never
  # interpolated into the source text: a shell `${x:-null}` expansion emits
  # the bare token `null`, which is valid JSON but a `NameError` in python —
  # the smoke run's own first failure. Empty string means "absent" and is
  # mapped to JSON null in ONE place by a typed helper, so a malformed
  # number surfaces as a crash rather than being silently nulled.
  MF_LEG="$leg_id" MF_SHA="$SHA" MF_NSYS="$NSYS_VERSION" MF_DTYPE="$dtype" \
  MF_DISABLE="$disable_keys" MF_BATCH="$BATCH" MF_WIDTH="$WIDTH" \
  MF_TARGETS="$TARGET_MODULES" MF_EVALCAD="$EVAL_CADENCE" \
  MF_CSHA_N="$corpus_sha_n" MF_CSHA_M="$corpus_sha_m" MF_VTOK="$verify_tok_status" \
  MF_WMIN="$width_min" MF_WMAX="$width_max" \
  MF_SN="$STEPS_N" MF_SM="$STEPS_M" MF_SMEAS_N="$sm_n" MF_SMEAS_M="$sm_m" \
  MF_WALL_N="$wall_n" MF_WALL_M="$wall_m" MF_STATUS="$status" MF_REASON="$reason" \
  MF_CENSUS_OK="$census_ok" MF_CENSUS_EXIT="$census_exit" MF_PAIRS_OK="$pairs_ok" \
  python3 - "$leg_dir/manifest.json" <<'PY'
import json, os, sys


def s(k):
    return os.environ.get(k, "")


def opt(k, cast):
    v = os.environ.get(k, "")
    return None if v == "" else cast(v)


json.dump({
    "leg_id": s("MF_LEG"),
    "git_sha": s("MF_SHA"),
    "nsys_version": s("MF_NSYS"),
    "dtype": s("MF_DTYPE"),
    "kernels_disable_keys": s("MF_DISABLE"),
    "batch": int(s("MF_BATCH")),
    "width": int(s("MF_WIDTH")),
    "target_modules": s("MF_TARGETS"),
    "eval_cadence": int(s("MF_EVALCAD")),
    "corpus_sha256_n": s("MF_CSHA_N") or None,
    "corpus_sha256_m": s("MF_CSHA_M") or None,
    "verify_tokenizer_flag": s("MF_VTOK"),
    "measured_min_tokens_per_text": opt("MF_WMIN", int),
    "measured_max_tokens_per_text": opt("MF_WMAX", int),
    "steps_declared_n": int(s("MF_SN")),
    "steps_declared_m": int(s("MF_SM")),
    "steps_measured_n": opt("MF_SMEAS_N", int),
    "steps_measured_m": opt("MF_SMEAS_M", int),
    "train_run_wall_s_n": opt("MF_WALL_N", float),
    "train_run_wall_s_m": opt("MF_WALL_M", float),
    "status": s("MF_STATUS"),
    "reason": s("MF_REASON"),
    "census_ok": s("MF_CENSUS_OK") == "true",
    "census_exit": opt("MF_CENSUS_EXIT", int),
    "pairs_ok": s("MF_PAIRS_OK") == "true",
}, open(sys.argv[1], "w"), indent=1)
PY
  echo "=== leg $leg_id: status=$status ${reason:+reason=$reason}"
  return 0
}

for spec in "${LEGS[@]}"; do
  IFS='|' read -r leg_id dtype disable_keys <<< "$spec"
  if [ -n "$AXPY_LEGS_ONLY" ]; then
    case ",$AXPY_LEGS_ONLY," in
      *",$leg_id,"*) ;;
      *) continue ;;
    esac
  fi
  run_leg "$leg_id" "$dtype" "$disable_keys"
done

echo "=== sweep complete -> $OUT_DIR"
