#!/usr/bin/env python3
"""Hermetic tests for `frontend_ab.sh` itself (issue #421 follow-on, "media
front-end parallelization" contract) -- the same "the shell PRODUCER itself
must run in CI at least once, zero-execution is RED not a skip" doctrine
`test_profile_421_legs_dry_run.py`/`test_finetune_ab_sh_dry_run.py` already
carry: this drives the REAL `bash ci/scripts/perf/frontend_ab.sh` subprocess
end to end, never a re-implementation of its control flow.

`FRONTEND_AB_DRY_RUN=1` swaps `$BASE_BIN`/`$TIP_BIN` for hermetic stand-ins
generated BY THE SCRIPT ITSELF that read and VALIDATE their own real argv
(never a fixed-positional-argument stub) -- a regression that drops/garbles
a required `finetune-run` flag fails here, hermetically, rather than only on
a real pod run. The two real media corpus producers ALWAYS run for real
under DRY_RUN too (esc-088, `.jammi/escapes.jsonl`), so this suite also
exercises that they still emit real, non-empty files.

A handful of `FRONTEND_AB_DRY_RUN_*` env levers exist ONLY to make the
bar-decision arithmetic's four branches (PASS / FAIL / INVALID_BEATS_IDEAL /
UNRESOLVED) and the provenance-mismatch refusal deterministically
reachable from a hermetic test -- see `frontend_ab.sh`'s own module doc and
its stub-generation comments for what each one does; none of them exists on
a real (non-dry) run.

Run: `python3 ci/scripts/perf/test_frontend_ab_dry_run.py`
"""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
import unittest

PERF_DIR = os.path.dirname(os.path.abspath(__file__))
SCRIPT = os.path.join(PERF_DIR, "frontend_ab.sh")
REPO_ROOT = os.path.abspath(os.path.join(PERF_DIR, "..", "..", ".."))

TOWERS = ("htsat", "clip-vision")
ROLES = ("base", "tip")
REPEATS = ("r1", "r2")


def run_dry(out_dir, extra_env=None, serial_tail_ratio="0.01"):
    env = dict(os.environ)
    env["FRONTEND_AB_DRY_RUN"] = "1"
    env["OUT_DIR"] = out_dir
    if serial_tail_ratio is not None:
        env["FRONTEND_AB_SERIAL_TAIL_RATIO"] = serial_tail_ratio
    else:
        env.pop("FRONTEND_AB_SERIAL_TAIL_RATIO", None)
    # A leftover ambient value must not silently leak into this suite's own
    # ordinary-path tests.
    env.pop("JAMMI_KERNELS_DISABLE", None)
    for key in list(env):
        if key.startswith("BASE_") or key.startswith("TIP_") or key == "BOX" or key == "BOX_SLUG":
            env.pop(key, None)
    if extra_env:
        env.update(extra_env)
    return subprocess.run(
        ["bash", SCRIPT], env=env, capture_output=True, text=True, timeout=300, cwd=REPO_ROOT
    )


def _fail_msg(result):
    return f"exit={result.returncode}\nstdout={result.stdout}\nstderr={result.stderr}"


def _report(out_dir):
    with open(os.path.join(out_dir, "report.json"), encoding="utf-8") as f:
        return json.load(f)


class DryRunSmokeTests(unittest.TestCase):
    def test_dry_run_exits_zero_and_writes_a_green_report_by_default(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir)
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            report = _report(out_dir)
            self.assertEqual(report["status"], "GREEN", _fail_msg(result))
            self.assertTrue(report["dry_run"])

    def test_every_tower_role_repeat_leg_is_recorded_ok(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir)
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            report = _report(out_dir)
            for tower in TOWERS:
                for role in ROLES:
                    for repeat in REPEATS:
                        leg = report["towers"][tower][role][repeat]
                        self.assertEqual(
                            leg["outcome"], "OK", f"{tower}/{role}/{repeat}: {leg}"
                        )
                        self.assertEqual(leg["steps_measured"], 100)

    def test_frontend_ab_repeats_widens_the_leg_set_to_r1_through_rn(self):
        # FRONTEND_AB_REPEATS=3 -- non-vacuous: the default (2) already
        # writes r1/r2, so this asserts r3 SPECIFICALLY exists, which a
        # driver that silently ignored the knob would never produce.
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir, extra_env={"FRONTEND_AB_REPEATS": "3"})
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            report = _report(out_dir)
            self.assertEqual(report["repeats"], 3)
            for tower in TOWERS:
                for role in ROLES:
                    self.assertIn("r3", report["towers"][tower][role])
                    self.assertEqual(report["towers"][tower][role]["r3"]["outcome"], "OK")

    def test_a_non_positive_frontend_ab_repeats_refuses_before_any_leg_runs(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir, extra_env={"FRONTEND_AB_REPEATS": "0"})
            self.assertEqual(result.returncode, 2, _fail_msg(result))
            self.assertIn("FRONTEND_AB_REPEATS", result.stderr)

    def test_default_knobs_produce_a_pass_shaped_bar(self):
        # P = 13 -> ideal = 12; ratio = 0.10 sits inside [lower, upper] for
        # every r -- see frontend_ab.sh's own module doc.
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir)
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            bar = _report(out_dir)["htsat_bar"]
            self.assertEqual(bar["verdict"], "PASS", bar)
            self.assertEqual(bar["p"], 13)
            self.assertEqual(bar["ideal"], 12.0)

    def test_clip_vision_is_report_only_no_verdict_key(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir)
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            report = _report(out_dir)
            self.assertIn("clip_vision_report_only", report)
            self.assertNotIn("verdict", report["clip_vision_report_only"])

    def test_corpus_producers_ran_for_real_and_wrote_nonempty_files(self):
        # esc-088: the corpus step must never be stubbed out under DRY_RUN.
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir)
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            for tower in TOWERS:
                corpus_dir = os.path.join(out_dir, "corpus", tower)
                for name in ("triplets.jsonl", "heldout_ids.txt", "heldout_triplets.jsonl"):
                    path = os.path.join(corpus_dir, name)
                    self.assertTrue(os.path.isfile(path), path)
                    self.assertGreater(os.path.getsize(path), 0, path)

    def test_dry_run_never_writes_the_real_committed_artifacts_directory(self):
        cuda_runs_dir = os.path.join(
            REPO_ROOT, "crates", "jammi-kernels", "artifacts", "cuda-runs"
        )
        before = set(os.listdir(cuda_runs_dir))
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir)
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            after = set(os.listdir(cuda_runs_dir))
            self.assertEqual(before, after, "DRY_RUN must never touch the real artifacts dir")
            self.assertTrue(os.path.isfile(os.path.join(out_dir, "artifact-dry-run.json")))

    def test_pinned_workload_constants_appear_on_the_htsat_command_line(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir)
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            htsat_lines = [
                line
                for line in result.stderr.splitlines()
                if line.startswith("+") and "audio_embedding" in line
            ]
            self.assertTrue(htsat_lines, _fail_msg(result))
            for line in htsat_lines:
                self.assertIn("--objective triplet", line)
                self.assertIn("--lora-init zeros_b", line)
                self.assertIn(
                    "--target-modules "
                    "query\\,key\\,value\\,attention_output\\,intermediate_dense\\,"
                    "output_dense\\,reduction\\,linear1\\,linear2",
                    line,
                )
                self.assertIn("--eval-cadence 1", line)
                self.assertIn("--batch 8", line)
                self.assertIn("--arm fused", line)

    def test_legs_interleave_base_tip_base_tip_per_tower(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir)
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            for tower in TOWERS:
                order = []
                for line in result.stderr.splitlines():
                    if not line.startswith("+"):
                        continue
                    if f"work/{tower}__base__r1" in line:
                        order.append("base")
                    elif f"work/{tower}__tip__r1" in line:
                        order.append("tip")
                    elif f"work/{tower}__base__r2" in line:
                        order.append("base")
                    elif f"work/{tower}__tip__r2" in line:
                        order.append("tip")
                self.assertEqual(order, ["base", "tip", "base", "tip"], (tower, order))


class BarVerdictTests(unittest.TestCase):
    """The bar's four branches (module doc), driven via the TEST-ONLY
    `FRONTEND_AB_DRY_RUN_*` fabrication knobs -- never by reimplementing the
    arithmetic here."""

    def test_a_slower_tip_reads_fail(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(
                out_dir, extra_env={"FRONTEND_AB_DRY_RUN_TIP_FRONT_PER_STEP": "0.005"}
            )
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            self.assertEqual(_report(out_dir)["htsat_bar"]["verdict"], "FAIL")

    def test_a_too_fast_tip_reads_invalid_beats_ideal(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(
                out_dir, extra_env={"FRONTEND_AB_DRY_RUN_TIP_FRONT_PER_STEP": "0.0005"}
            )
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            self.assertEqual(_report(out_dir)["htsat_bar"]["verdict"], "INVALID_BEATS_IDEAL")

    def test_a_wide_base_to_base_spread_reads_unresolved(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(
                out_dir,
                extra_env={"FRONTEND_AB_DRY_RUN_BASE_FRONT_PER_STEP_R2": "0.024"},
            )
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            bar = _report(out_dir)["htsat_bar"]
            self.assertEqual(bar["verdict"], "UNRESOLVED")
            # A genuinely non-degenerate interval (the base-to-base spread
            # the r2 override introduces) -- ratio_lo/ratio_hi propagate
            # BOTH arms' observed repeats, never a `spread / mean` fraction
            # added onto the point estimate (see frontend_ab_merge.py's own
            # module doc for the units-error class that replaces).
            self.assertLess(bar["ratio_lo"], bar["ratio_hi"])

    def test_a_bar_verdict_never_fails_the_scripts_own_exit_code(self):
        # The bar is RECORDED, never gated -- a FAIL-shaped bar is still a
        # successful, GREEN measurement run.
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(
                out_dir, extra_env={"FRONTEND_AB_DRY_RUN_TIP_FRONT_PER_STEP": "0.005"}
            )
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            self.assertEqual(_report(out_dir)["status"], "GREEN")


class ProvenanceCrossCheckTests(unittest.TestCase):
    def test_a_tip_binary_reporting_a_different_sha_refuses_before_any_leg(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(
                out_dir,
                extra_env={
                    "TIP_SHA": "1" * 40,
                    "FRONTEND_AB_DRY_RUN_TIP_PROVENANCE_SHA_OVERRIDE": "2" * 40,
                },
            )
            self.assertNotEqual(result.returncode, 0, _fail_msg(result))
            self.assertIn("reports build_sha=", result.stderr)
            self.assertIn("but the operator declared", result.stderr)
            self.assertFalse(os.path.exists(os.path.join(out_dir, "report.json")))

    def test_matching_declared_and_reported_shas_do_not_refuse(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(
                out_dir,
                extra_env={"TIP_SHA": "3" * 40, "BASE_SHA": "4" * 40},
            )
            self.assertEqual(result.returncode, 0, _fail_msg(result))
            report = _report(out_dir)
            self.assertEqual(report["tip_sha"], "3" * 40)
            self.assertEqual(report["base_sha"], "4" * 40)


class SerialTailRatioValidationTests(unittest.TestCase):
    def test_missing_ratio_refuses_before_any_leg_runs(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir, serial_tail_ratio=None)
            self.assertEqual(result.returncode, 2, _fail_msg(result))
            self.assertIn("FRONTEND_AB_SERIAL_TAIL_RATIO is required", result.stderr)
            self.assertFalse(os.listdir(out_dir) if os.path.isdir(out_dir) else [])

    def test_a_ratio_above_1_refuses(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir, serial_tail_ratio="1.5")
            self.assertEqual(result.returncode, 2, _fail_msg(result))
            self.assertIn("must be a float in [0, 1]", result.stderr)

    def test_a_negative_ratio_refuses(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir, serial_tail_ratio="-0.1")
            self.assertEqual(result.returncode, 2, _fail_msg(result))
            self.assertIn("must be a float in [0, 1]", result.stderr)

    def test_a_non_numeric_ratio_refuses(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(out_dir, serial_tail_ratio="not-a-number")
            self.assertEqual(result.returncode, 2, _fail_msg(result))


class AmbientDisableEnvGuardTests(unittest.TestCase):
    def test_an_ambient_kernels_disable_env_var_refuses_before_any_leg_runs(self):
        with tempfile.TemporaryDirectory() as out_dir:
            env = dict(os.environ)
            env["FRONTEND_AB_DRY_RUN"] = "1"
            env["OUT_DIR"] = out_dir
            env["FRONTEND_AB_SERIAL_TAIL_RATIO"] = "0.01"
            env["JAMMI_KERNELS_DISABLE"] = "attention_block_flash"
            result = subprocess.run(
                ["bash", SCRIPT], env=env, capture_output=True, text=True, timeout=300,
                cwd=REPO_ROOT,
            )
            self.assertEqual(result.returncode, 2, _fail_msg(result))
            self.assertIn("JAMMI_KERNELS_DISABLE is set", result.stderr)


class RealRunRequiredEnvTests(unittest.TestCase):
    def test_a_non_dry_invocation_with_no_env_refuses_naming_every_missing_var(self):
        with tempfile.TemporaryDirectory() as out_dir:
            env = dict(os.environ)
            env["OUT_DIR"] = out_dir
            env["FRONTEND_AB_SERIAL_TAIL_RATIO"] = "0.01"
            env.pop("FRONTEND_AB_DRY_RUN", None)
            for key in (
                "BASE_BIN", "TIP_BIN", "BASE_SHA", "TIP_SHA", "BOX",
                "MODEL_DIR_CLIP", "MODEL_DIR_CLAP",
            ):
                env.pop(key, None)
            result = subprocess.run(
                ["bash", SCRIPT], env=env, capture_output=True, text=True, timeout=60,
                cwd=REPO_ROOT,
            )
            self.assertEqual(result.returncode, 2, _fail_msg(result))
            for name in (
                "BASE_BIN", "TIP_BIN", "BASE_SHA", "TIP_SHA", "BOX",
                "MODEL_DIR_CLIP", "MODEL_DIR_CLAP",
            ):
                self.assertIn(name, result.stderr)


class LegFailureTests(unittest.TestCase):
    """A REAL leg failure (the stub exits nonzero, exactly what a crashed
    real `finetune-run` invocation would do) must be recorded as this leg's
    own outcome and must flip the merged report's `status` to `INVALID`
    with `htsat_bar` absent -- never silently papered over by treating a
    missing/failed leg as if it had reported zero. Non-vacuous: a merge step
    that ignored `exit != 0` entirely would still read `status: GREEN` here,
    which is exactly the failure mode this test is written to catch."""

    def test_one_failed_leg_marks_the_whole_report_invalid_with_no_bar(self):
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(
                out_dir,
                extra_env={"FRONTEND_AB_DRY_RUN_FAIL_LEG": "audio_embedding__base__r1"},
            )
            # The driver itself must still exit nonzero when status != GREEN
            # (frontend_ab.sh's own final exit-code check).
            self.assertNotEqual(result.returncode, 0, _fail_msg(result))
            report = _report(out_dir)
            self.assertEqual(report["status"], "INVALID", _fail_msg(result))
            self.assertIsNone(report["htsat_bar"])
            failed_leg = report["towers"]["htsat"]["base"]["r1"]
            self.assertEqual(failed_leg["outcome"], "FAIL")

    def test_sibling_legs_still_run_after_one_leg_fails(self):
        # encode_ab.sh/finetune_run_ab.sh's own convention: a leg failure
        # never aborts the sweep.
        with tempfile.TemporaryDirectory() as out_dir:
            result = run_dry(
                out_dir,
                extra_env={"FRONTEND_AB_DRY_RUN_FAIL_LEG": "audio_embedding__base__r1"},
            )
            report = _report(out_dir)
            self.assertEqual(
                report["towers"]["htsat"]["tip"]["r1"]["outcome"], "OK", _fail_msg(result)
            )
            self.assertEqual(
                report["towers"]["htsat"]["base"]["r2"]["outcome"], "OK", _fail_msg(result)
            )
            self.assertEqual(
                report["towers"]["clip-vision"]["base"]["r1"]["outcome"], "OK", _fail_msg(result)
            )


if __name__ == "__main__":
    unittest.main()
