#!/usr/bin/env python3
"""The lanes CI runs, as one typed table: `ci/lanes.toml`, rendered into every
workflow under `.github/workflows/` and the maintainer page that describes
them.

    python3 ci/scripts/lanes.py render          # write the workflows and the page
    python3 ci/scripts/lanes.py check           # they are what the table renders
    python3 ci/scripts/lanes.py list [WORKFLOW] # the lanes, by workflow
    python3 ci/scripts/lanes.py run LANE        # a lane's commands, here, in order
    python3 ci/scripts/lanes.py --self-test

A lane is a command with four typed properties: the host it runs on, what it
needs of that host, when it runs, and what it produces or consumes. Every
property GitHub spells per job -- `runs-on`, `container`, `services`,
`needs`, `if`, `permissions`, the checkout, the toolchain, the artifact
uploads and downloads, the release gate, the summary -- is derived from those
four here, once, so the workflows carry no logic of their own and a state the
table cannot express cannot reach a workflow: a paid lane on a pull request,
a publisher off a tag, a secret a lane never declared, an artifact nothing
builds, a feature spelled where the manifest should be read.

The rendered files are committed, because GitHub reads YAML; `check` holds
them equal to what the table renders, and `render` rewrites them. A lane's
`why` is the one sentence above its job; the architecture is the page.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "ci" / "scripts"))
import ci_image  # noqa: E402

TABLE = Path("ci/lanes.toml")
WORKFLOWS_DIR = Path(".github/workflows")
PAGE = Path("docs/maintainer/ci.md")
GENERATED = "GENERATED by ci/scripts/lanes.py from ci/lanes.toml -- edit the table, then `python3 ci/scripts/lanes.py render`."

PYTHON = "3.12"
RUNNERS = {"amd64": "ubuntu-latest", "arm64": "ubuntu-24.04-arm"}
MACOS_RUNNER = "macos-14"
TARGETS = {"amd64": "x86_64", "arm64": "aarch64"}
HOSTS = ("cpu-image", "cuda-image", "ubuntu", "macos", "colab")
IMAGE_HOSTS = {"cpu-image": "cpu", "cuda-image": "cuda"}
BARE_HOSTS = ("ubuntu", "macos")
TRIGGER_KINDS = ("pr", "main", "schedule", "dispatch")
PUBLISHES = ("release", "ci-image", "alias")
RUST = (True, "release", "no-sccache")
SUMMARY_LANE = "ci-summary"
PROOF_LANE = "proof"
AWAIT_LANE = "await-images"
ARTIFACT_RUN_ENV = "JAMMI_ARTIFACT_RUN"
# The test-backend credentials every lane that provisions Postgres shares.
PG_USER, PG_PASSWORD, PG_DB = "jammi", "jammi", "jammi_test"
PG_URL = f"postgres://{PG_USER}:{PG_PASSWORD}@postgres:5432/{PG_DB}"

# What a lane may need of its host beyond the image: the permission it widens,
# or the provisioning it renders. A secret enters a job only through a need.
PERMISSION_NEEDS = {
    "ghcr": {"packages": "write"},
    "attest": {"id-token": "write", "attestations": "write"},
    "oidc": {"id-token": "write"},
    "release-write": {"contents": "write"},
    "pages": {"pages": "write", "id-token": "write"},
    "actions-read": {"actions": "read"},
}
PROVISION_NEEDS = ("postgres", "s3", "cutlass", "nccl", "kubeconform", "full-history", "hub-token", "runpod", "audit-key", "python", "maturin", "node")
NEEDS = (*PERMISSION_NEEDS, *PROVISION_NEEDS)
# Step text that publishes: allowed only in a lane that declares what it promotes.
PUBLISH_PRIMITIVES = (
    "./.github/actions/push-image-leg",
    "./.github/actions/merge-index",
    "./.github/actions/release-upload",
    "pypa/gh-action-pypi-publish",
    "actions/deploy-pages",
    "npm publish",
    "cargo publish",
    "publish_crates.sh",
    "imagetools create",
    "gh release",
)
# Step text that builds a wheel: every such lane must then hold the wheel to
# PyPI's per-file limit, in the same lane, before uploading it.
WHEEL_BUILDS = ("maturin build", "python -m build", "wheel tags", "build_native_cu12_wheel.sh")
WHEEL_GATE = "assert_wheel_size.sh"
COMPILES = ("cargo build", "cargo test", "cargo clippy", "cargo nextest", "maturin build", "python -m build", "npm run build")
NEEDS_REF = re.compile(r"needs\.([A-Za-z0-9_-]+)\.")
SCRIPT_REF = re.compile(r"ci/scripts/[\w./-]+\.sh")
FEATURE_FLAG = re.compile(r"(?:--features|(?<![\w-])-F)(?:=|\s+)([\"']?[\w,/ -]+)")


class TableError(ValueError):
    """The table is not what its schema says, or says something CI cannot be."""


def fields(table: dict, where: str, required: set[str], optional: set[str]) -> dict:
    if missing := sorted(required - table.keys()):
        raise TableError(f"{where}: missing {missing}")
    if unknown := sorted(table.keys() - required - optional):
        raise TableError(f"{where}: unknown {unknown} (allowed: {sorted(required | optional)})")
    return table


@dataclass(frozen=True)
class Trigger:
    kind: str  # pr | main | nightly | dispatch | label | tag
    value: str = ""  # the label name, the tag prefix

    @staticmethod
    def parse(text: str, where: str) -> "Trigger":
        kind, _, value = text.partition(":")
        if kind in TRIGGER_KINDS and not value:
            return Trigger(kind)
        if kind in ("label", "tag") and value:
            return Trigger(kind, value)
        raise TableError(f"{where}: `{text}` is not a trigger (pr, main, schedule, dispatch, label:<name>, tag:<prefix>)")

    @property
    def text(self) -> str:
        return f"{self.kind}:{self.value}" if self.value else self.kind

    @property
    def predicate(self) -> str:
        return {
            "pr": "github.event_name == 'pull_request'",
            "main": "github.event_name == 'push'",
            "schedule": "github.event_name == 'schedule'",
            "dispatch": "github.event_name == 'workflow_dispatch'",
            "label": f"(github.event_name == 'pull_request' && github.event.label.name == '{self.value}')",
            "tag": f"startsWith(github.ref, 'refs/tags/{self.value}')",
        }[self.kind]


@dataclass(frozen=True)
class Input:
    name: str
    description: str
    type: str
    required: bool
    default: object
    options: tuple[str, ...]


@dataclass(frozen=True)
class Workflow:
    id: str
    file: str
    name: str
    doc: str
    on: tuple[Trigger, ...]
    cron: str
    cancel_superseded: bool
    group: str
    paid_cron: bool
    inputs: tuple[Input, ...]

    @property
    def tag(self) -> Trigger | None:
        tags = [t for t in self.on if t.kind == "tag"]
        return tags[0] if tags else None


@dataclass(frozen=True)
class Artifact:
    name: str
    path: str
    retention: int | None
    if_no_files_found: str
    compression: int | None


@dataclass(frozen=True)
class Step:
    raw: dict

    @property
    def kind(self) -> str:
        for k in ("run", "uses", "upload", "download"):
            if k in self.raw:
                return k
        raise TableError(f"a step is none of run/uses/upload/download: {self.raw}")

    @property
    def text(self) -> str:
        """Every string in the step, for the rules that read step text."""
        return "\n".join(_strings(self.raw))


@dataclass(frozen=True)
class Lane:
    id: str
    why: str
    workflows: tuple[str, ...]
    name: str
    when: tuple[Trigger, ...] | None
    host: str
    arch: str
    rust: object  # False | True | "release" | "no-sccache"
    needs: tuple[str, ...]
    timeout: int | str | None
    after: tuple[str, ...]
    produces: tuple[str, ...]
    consumes: tuple[str, ...]
    env: dict[str, str]
    outputs: dict[str, str]
    checkout: bool
    publishes: str | None
    environment: dict | None
    dir: str | None
    legs: tuple[dict, ...]
    steps: tuple[Step, ...]

    @property
    def text(self) -> str:
        return "\n".join([*(s.text for s in self.steps), *_strings(self.env), *_strings(list(self.legs))])

    def _expand(self, names: tuple[str, ...]) -> tuple[str, ...]:
        """`names`, each `{field}` filled from every leg (an artifact name per leg)."""
        out: list[str] = []
        for name in names:
            if "{" not in name:
                out.append(name)
                continue
            if not self.legs:
                raise TableError(f"lane.{self.id}: `{name}` names a leg field and the lane has no legs")
            for leg in self.legs:
                try:
                    out.append(name.format(**_leg_fields(self, leg)))
                except KeyError as e:
                    raise TableError(f"lane.{self.id}: `{name}` names field {e} that a leg lacks") from None
        return tuple(dict.fromkeys(out))

    @property
    def produced(self) -> tuple[str, ...]:
        return self._expand(self.produces)

    @property
    def consumed(self) -> tuple[str, ...]:
        return self._expand(self.consumes)


@dataclass(frozen=True)
class Table:
    workflows: dict[str, Workflow]
    artifacts: dict[str, Artifact]
    actions: dict[str, str]
    lanes: dict[str, Lane]

    def producer(self, artifact: str) -> Lane:
        for lane in self.lanes.values():
            if artifact in lane.produced:
                return lane
        raise TableError(f"artifact `{artifact}` is produced by no lane")

    def in_workflow(self, workflow: str) -> list[Lane]:
        return [lane for lane in self.lanes.values() if workflow in lane.workflows]


def _leg_fields(lane: "Lane", leg: dict) -> dict:
    """A leg's fields with the ones the renderer derives: `target` and
    `platform` from `arch`."""
    out = {k: v for k, v in leg.items() if k != "host"}
    arch = leg.get("arch", lane.arch)
    if "arch" in leg:
        out.setdefault("target", TARGETS[arch])
        out.setdefault("platform", f"linux/{arch}")
    return out


def _strings(node) -> list[str]:
    if isinstance(node, dict):
        return [s for v in node.values() for s in _strings(v)]
    if isinstance(node, list):
        return [s for v in node for s in _strings(v)]
    return [node] if isinstance(node, str) else []


# ----------------------------------------------------------------------------- parse
def parse(text: str, root: Path | None = None) -> Table:
    """The table `text` describes; with `root`, the rules that read what a
    step runs also read the scripts it names, transitively."""
    doc = tomllib.loads(text)
    fields(doc, "top level", {"workflow", "artifact", "action", "lane"}, set())
    workflows = {wid: _parse_workflow(wid, t) for wid, t in doc["workflow"].items()}
    artifacts = {
        name: Artifact(
            name,
            **{
                k.replace("-", "_"): v
                for k, v in {
                    "retention": None,
                    "if-no-files-found": "error",
                    "compression": None,
                    **fields(t, f"artifact.{name}", {"path"}, {"retention", "if-no-files-found", "compression"}),
                }.items()
            },
        )
        for name, t in doc["artifact"].items()
    }
    actions = doc["action"]
    for alias, ref in actions.items():
        if not isinstance(ref, str) or not re.fullmatch(r"[\w.-]+/[\w.-]+@[0-9a-f]{40} # .+", ref):
            raise TableError(f"action.{alias}: not `owner/repo@<40-hex sha> # <version>`: {ref!r}")
    lanes = {lid: _parse_lane(lid, t, workflows) for lid, t in doc["lane"].items()}
    table = Table(workflows, artifacts, actions, lanes)
    for finding in validate(table, root):
        raise TableError(finding)
    return table


def _parse_workflow(wid: str, t: dict) -> Workflow:
    where = f"workflow.{wid}"
    fields(t, where, {"name", "doc", "on"}, {"file", "cron", "cancel-superseded", "group", "paid-cron", "inputs"})
    on = tuple(Trigger.parse(x, where) for x in t["on"])
    if ("schedule" in [x.kind for x in on]) != ("cron" in t):
        raise TableError(f"{where}: `cron` exactly when `on` carries schedule")
    if sum(x.kind == "tag" for x in on) > 1:
        raise TableError(f"{where}: one tag family per workflow")
    inputs = []
    for name, it in t.get("inputs", {}).items():
        fields(it, f"{where}.inputs.{name}", {"description", "type"}, {"required", "default", "options"})
        inputs.append(Input(name, it["description"], it["type"], it.get("required", False), it.get("default"), tuple(it.get("options", ()))))
    if inputs and "dispatch" not in [x.kind for x in on]:
        raise TableError(f"{where}: inputs without a dispatch trigger")
    return Workflow(
        wid,
        t.get("file", f"{wid}.yml"),
        t["name"],
        t["doc"].strip(),
        on,
        t.get("cron", ""),
        t.get("cancel-superseded", False),
        t.get("group", f"{wid}-${{{{ github.ref }}}}"),
        t.get("paid-cron", False),
        tuple(inputs),
    )


def _parse_lane(lid: str, t: dict, workflows: dict[str, Workflow]) -> Lane:
    where = f"lane.{lid}"
    fields(
        t,
        where,
        {"why", "steps"},
        {"workflow", "name", "when", "host", "arch", "rust", "needs", "timeout", "after", "produces", "consumes", "env", "outputs", "checkout", "publishes", "environment", "dir", "legs"},
    )
    wf = t.get("workflow", "ci")
    wfs = tuple([wf] if isinstance(wf, str) else wf)
    for w in wfs:
        if w not in workflows:
            raise TableError(f"{where}: unknown workflow `{w}`")
    when = None
    if "when" in t:
        when = tuple(Trigger.parse(x, where) for x in t["when"])
        every = {x for w in wfs for x in workflows[w].on}
        if not set(when) <= every:
            raise TableError(f"{where}: `when` names a trigger its workflows lack ({[x.text for x in when]} vs {sorted(x.text for x in every)})")
        for w in wfs:
            if not set(when) & set(workflows[w].on):
                raise TableError(f"{where}: `when` leaves it nothing to run on in `{w}`")
    host = t.get("host", "cpu-image")
    if host not in HOSTS:
        raise TableError(f"{where}: host `{host}` is none of {HOSTS}")
    arch = t.get("arch", "amd64")
    if arch not in RUNNERS:
        raise TableError(f"{where}: arch `{arch}` is none of {sorted(RUNNERS)}")
    rust = t.get("rust", False)
    if rust is not False and rust not in RUST:
        raise TableError(f"{where}: rust is true, \"release\" or \"no-sccache\"")
    needs = tuple(t.get("needs", ()))
    for n in needs:
        if n not in NEEDS:
            raise TableError(f"{where}: unknown need `{n}` (needs: {NEEDS})")
    publishes = t.get("publishes")
    if publishes is not None and publishes not in PUBLISHES:
        raise TableError(f"{where}: publishes is one of {PUBLISHES}")
    legs = tuple(t.get("legs", ()))
    for leg in legs:
        if "host" in leg and leg["host"] not in HOSTS:
            raise TableError(f"{where}: a leg's host `{leg['host']}` is none of {HOSTS}")
        if "arch" in leg and leg["arch"] not in RUNNERS:
            raise TableError(f"{where}: a leg's arch `{leg['arch']}` is none of {sorted(RUNNERS)}")
    steps = tuple(Step(s) for s in t["steps"])
    # An explicit upload step produces its artifact as surely as `produces` does.
    produces = tuple(dict.fromkeys([*t.get("produces", ()), *(s.raw["upload"] for s in steps if "upload" in s.raw)]))
    for s in steps:
        fields(s.raw, f"{where}.steps", set(), {"name", "run", "uses", "with", "env", "if", "when", "id", "dir", "shell", "upload", "download", "path", "from"})
        if s.kind == "download" and "path" not in s.raw:
            raise TableError(f"{where}.steps: a download names its path")
        s.kind
    return Lane(
        lid,
        t["why"].strip(),
        wfs,
        t.get("name", lid),
        when,
        host,
        arch,
        rust,
        needs,
        t.get("timeout"),
        tuple(t.get("after", ())),
        produces,
        tuple(t.get("consumes", ())),
        dict(t.get("env", {})),
        dict(t.get("outputs", {})),
        t.get("checkout", True),
        publishes,
        t.get("environment"),
        t.get("dir"),
        legs,
        steps,
    )


# ----------------------------------------------------------------------------- validate
def validate(table: Table, root: Path | None = None) -> list[str]:
    """What the table says that CI cannot be. Every rule is a shape a hand-written
    workflow could take and a reviewer could miss."""
    out: list[str] = []
    for lane in table.lanes.values():
        w = f"lane.{lane.id}"
        wfs = [table.workflows[x] for x in lane.workflows]
        text = lane.text
        if root is not None:
            text, missing = _with_scripts(text, root)
            out += [f"{w}: names `{m}`, which does not exist" for m in missing]
        if not lane.why.endswith("."):
            out.append(f"{w}: `why` is a sentence")
        if "${{ secrets." in text:
            out.append(f"{w}: reads a secret outside a need (hub-token, runpod)")
        try:
            edges = _edges(table, lane, wfs[0])
        except TableError as e:
            out.append(str(e))
            edges = set()
        for ref in set(NEEDS_REF.findall(text)):
            if ref not in edges and ref != PROOF_LANE:
                out.append(f"{w}: `needs.{ref}` is not an edge of this lane (after, consumes, proof)")
        if lane.publishes == "release":
            if not all(wf.tag and _when(lane, wf) == (wf.tag,) for wf in wfs):
                out.append(f"{w}: a release lane runs when its workflow's tag is pushed and never else (`when = [\"tag:...\"]`)")
            if any(c in text for c in COMPILES):
                out.append(f"{w}: a release lane compiles nothing; it promotes what the proving run built")
        elif any(p in text for p in PUBLISH_PRIMITIVES):
            if lane.publishes is None:
                out.append(f"{w}: publishes (its steps carry a publish primitive) but declares no `publishes`")
            elif any(t.kind not in ("main", "pr") for wf in wfs for t in wf.on):
                out.append(f"{w}: a `{lane.publishes}` promotion is a merge-path lane, never a release")
        if "runpod" in lane.needs:
            for wf in wfs:
                bad = [t.text for t in wf.on if t.kind in ("pr", "main", "tag") or (t.kind == "schedule" and not wf.paid_cron)]
                if bad:
                    out.append(f"{w}: rents hardware, so `{wf.id}` may fire only by label, dispatch or a reviewed schedule (`paid-cron = true`), not {bad}")
        if any(b in text for b in WHEEL_BUILDS) and WHEEL_GATE not in text:
            out.append(f"{w}: builds a wheel and never holds it to PyPI's per-file limit ({WHEEL_GATE})")
        if lane.rust == "release":
            for m in FEATURE_FLAG.finditer(text):
                if "$" not in m.group(1):
                    out.append(f"{w}: a release build spells features ({m.group(0).strip()!r}); it reads ci/release-feature-manifest.json")
        if "python" in lane.needs and lane.host not in BARE_HOSTS and not any(l.get("host") in BARE_HOSTS for l in lane.legs):
            out.append(f"{w}: the CI image carries Python; `python` is for a bare host")
        if "maturin" in lane.needs and "python" not in lane.needs:
            out.append(f"{w}: maturin on a bare host installs into the interpreter `python` provides; name both")
        if lane.host == "cuda-image" and lane.arch != "amd64":
            out.append(f"{w}: the CUDA image is amd64 only")
        if "s3" in lane.needs and "postgres" not in lane.needs:
            out.append(f"{w}: the S3-class store lane also needs postgres (the harness refuses a missing backend)")
        for a in lane.produces:
            if a not in table.artifacts:
                out.append(f"{w}: produces `{a}`, which `artifact` does not define")
        try:
            for a in lane.consumed:
                table.producer(a)
            for step in lane.steps:
                if step.kind == "download" and "from" in step.raw and step.raw["from"] not in table.workflows:
                    out.append(f"{w}: a download `from` an unknown workflow `{step.raw['from']}`")
        except TableError as e:
            out.append(f"{w}: {e}")
        for a in lane.after:
            if a not in table.lanes and a not in (PROOF_LANE, AWAIT_LANE):
                out.append(f"{w}: after `{a}`, which is no lane")
        if lane.publishes == "ci-image" and not lane.name.startswith(ci_image.BUILDER_JOB_PREFIX):
            out.append(f"{w}: a CI image builder is named `{ci_image.BUILDER_JOB_PREFIX}...` so every other workflow's wait sees its failure")
        if lane.environment is not None and lane.publishes != "release":
            out.append(f"{w}: a deployment environment belongs to a release lane")
    for name, art in table.artifacts.items():
        if not any(name in lane.produces for lane in table.lanes.values()):
            out.append(f"artifact.{name}: no lane produces it")
    for wf in table.workflows.values():
        lanes = table.in_workflow(wf.id)
        if not lanes:
            out.append(f"workflow.{wf.id}: no lane runs in it")
        if any(l.publishes == "release" for l in lanes) and wf.tag is None:
            out.append(f"workflow.{wf.id}: a release lane needs a tag trigger")
    return out


def _with_scripts(text: str, root: Path) -> tuple[str, list[str]]:
    """`text` with every `ci/scripts/*.sh` it names appended, comments dropped,
    transitively; and the scripts it names that do not exist."""
    seen: set[str] = set()
    missing: list[str] = []
    pending = SCRIPT_REF.findall(text)
    parts = [text]
    while pending:
        rel = pending.pop()
        if rel in seen:
            continue
        seen.add(rel)
        path = root / rel
        if not path.is_file():
            missing.append(rel)
            continue
        body = "\n".join(l for l in path.read_text().splitlines() if not l.lstrip().startswith("#"))
        parts.append(body)
        pending += SCRIPT_REF.findall(body)
    return "\n".join(parts), sorted(missing)


def _edges(table: Table, lane: Lane, wf: Workflow) -> set[str]:
    """The job ids `lane` may name in `needs.<id>` within `wf`."""
    edges = set(lane.after)
    producers = {table.producer(a).id for a in lane.consumed}
    local = {p for p in producers if wf.id in table.lanes[p].workflows}
    if local and local != producers:
        raise TableError(f"lane.{lane.id}: consumes from this workflow and from another at once")
    edges |= local
    if producers and not local:
        edges |= {_resolver_id(w) for w in _remote_workflows(table, lane)}
    return edges


def _remote_workflows(table: Table, lane: Lane) -> list[str]:
    """The workflows, in table order, whose runs hold what `lane` consumes."""
    return sorted({table.producer(a).workflows[0] for a in lane.consumed}, key=list(table.workflows).index)


def _resolver_id(workflow: str) -> str:
    return f"artifacts-{workflow}"


# ----------------------------------------------------------------------------- render
class Commented(str):
    """A mapping key rendered with a comment line above it."""

    comment: str

    def __new__(cls, key: str, comment: str):
        self = super().__new__(cls, key)
        self.comment = comment
        return self


class Pinned(str):
    """A scalar rendered with a trailing comment: an action reference and the
    version its sha pins, `owner/repo@<sha> # vX`."""

    comment: str

    def __new__(cls, ref: str):
        value, _, comment = ref.partition(" # ")
        self = super().__new__(cls, value)
        self.comment = comment
        return self


def render_all(table: Table, refs: dict[str, str]) -> dict[str, str]:
    """`{repo-relative path: text}` for every rendered file."""
    out = {str(WORKFLOWS_DIR / wf.file): emit(render_workflow(table, wf, refs)) for wf in table.workflows.values()}
    out[str(PAGE)] = render_page(table)
    return out


def render_workflow(table: Table, wf: Workflow, refs: dict[str, str]) -> dict:
    lanes = table.in_workflow(wf.id)
    jobs: dict = {}
    needs_await = wf.id != "ci" and any(_uses_image(l) for l in lanes)
    if needs_await:
        jobs[Commented(AWAIT_LANE, "The tree's CI images, built by ci.yml's run for the same commit.")] = _await_job(table)
    if any(l.publishes == "release" for l in lanes):
        jobs[Commented(PROOF_LANE, "The release gate: the tree's recorded verdicts, and the tag names its version.")] = _proof_job(table, wf)
    local = {x.id for x in lanes}
    for other in sorted({w for l in lanes if _consumes_other_run(table, l, wf) for w in _remote_workflows(table, l)}, key=list(table.workflows).index):
        names = sorted({a for l in lanes for a in l.consumed if table.producer(a).id not in local and table.producer(a).workflows[0] == other})
        jobs[Commented(_resolver_id(other), f"The {other}.yml run that proved this tree, which holds what this workflow installs.")] = _resolver_job(table, other, names)
    for lane in lanes:
        jobs[Commented(lane.id, lane.why)] = render_job(table, wf, lane, refs, needs_await)
    if any(t.kind == "pr" for t in wf.on):
        jobs[Commented(SUMMARY_LANE, "The one check a ruleset requires: every job above succeeded or was skipped by its trigger.")] = _summary_job(list(jobs))
    doc: dict = {"name": wf.name, "on": _on(wf)}
    if wf.cancel_superseded:
        doc["concurrency"] = {"group": wf.group, "cancel-in-progress": "${{ github.ref != 'refs/heads/main' }}"}
    elif not any(l.needs and "runpod" in l.needs for l in lanes):
        doc["concurrency"] = {"group": wf.group, "cancel-in-progress": False}
    doc["permissions"] = {"contents": "read"}
    doc["jobs"] = jobs
    return {"_doc": f"{GENERATED}\n\n{wf.doc}", **doc}


def _uses_image(lane: Lane) -> bool:
    return lane.host in IMAGE_HOSTS or any(l.get("host") in IMAGE_HOSTS for l in lane.legs) or "{image:" in lane.text


def _on(wf: Workflow) -> dict:
    on: dict = {}
    kinds = {t.kind: t for t in wf.on}
    if "main" in kinds:
        on["push"] = {"branches": ["main"]}
    if "tag" in kinds:
        on["push"] = {"tags": [f"{kinds['tag'].value}*"]}
    if "pr" in kinds:
        on["pull_request"] = {}
    if "label" in kinds:
        on["pull_request"] = {"types": ["labeled"]}
    if "schedule" in kinds:
        on["schedule"] = [{"cron": wf.cron}]
    if "dispatch" in kinds:
        on["workflow_dispatch"] = {"inputs": {i.name: _input(i) for i in wf.inputs}} if wf.inputs else {}
    return on


def _input(i: Input) -> dict:
    d: dict = {"description": i.description, "required": i.required, "type": i.type}
    if i.default is not None:
        d["default"] = i.default
    if i.options:
        d["options"] = list(i.options)
    return d


def _action(table: Table, alias: str) -> Pinned:
    return Pinned(table.actions[alias])


def _checkout(table: Table, fetch_depth: int | None = None, submodules: bool | None = None) -> dict:
    step: dict = {"uses": _action(table, "checkout")}
    with_ = {}
    if fetch_depth is not None:
        with_["fetch-depth"] = fetch_depth
    if submodules is not None:
        with_["submodules"] = submodules
    if with_:
        step["with"] = with_
    return step


def _await_job(table: Table) -> dict:
    return {
        "runs-on": RUNNERS["amd64"],
        "timeout-minutes": 50,
        "permissions": {"contents": "read", "actions": "read"},
        "steps": [
            _checkout(table),
            {
                "env": {"GITHUB_TOKEN": "${{ github.token }}", "HEAD_SHA": "${{ github.event.pull_request.head.sha || github.sha }}"},
                "run": 'python3 ci/scripts/ci_image.py await --repo "$GITHUB_REPOSITORY" --head-sha "$HEAD_SHA" cpu cuda',
            },
        ],
    }


def _proof_job(table: Table, wf: Workflow) -> dict:
    return {
        "runs-on": RUNNERS["amd64"],
        "if": wf.tag.predicate,
        "timeout-minutes": 15,
        "permissions": {"contents": "read", "actions": "read"},
        "steps": [
            _checkout(table),
            {"run": 'bash ci/scripts/check_release_tag.sh "$GITHUB_REF_NAME"'},
            {
                "env": {"GITHUB_TOKEN": "${{ github.token }}"},
                "run": 'python3 ci/scripts/verdict.py require --repo "$GITHUB_REPOSITORY" --tree "$(git rev-parse "$GITHUB_SHA^{tree}")"',
            },
        ],
    }


def _resolver_job(table: Table, workflow: str, names: list[str]) -> dict:
    return {
        "runs-on": RUNNERS["amd64"],
        "permissions": {"contents": "read", "actions": "read"},
        "outputs": {"run": "${{ steps.resolve.outputs.run }}"},
        "steps": [
            _checkout(table),
            {
                "id": "resolve",
                "env": {"GITHUB_TOKEN": "${{ github.token }}", "LANE": workflow, "ARTIFACTS": " ".join(names)},
                "run": 'python3 ci/scripts/proven_artifacts.py --repo "$GITHUB_REPOSITORY" --tree "$(git rev-parse \'HEAD^{tree}\')" --lane "$LANE" --artifacts "$ARTIFACTS" >> "$GITHUB_OUTPUT"',
            },
        ],
    }


def _summary_job(job_ids: list[str]) -> dict:
    return {
        "needs": job_ids,
        "if": "always()",
        "runs-on": RUNNERS["amd64"],
        "timeout-minutes": 5,
        "permissions": {},
        "steps": [
            {
                "env": {"NEEDS": "${{ toJSON(needs) }}"},
                "run": (
                    "jq -r 'to_entries[] | \"  \\(.key) = \\(.value.result)\"' <<< \"$NEEDS\"\n"
                    "failed=\"$(jq -r 'to_entries[] | select(.value.result == \"failure\" or .value.result == \"cancelled\") | .key' <<< \"$NEEDS\")\"\n"
                    "[ -z \"$failed\" ] || { echo \"::error::failed or cancelled: $failed\"; exit 1; }\n"
                ),
            }
        ],
    }


def render_job(table: Table, wf: Workflow, lane: Lane, refs: dict[str, str], has_await: bool) -> dict:
    job: dict = {}
    if lane.name != lane.id:
        job["name"] = _template(lane.name)
    needs = sorted(_edges(table, lane, wf))
    if lane.publishes == "release":
        needs.append(PROOF_LANE)
    if wf.id == "ci":
        for image, builder in (("cpu-image", "image-cpu-merge"), ("cuda-image", "image-cuda-merge")):
            if (lane.host == image or any(l.get("host") == image for l in lane.legs)) and lane.id != builder:
                needs.append(builder)
    elif has_await and lane.id != AWAIT_LANE and _uses_image(lane):
        needs.append(AWAIT_LANE)
    if needs:
        job["needs"] = sorted(set(needs))
    when = _when(lane, wf)
    if set(when) != set(wf.on) or any(t.kind == "label" for t in wf.on):
        job["if"] = " || ".join(t.predicate for t in when)
    hosts = {leg.get("host", lane.host) for leg in lane.legs} | {lane.host}
    mixed = len(hosts) > 1 or len({leg.get("arch", lane.arch) for leg in lane.legs}) > 1
    if mixed:
        job["runs-on"] = "${{ matrix.runner }}"
        if any(_container(h, refs) for h in hosts):
            job["container"] = "${{ matrix.container }}"
    else:
        job["runs-on"] = _runner(lane.host, lane.arch)
        container = _container(lane.host, refs)
        if container:
            job["container"] = container
    if lane.environment:
        job["environment"] = lane.environment
    perms = {"contents": "read"}
    for n in lane.needs:
        perms.update(PERMISSION_NEEDS.get(n, {}))
    if _consumes_other_run(table, lane, wf) or lane.publishes == "release":
        perms["actions"] = "read"
    if perms != {"contents": "read"}:
        job["permissions"] = perms
    if "runpod" in lane.needs:
        job["concurrency"] = {"group": f"{lane.id}-${{{{ github.ref }}}}", "cancel-in-progress": False}
    if lane.timeout:
        job["timeout-minutes"] = lane.timeout
    if lane.legs:
        job["strategy"] = {"fail-fast": False, "matrix": {"include": [_leg(lane, leg, refs, mixed, "container" in job, len(hosts & set(BARE_HOSTS)) not in (0, len(hosts))) for leg in lane.legs]}}
    if "postgres" in lane.needs:
        job["services"] = {
            "postgres": {
                "image": refs["postgres"],
                "env": {"POSTGRES_USER": PG_USER, "POSTGRES_PASSWORD": PG_PASSWORD, "POSTGRES_DB": PG_DB},
                "options": f'--health-cmd "pg_isready -U {PG_USER} -d {PG_DB}" --health-interval 5s --health-timeout 5s --health-retries 12',
                "ports": ["5432:5432"],
            }
        }
    env: dict = {}
    if lane.rust:
        env.update({"CARGO_TERM_COLOR": "always", "RUST_BACKTRACE": "1"})
    if "postgres" in lane.needs:
        env["JAMMI_TEST_PG_URL"] = PG_URL
    if "hub-token" in lane.needs:
        env["HF_TOKEN"] = "${{ secrets.HF_TOKEN }}"
    if "runpod" in lane.needs:
        env.update({"RUNPOD_API_KEY": "${{ secrets.RUNPOD_API_KEY }}", "GIT_REPO": "https://github.com/${{ github.repository }}.git"})
    if lane.consumes:
        if not _consumes_other_run(table, lane, wf):
            env[ARTIFACT_RUN_ENV] = "${{ github.run_id }}"
        elif len(remotes := _remote_workflows(table, lane)) == 1:
            env[ARTIFACT_RUN_ENV] = f"${{{{ needs.{_resolver_id(remotes[0])}.outputs.run }}}}"
    env.update({k: _subst(v, refs) for k, v in lane.env.items()})
    if env:
        job["env"] = env
    if lane.outputs:
        job["outputs"] = {k: f"${{{{ {v} }}}}" for k, v in lane.outputs.items()}
    if lane.dir:
        job["defaults"] = {"run": {"working-directory": lane.dir}}
    job["steps"] = _steps(table, lane, refs, mixed)
    return job


def _when(lane: Lane, wf: Workflow) -> tuple[Trigger, ...]:
    """The triggers of `wf` the lane runs on."""
    return tuple(t for t in wf.on if lane.when is None or t in lane.when)


def _consumes_other_run(table: Table, lane: Lane, wf: Workflow) -> bool:
    return bool(lane.consumes) and not any(wf.id in table.lanes[table.producer(a).id].workflows for a in lane.consumed)


def _runner(host: str, arch: str) -> str:
    return MACOS_RUNNER if host == "macos" else RUNNERS[arch]


def _container(host: str, refs: dict[str, str]) -> str | None:
    if host in IMAGE_HOSTS:
        return refs[IMAGE_HOSTS[host]]
    if host == "colab":
        return refs["colab"]
    return None


def _leg(lane: Lane, leg: dict, refs: dict[str, str], mixed: bool, container: bool, mixed_bare: bool) -> dict:
    """A matrix row: the leg's own fields, the ones the renderer derives, and
    only those of `runner`, `container` and `bare` the job reads."""
    host = leg.get("host", lane.host)
    arch = leg.get("arch", lane.arch)
    out = _leg_fields(lane, leg)
    if mixed:
        out["runner"] = _runner(host, arch)
    if container:
        out["container"] = _container(host, refs) or ""
    if mixed_bare:
        out["bare"] = host in BARE_HOSTS
    return out


def _template(name: str) -> str:
    return re.sub(r"\{(\w+)\}", r"${{ matrix.\1 }}", name)


def _subst(text: str, refs: dict[str, str]) -> str:
    def image(m: re.Match) -> str:
        ref = refs[m.group(1)]
        repo, _, tag = ref.partition(":")
        return {"": ref, "-repo": repo, "-tag": tag}[m.group(2) or ""]

    text = re.sub(r"\{image:(\w+)(-repo|-tag)?\}", image, text)
    return text.replace("{artifact-run}", f"${{{{ env.{ARTIFACT_RUN_ENV} }}}}")


def _steps(table: Table, lane: Lane, refs: dict[str, str], mixed: bool) -> list[dict]:
    steps: list[dict] = []
    hosts = {l.get("host", lane.host) for l in lane.legs} | {lane.host}
    bare = bool(hosts & set(BARE_HOSTS))
    bare_if = None if hosts <= set(BARE_HOSTS) or not bare else "${{ matrix.bare }}"
    if lane.checkout:
        steps.append(_checkout(table, 0 if "full-history" in lane.needs else None, False if "cutlass" in lane.needs else None))
    if "cutlass" in lane.needs:
        steps.append({"name": "Init the CUTLASS submodule", "run": "git submodule update --init --depth 1 crates/jammi-kernels/third_party/cutlass"})
    if "nccl" in lane.needs:
        steps.append({"name": "The image carries NCCL (header + link library)", "run": "rpm -q libnccl libnccl-devel && test -e /usr/include/nccl.h && test -e /usr/lib64/libnccl.so"})
    if "python" in lane.needs:
        steps.append(_bare({"uses": _action(table, "setup-python"), "with": {"python-version": PYTHON}}, bare_if))
    if "maturin" in lane.needs:
        # The CI image carries maturin; a bare host takes the pip release of
        # the same version into the interpreter setup-python put on PATH.
        steps.append(_bare({"name": "maturin at its pin", "run": "bash .docker/pinned-tools.sh maturin"}, bare_if))
    if "node" in lane.needs:
        steps.append({"uses": _action(table, "setup-node"), "with": {"node-version-file": "clients/typescript/.nvmrc", "registry-url": "https://registry.npmjs.org"}})
    if lane.rust:
        if bare:
            host_step: dict = {"uses": "./.github/actions/setup-rust-host"}
            if any("rust_target" in l for l in lane.legs):
                host_step["with"] = {"targets": "${{ matrix.rust_target }}"}
            steps.append(_bare(host_step, bare_if))
        ci_step: dict = {"uses": "./.github/actions/setup-rust-ci"}
        if lane.rust == "release":
            ci_step["with"] = {"deny-warnings": "false"}
        elif lane.rust == "no-sccache":
            ci_step["with"] = {"no-sccache": "true"}
        steps.append(ci_step)
    if "kubeconform" in lane.needs:
        if bare:
            steps.append({"name": "kustomize and kubeconform at their pins", "run": "sudo bash .docker/pinned-tools.sh kustomize kubeconform"})
        steps.append({"uses": _action(table, "cache"), "with": {"path": "${{ github.workspace }}/.kubeconform-cache", "key": "kubeconform-schemas-${{ hashFiles('ci/scripts/check_kube_manifests.sh') }}"}})
    if "s3" in lane.needs:
        steps += [
            {"uses": _action(table, "cache"), "with": {"path": "/opt/s3-test-store", "key": "s3-test-store-${{ hashFiles('ci/scripts/s3_test_store.sh') }}"}},
            {"name": "Start the S3-class store", "run": 'export JAMMI_S3_STORE_DIR=/opt/s3-test-store\nci/scripts/s3_test_store.sh start --addr 127.0.0.1:9000 --data /tmp/s3-test-store\nci/scripts/s3_test_store.sh env --addr 127.0.0.1:9000 >> "$GITHUB_ENV"\n'},
            {"name": "Every distributed backend is provisioned (no hollow green)", "run": "bash ci/scripts/require_distributed_backends.sh"},
        ]
    if "audit-key" in lane.needs:
        steps.append({"name": "An ephemeral audit master key for this throwaway stack", "run": 'key="$(openssl rand -hex 32)"\necho "::add-mask::$key"\necho "JAMMI_AUDIT_MASTER_KEY=$key" >> "$GITHUB_ENV"\n'})
    uploaded: set[str] = set()
    for step in lane.steps:
        steps.append(_step(table, lane, step, refs))
        if step.kind == "upload":
            uploaded.add(step.raw["upload"])
    for name in lane.produces:
        if name not in uploaded:
            steps.append(_upload(table, name))
    return steps


def _bare(step: dict, bare_if: str | None) -> dict:
    return {"if": bare_if, **step} if bare_if else step


def _step(table: Table, lane: Lane, step: Step, refs: dict[str, str]) -> dict:
    raw = step.raw
    out: dict = {}
    if "when" in raw:
        out["if"] = Trigger.parse(raw["when"], f"lane.{lane.id}.steps").predicate
    if "if" in raw:
        out["if"] = raw["if"]
    if "name" in raw:
        out["name"] = raw["name"]
    if "id" in raw:
        out["id"] = raw["id"]
    if step.kind == "upload":
        up = _upload(table, raw["upload"])
        return {**out, **up}
    if step.kind == "download":
        run_id = f"${{{{ needs.{_resolver_id(raw['from'])}.outputs.run }}}}" if "from" in raw else f"${{{{ env.{ARTIFACT_RUN_ENV} }}}}"
        return {**out, "uses": _action(table, "download-artifact"), "with": {"name": _template(raw["download"]), "path": _subst(raw["path"], refs), "run-id": run_id, "github-token": "${{ github.token }}"}}
    if step.kind == "uses":
        uses = raw["uses"]
        out["uses"] = _action(table, uses[1:]) if uses.startswith("@") else uses
        if "with" in raw:
            out["with"] = {k: _subst(v, refs) if isinstance(v, str) else v for k, v in raw["with"].items()}
    else:
        out["run"] = _subst(raw["run"], refs)
        if "shell" in raw:
            out["shell"] = raw["shell"]
        if "dir" in raw:
            out["working-directory"] = raw["dir"]
    if "env" in raw:
        out["env"] = {k: _subst(v, refs) for k, v in raw["env"].items()}
    return out


def _upload(table: Table, name: str) -> dict:
    art = table.artifacts[name]
    with_: dict = {"name": _template(name), "path": art.path}
    if art.retention is not None:
        with_["retention-days"] = art.retention
    if art.if_no_files_found != "error":
        with_["if-no-files-found"] = art.if_no_files_found
    if art.compression is not None:
        with_["compression-level"] = art.compression
    return {"uses": _action(table, "upload-artifact"), "with": with_}


# ----------------------------------------------------------------------------- page
def render_page(table: Table) -> str:
    lines = [
        f"<!-- {GENERATED} -->",
        "# The lanes CI runs",
        "",
        "Every workflow under `.github/workflows/` is rendered from `ci/lanes.toml` by",
        "`ci/scripts/lanes.py`. A lane is a command with four typed properties: the host",
        "it runs on, what it needs of that host, when it runs, and what it produces or",
        "consumes. Everything a job spells -- its runner, container, services, edges,",
        "condition, permissions, checkout, toolchain, artifact transfer, release gate",
        "and summary -- is derived from those. The guard `lanes rendered` holds the",
        "committed files equal to the table.",
        "",
        "Locally, `python3 ci/scripts/lanes.py run <lane>` runs a lane's commands in",
        "order inside the CI image (`ci/dev.sh python3 ci/scripts/lanes.py run <lane>`;",
        "`--with pg,s3` provides the backends a lane needs).",
        "",
    ]
    for wf in table.workflows.values():
        lines += [f"## `{wf.file}` -- {wf.name}", "", *_wrap(wf.doc), "", f"Fires on: {', '.join(t.text for t in wf.on)}" + (f" (`{wf.cron}`)" if wf.cron else "") + ".", ""]
        lines += ["| lane | runs on | needs | when | produces | consumes | why |", "|---|---|---|---|---|---|---|"]
        for lane in table.in_workflow(wf.id):
            when = ", ".join(t.text for t in _when(lane, wf))
            hosts = sorted({l.get("host", lane.host) for l in lane.legs} | {lane.host})
            lines.append(
                f"| `{lane.id}` | {', '.join(hosts)}{f' x{len(lane.legs)}' if lane.legs else ''} | {', '.join(lane.needs) or '-'} | {when} | "
                f"{', '.join(f'`{a}`' for a in lane.produces) or '-'} | {', '.join(f'`{a}`' for a in lane.consumes) or '-'} | {lane.why} |"
            )
        lines.append("")
    return "\n".join(lines)


def _wrap(doc: str) -> list[str]:
    return doc.splitlines()


# ----------------------------------------------------------------------------- emit
_PLAIN = re.compile(r"^(?![-?:,\[\]{}#&*!|>'\"%@`])(?!.*: )(?!.* #)(?!.*#$)[^\n]*[^\s]$")
_RESERVED = {"true", "false", "null", "yes", "no", "on", "off", "~", ""}
_NUMBER = re.compile(r"^[-+]?(\d[\d_]*(\.\d*)?|\.\d+)([eE][-+]?\d+)?$|^0x[0-9a-f]+$|^0o[0-7]+$")


def _scalar(v) -> str:
    if isinstance(v, Pinned):
        return f"{_scalar(str(v))} # {v.comment}"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if not isinstance(v, str):
        raise TypeError(f"cannot emit {v!r}")
    if "\n" in v:
        raise ValueError("block scalars are emitted by the caller")
    if v.lower() in _RESERVED or _NUMBER.match(v) or not _PLAIN.match(v) or v != v.strip():
        return "'" + v.replace("'", "''") + "'"
    return v


def emit(doc: dict) -> str:
    out: list[str] = []
    header = doc.pop("_doc", "")
    for line in header.splitlines():
        out.append(f"# {line}".rstrip())
    out.append("")
    _emit_map(doc, 0, out)
    return "\n".join(out).rstrip("\n") + "\n"


def _emit_map(m: dict, indent: int, out: list[str]) -> None:
    pad = " " * indent
    for k, v in m.items():
        if isinstance(k, Commented):
            if out and out[-1] != "":
                out.append("")
            out.append(f"{pad}# {k.comment}")
        key = _scalar(str(k))
        if isinstance(v, dict):
            if not v:
                out.append(f"{pad}{key}: {{}}")
            else:
                out.append(f"{pad}{key}:")
                _emit_map(v, indent + 2, out)
        elif isinstance(v, list):
            if not v:
                out.append(f"{pad}{key}: []")
            else:
                out.append(f"{pad}{key}:")
                _emit_list(v, indent + 2, out)
        elif isinstance(v, str) and "\n" in v:
            out.append(f"{pad}{key}: |")
            for line in v.rstrip("\n").splitlines():
                out.append(f"{pad}  {line}" if line else "")
        else:
            out.append(f"{pad}{key}: {_scalar(v)}")


def _emit_list(items: list, indent: int, out: list[str]) -> None:
    pad = " " * indent
    for item in items:
        if isinstance(item, dict):
            first = True
            sub: list[str] = []
            _emit_map(item, indent + 2, sub)
            for line in sub:
                if first:
                    out.append(f"{pad}- {line[indent + 2:]}")
                    first = False
                else:
                    out.append(line)
        elif isinstance(item, list):
            raise TypeError("nested lists are not emitted")
        elif isinstance(item, str) and "\n" in item:
            raise TypeError("block scalars in lists are not emitted")
        else:
            out.append(f"{pad}- {_scalar(item)}")


# ----------------------------------------------------------------------------- commands
def load(root: Path = REPO_ROOT) -> Table:
    return parse((root / TABLE).read_text(), root)


def refs(root: Path = REPO_ROOT) -> dict[str, str]:
    return ci_image.refs(root)


def check(root: Path = REPO_ROOT) -> list[str]:
    """Findings: a rendered file that differs from the table, or a workflow file
    the table does not render."""
    table = load(root)
    rendered = render_all(table, refs(root))
    findings = []
    for rel, text in rendered.items():
        path = root / rel
        if not path.exists():
            findings.append(f"{rel}: missing -- run `python3 ci/scripts/lanes.py render`")
        elif path.read_text() != text:
            findings.append(f"{rel}: differs from what ci/lanes.toml renders -- run `python3 ci/scripts/lanes.py render`")
    for path in sorted((root / WORKFLOWS_DIR).glob("*.y*ml")):
        rel = str(path.relative_to(root))
        if rel not in rendered:
            findings.append(f"{rel}: not rendered from ci/lanes.toml -- a workflow is a lane in the table")
    return findings


def render(root: Path = REPO_ROOT) -> list[str]:
    table = load(root)
    rendered = render_all(table, refs(root))
    for rel, text in rendered.items():
        (root / rel).parent.mkdir(parents=True, exist_ok=True)
        (root / rel).write_text(text)
    for path in sorted((root / WORKFLOWS_DIR).glob("*.y*ml")):
        if str(path.relative_to(root)) not in rendered:
            path.unlink()
    return sorted(rendered)


def run_lane(table: Table, lane_id: str, root: Path = REPO_ROOT) -> int:
    """Run a lane's `run` steps here, in order, with its environment; a lane
    whose steps use an action, or that needs a host this one is not, says so."""
    lane = table.lanes.get(lane_id)
    if lane is None:
        print(f"lanes: no lane `{lane_id}` ({', '.join(sorted(table.lanes))})", file=sys.stderr)
        return 2
    if lane.legs:
        print(f"lanes: `{lane_id}` has legs; run each leg's command by hand with its matrix values", file=sys.stderr)
    env = {**os.environ, **{k: v for k, v in lane.env.items() if "${{" not in v}}
    if "postgres" in lane.needs and "JAMMI_TEST_PG_URL" not in env:
        print("lanes: this lane needs Postgres: run it through `ci/dev.sh --with pg`", file=sys.stderr)
        return 2
    for step in lane.steps:
        if step.kind != "run":
            print(f"lanes: skipping a `{step.kind}` step ({step.raw.get(step.kind)}); only `run` steps run here", file=sys.stderr)
            continue
        cmd = step.raw["run"]
        if "${{" in cmd:
            print(f"lanes: a step carries a workflow expression and cannot run here:\n{cmd}", file=sys.stderr)
            return 2
        cwd = root / (step.raw.get("dir") or lane.dir or ".")
        print(f"==> {step.raw.get('name', cmd.splitlines()[0])}")
        proc = subprocess.run(["bash", "-e", "-o", "pipefail", "-c", cmd], cwd=cwd, env={**env, **step.raw.get("env", {})})
        if proc.returncode != 0:
            return proc.returncode
    return 0


def self_test() -> int:
    failures: list[str] = []

    def expect(label: str, text: str, want: str | None) -> None:
        try:
            parse(text)
            got = None
        except TableError as e:
            got = str(e)
        if (want is None) != (got is None) or (want and want not in (got or "")):
            failures.append(f"{label}: expected {want!r}, got {got!r}")

    base = """
    [workflow.ci]
    name = "CI"
    doc = "d"
    on = ["pr", "main"]
    [workflow.paid]
    name = "P"
    doc = "d"
    on = ["label:run-x", "dispatch"]
    [workflow.rel]
    name = "R"
    doc = "d"
    on = ["tag:v", "dispatch"]
    [action]
    checkout = "actions/checkout@0000000000000000000000000000000000000000 # v4"
    upload-artifact = "actions/upload-artifact@0000000000000000000000000000000000000000 # v4"
    download-artifact = "actions/download-artifact@0000000000000000000000000000000000000000 # v4"
    [artifact.a]
    path = "out"
    [lane.build]
    why = "Builds a."
    produces = ["a"]
    steps = [{run = "make"}]
    [lane.paid-ok]
    why = "Rents."
    workflow = "paid"
    needs = ["runpod"]
    steps = [{run = "x"}]
    [lane.rel-ok]
    why = "Promotes."
    workflow = "rel"
    when = ["tag:v"]
    publishes = "release"
    steps = [{run = "gh release upload"}]
    """
    expect("the base table parses", base, None)
    expect("a paid lane on a pull request", base + '\n[lane.p]\nwhy = "W."\nneeds = ["runpod"]\nsteps = [{run = "x"}]\n', "rents hardware")
    expect("a paid lane by label", base + '\n[lane.p]\nwhy = "W."\nworkflow = "paid"\nneeds = ["runpod"]\nsteps = [{run = "x"}]\n', None)
    expect("a publisher off a tag", base + '\n[lane.pub]\nwhy = "W."\nworkflow = "rel"\nsteps = [{run = "npm publish"}]\n', "declares no `publishes`")
    expect("a release lane on a dispatch", base + '\n[lane.pub]\nwhy = "W."\nworkflow = "rel"\npublishes = "release"\nsteps = [{run = "npm publish"}]\n', "never else")
    expect("a release lane that compiles", base + '\n[lane.pub]\nwhy = "W."\nworkflow = "rel"\nwhen = ["tag:v"]\npublishes = "release"\nsteps = [{run = "cargo build && npm publish"}]\n', "compiles nothing")
    expect("a release lane", base + '\n[lane.pub]\nwhy = "W."\nworkflow = "rel"\nwhen = ["tag:v"]\npublishes = "release"\nsteps = [{run = "npm publish"}]\n', None)
    expect("a secret outside a need", base + '\n[lane.s]\nwhy = "W."\nsteps = [{run = "x", env = {T = "${{ secrets.T }}"}}]\n', "secret outside a need")
    expect("an artifact nothing builds", base + '\n[lane.c]\nwhy = "W."\nconsumes = ["b"]\nsteps = [{run = "x"}]\n', "produced by no lane")
    expect("a wheel never held to the limit", base + '\n[lane.w]\nwhy = "W."\nsteps = [{run = "maturin build"}]\n', "per-file limit")
    expect("a release build spelling features", base + '\n[lane.w]\nwhy = "W."\nrust = "release"\nsteps = [{run = "cargo build --features cuda,mysql"}]\n', "spells features")
    expect("a release build reading the manifest", base + '\n[lane.w]\nwhy = "W."\nrust = "release"\nsteps = [{run = "cargo build --features \\"$FEATURES\\""}]\n', None)
    expect("an edge a lane never declared", base + '\n[lane.e]\nwhy = "W."\nsteps = [{run = "echo ${{ needs.build.outputs.x }}"}]\n', "not an edge")
    expect("a `when` the workflow lacks", base + '\n[lane.e]\nwhy = "W."\nwhen = ["schedule"]\nsteps = [{run = "x"}]\n', "names a trigger")
    expect("an unpinned action", base.replace("checkout@0000000000000000000000000000000000000000 # v4", "checkout@v4"), "40-hex sha")

    table = parse(base + '\n[lane.c]\nwhy = "W."\nhost = "ubuntu"\nconsumes = ["a"]\nsteps = [{download = "a", path = "in"}, {run = "ls"}]\n[lane.pub]\nwhy = "W."\nworkflow = "rel"\nhost = "ubuntu"\nwhen = ["tag:v"]\npublishes = "release"\nconsumes = ["a"]\nsteps = [{run = "npm publish"}]\n')
    fake_refs = {"cpu": "img:cpu", "cuda": "img:cuda", "postgres": "pg", "colab": "py"}
    ci = render_workflow(table, table.workflows["ci"], fake_refs)
    if ci["jobs"]["c"]["needs"] != ["build"] or ci["jobs"]["c"]["env"][ARTIFACT_RUN_ENV] != "${{ github.run_id }}":
        failures.append(f"an in-workflow consumer needs its producer and its own run: {ci['jobs']['c']}")
    if SUMMARY_LANE not in ci["jobs"] or ci["jobs"][SUMMARY_LANE]["needs"] != ["build", "c"]:
        failures.append("the merge-path workflow sums every job")
    rel = render_workflow(table, table.workflows["rel"], fake_refs)
    if set(rel["jobs"]["pub"]["needs"]) != {"artifacts-ci", PROOF_LANE} or rel["jobs"]["pub"]["if"] != "startsWith(github.ref, 'refs/tags/v')":
        failures.append(f"a release lane waits on the proof and the proving run: {rel['jobs']['pub']}")
    if "always()" in str(rel["jobs"]["pub"]):
        failures.append("a release lane never carries always()")
    text = emit(dict(rel))
    if "${{ secrets." in text:
        failures.append("a rendered release workflow reads no secret")
    for v, want in (("3.12", "'3.12'"), ("*/6", "'*/6'"), ("a: b", "'a: b'"), ("${{ x }}", "${{ x }}"), ("on", "'on'"), ("plain text", "plain text"), ("--flag", "'--flag'")):
        if _scalar(v) != want:
            failures.append(f"emit {v!r} as {want!r}, got {_scalar(v)!r}")
    if failures:
        print("lanes self-test: FAIL", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        return 1
    print("lanes self-test: OK")
    return 0


def main(argv: list[str]) -> int:
    if argv == ["--self-test"]:
        return self_test()
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="command", required=True)
    sub.add_parser("render")
    sub.add_parser("check")
    ls = sub.add_parser("list")
    ls.add_argument("workflow", nargs="?")
    rn = sub.add_parser("run")
    rn.add_argument("lane")
    args = ap.parse_args(argv)
    try:
        if args.command == "render":
            for rel in render():
                print(rel)
            return 0
        if args.command == "check":
            findings = check()
            for f in findings:
                print(f"::error::lanes: {f}", file=sys.stderr)
            if not findings:
                print("lanes: every workflow is what ci/lanes.toml renders")
            return 1 if findings else 0
        table = load()
        if args.command == "list":
            for wf in table.workflows.values():
                if args.workflow and wf.id != args.workflow:
                    continue
                print(f"{wf.file}:")
                for lane in table.in_workflow(wf.id):
                    print(f"  {lane.id:28} {lane.host:10} {', '.join(lane.needs)}")
            return 0
        return run_lane(table, args.lane)
    except TableError as e:
        print(f"::error::lanes: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
