//! gRPC services exposed by `jammi-server`.
//!
//! The wire surface is hybrid (per ADR-01): Flight SQL retains query/result;
//! typed gRPC services handle session management and (later) trigger
//! streams. Both Flight SQL and gRPC services share a
//! [`session::SessionStore`] via the [`session::TenantInterceptor`] so a
//! tenant bound through `SessionService.SetTenant` is observable on any
//! downstream request — including SQL queries issued against Flight SQL.
//!
//! Proto generated by `build.rs` lives under [`proto`].

pub mod embedding;
pub mod eval;
pub mod inference;
pub mod session;
pub mod trigger;
pub mod wire;

/// Proto-generated types for the `jammi.v1` API surface.
pub mod proto {
    pub mod session {
        tonic::include_proto!("jammi.v1.session");
    }
    pub mod trigger {
        tonic::include_proto!("jammi.v1.trigger");
    }
    pub mod embedding {
        tonic::include_proto!("jammi.v1.embedding");
    }
    pub mod inference {
        tonic::include_proto!("jammi.v1.inference");
    }
    pub mod eval {
        tonic::include_proto!("jammi.v1.eval");
    }
}
