apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - statefulset-compute.yaml
  - service-compute-headless.yaml

configMapGenerator:
  - name: jammi-compute-config
    files:
      - jammi-compute.toml

generatorOptions:
  disableNameSuffixHash: true
