apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - deployment-compute.yaml

configMapGenerator:
  - name: jammi-compute-config
    files:
      - jammi-compute.toml

generatorOptions:
  disableNameSuffixHash: true
