#!/usr/bin/env python3
"""Emit the media-tower LoRA cache — run ONCE on a real GPU `jammi-server`,
against REAL OpenCLIP ViT-B-32 (text + vision) and REAL CLAP HTSAT checkpoints,
through the SHIPPED PYTHON SURFACE (``db.fine_tune`` / ``db.infer`` /
``db.describe_model`` — never ``jammi-bench finetune-run``, which is an internal
harness, not a consumer-facing entry point).

This is the CacheLane pattern every other vertical in this book already uses
(``build_finetune_cache.py`` for the text encoder, ``build_lifecycle_cache.py``
for the model catalog): the heavy work runs once against a real GPU server and
is committed under ``artifacts/media_tower/``; the chapter reads that cache and
asserts a measured verdict against ``golden_metrics.json``. It never recomputes
upstream.

Corpora are generated by the engine's own COMMITTED producers
(``ci/scripts/perf/gen_fixed_shape_image_corpus.py`` /
``gen_fixed_length_audio_corpus.py`` / ``gen_fixed_width_corpus.py``) — the same
generators the #421 profiling campaign uses for its fixed-shape/fixed-length
workloads — invoked as subprocesses and read back into Parquet sources this
script registers, rather than a fourth, ad hoc corpus builder. Small counts
throughout (24 rows per modality): this is a correctness/behavior cache, not a
throughput benchmark.

Four things this cache measures, per tower, through the public surface (the
recipes' own template — ``cookbook/recipes/image_search`` /
``cookbook/recipes/audio_search``, PR #466 — extended with a determinism
control this book adds):

1. **Change, not improvement.** The SAME probe input, encoded through the base
   checkpoint and through the LoRA-adapted checkpoint, must differ — the
   adapter actually moved the tower's representation. (Direction/quality is not
   claimed; only that training moved something.)
2. **The same-input control.** The SAME probe input encoded TWICE through the
   SAME (base) checkpoint, in two independent ``db.infer`` calls. Any nonzero
   diff observed in (1) could otherwise be inference noise rather than a real
   parameter change; this control is what rules that out. Measured, not
   assumed to be 0 — a real GPU kernel is only "deterministic across repeated
   calls" if nothing in the dispatch path is order-nondeterministic (e.g. an
   atomic-add reduction), so this script records the ACTUAL diff.
3. **The round trip.** After a job completes, this script closes the training
   connection and opens a BRAND NEW connection to the SAME server — proving
   the adapter is discoverable and servable from a session that never trained
   it (train -> save in the catalog -> serve from a new client), not merely
   held live in the training connection's own process state.
4. **Corrupt-media-row behavior.** A batch with one valid row, one NULL row,
   and one row of undecodable garbage bytes, run through ``db.infer`` — the
   real, MEASURED per-row `_status`/`_error` contract (`docs/guide/src/
   generate-image-embeddings.md`'s Error-handling table is the documented
   claim; this records what the engine actually does at this branch's tip,
   never assumes the doc is still accurate).

Usage::

    # 1. start the GPU server against the real checkpoints (clean artifact
    #    dir for a reproducible emit):
    #    JAMMI_ARTIFACT_DIR=/tmp/srv-media-art JAMMI_GPU__DEVICE=0 \\
    #    JAMMI_GPU__REQUIRE_GPU=true JAMMI_SERVER__FLIGHT_LISTEN=127.0.0.1:50051 \\
    #    jammi-server &
    # 2. emit against it:
    python scripts/build_media_tower_lora_cache.py --target grpc://127.0.0.1:50051 \\
        --vision-checkpoint /root/models/open-clip-vit-b-32 \\
        --audio-checkpoint /root/models/clap-htsat-fused
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

import jammi
import pyarrow as pa
import pyarrow.parquet as pq

import jammi_cookbook  # noqa: F401  — applies the determinism env on import
from jammi_cookbook import determinism

ENGINE_VERSION = "0.49.1"
ARTIFACTS = Path(__file__).resolve().parent.parent / "artifacts" / "media_tower"
PERF_SCRIPTS = Path(__file__).resolve().parents[3] / "ci" / "scripts" / "perf"

ROWS = 24  # small: a correctness/behavior cache, not a throughput benchmark
EPOCHS = 2
BATCH = 4
LORA_RANK = 4

# OpenCLIP's ResidualAttentionBlock LoRA sites — shared by the vision AND text
# towers (crates/jammi-encoders/src/open_clip_block.rs). The image_search
# recipe (PR #466) exercises the same two-site subset on the vision tower;
# this cache exercises it on the text tower too, since the block is identical.
CLIP_TARGET_MODULES = ["in_proj", "c_fc"]
# HTSAT-Swin's own LoRA sites (audio_search recipe, PR #466): the attention
# projections plus the audio-projection head's first linear.
CLAP_TARGET_MODULES = ["query", "value", "linear1"]


def _checksum(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def _run_generator(args: list[str]) -> None:
    print(f"  $ {' '.join(str(a) for a in args)}", flush=True)
    subprocess.run(args, check=True)


# --------------------------------------------------------------------------- #
# corpora — generated by the engine's own committed producers
# --------------------------------------------------------------------------- #


def build_image_triplets(work: Path) -> pa.Table:
    """Real-shape (anchor, positive, negative) PNG triplets via the committed
    fixed-shape image-corpus producer (224x224 — OpenCLIP ViT-B-32's own input
    size), read back with inline bytes."""
    out_dir = work / "image_corpus"
    _run_generator([
        sys.executable, str(PERF_SCRIPTS / "gen_fixed_shape_image_corpus.py"),
        "--rows", str(ROWS), "--size", "224", "--seed", str(determinism.SEED),
        "--families", "6", "--instances-per-family", "5", "--out-dir", str(out_dir),
    ])
    rows = [json.loads(line) for line in
            (out_dir / "triplets.jsonl").read_text().splitlines() if line]
    anchors = [(out_dir / r["anchor_path"]).read_bytes() for r in rows]
    positives = [(out_dir / r["positive_path"]).read_bytes() for r in rows]
    negatives = [(out_dir / r["negative_path"]).read_bytes() for r in rows]
    return pa.table({
        "anchor": pa.array(anchors, type=pa.binary()),
        "positive": pa.array(positives, type=pa.binary()),
        "negative": pa.array(negatives, type=pa.binary()),
    }), anchors[0]


def build_audio_triplets(work: Path) -> tuple[pa.Table, bytes]:
    """Real-shape (anchor, positive, negative) WAV triplets via the committed
    fixed-length audio-corpus producer (2s @ 48kHz — CLAP's own fusion window
    rate), read back with inline bytes."""
    out_dir = work / "audio_corpus"
    _run_generator([
        sys.executable, str(PERF_SCRIPTS / "gen_fixed_length_audio_corpus.py"),
        "--rows", str(ROWS), "--seconds", "2.0", "--sample-rate", "48000",
        "--seed", str(determinism.SEED), "--families", "6",
        "--instances-per-family", "5", "--out-dir", str(out_dir),
    ])
    rows = [json.loads(line) for line in
            (out_dir / "triplets.jsonl").read_text().splitlines() if line]
    anchors = [(out_dir / r["anchor_path"]).read_bytes() for r in rows]
    positives = [(out_dir / r["positive_path"]).read_bytes() for r in rows]
    negatives = [(out_dir / r["negative_path"]).read_bytes() for r in rows]
    return pa.table({
        "anchor": pa.array(anchors, type=pa.binary()),
        "positive": pa.array(positives, type=pa.binary()),
        "negative": pa.array(negatives, type=pa.binary()),
    }), anchors[0]


def build_text_triplets(work: Path) -> tuple[pa.Table, str]:
    """Real-width (anchor, positive, negative) text triplets via the committed
    fixed-width corpus producer, at CLIP's own 77-token context width."""
    out_path = work / "text_triplets.jsonl"
    _run_generator([
        sys.executable, str(PERF_SCRIPTS / "gen_fixed_width_corpus.py"),
        "--rows", str(ROWS), "--min-wordpieces", "40",
        "--seed", str(determinism.SEED), "--out", str(out_path),
    ])
    rows = [json.loads(line) for line in out_path.read_text().splitlines() if line]
    anchors = [r["anchor_text"] for r in rows]
    positives = [r["positive_text"] for r in rows]
    negatives = [r["negative_text"] for r in rows]
    return pa.table({
        "anchor": pa.array(anchors, type=pa.utf8()),
        "positive": pa.array(positives, type=pa.utf8()),
        "negative": pa.array(negatives, type=pa.utf8()),
    }), anchors[0]


# --------------------------------------------------------------------------- #
# per-tower measurement
# --------------------------------------------------------------------------- #


def _probe_source(db, name: str, column: str, dtype, value) -> str:
    """Register a single-row probe source under ``name`` (a fresh registration
    per call — the fine_tune/infer surface addresses sources by name, and this
    keeps every probe call's source unambiguous)."""
    tbl = pa.table({"id": pa.array(["probe"], type=pa.utf8()),
                    column: pa.array([value], type=dtype)})
    tmp = ARTIFACTS / f"_{name}.parquet"
    pq.write_table(tbl, tmp)
    db.add_source(name, url=str(tmp), format="parquet")
    return name


def _infer_vector(db, source: str, model: str, column: str, task: str) -> list[float]:
    out = db.infer(source=source, model=model, columns=[column], task=task, key="id")
    assert out.column("_status").to_pylist() == ["ok"], out.column("_error").to_pylist()
    return list(out.column("vector").to_pylist()[0])


def _max_abs_diff(a: list[float], b: list[float]) -> float:
    assert len(a) == len(b), (len(a), len(b))
    return max(abs(x - y) for x, y in zip(a, b, strict=True))


def measure_tower(
    db, *, target: str, label: str, task: str, column: str, dtype,
    base_model: str, triplets: pa.Table, probe_value, source_prefix: str,
    target_modules: list[str],
) -> dict:
    """Fine-tune one tower's LoRA adapter, then measure the four invariants
    (change / control / round-trip / corrupt-row) through the public surface."""
    print(f"\n=== [{label}] task={task} base={base_model} ===", flush=True)
    triplets_src = f"{source_prefix}_triplets"
    triplets_path = ARTIFACTS / f"_{triplets_src}.parquet"
    pq.write_table(triplets, triplets_path)
    db.add_source(triplets_src, url=str(triplets_path), format="parquet")

    job = db.fine_tune(
        source=triplets_src, base_model=base_model,
        columns=["anchor", "positive", "negative"], method="lora", task=task,
        target_modules=target_modules, lora_rank=LORA_RANK, learning_rate=5e-3,
        epochs=EPOCHS, batch_size=BATCH, warmup_steps=0, validation_fraction=0.0,
        early_stopping_metric="train_loss", seed=determinism.SEED,
    )
    job.wait()
    if job.status() != "completed":
        raise RuntimeError(f"{label} fine-tune did not complete: status={job.status()}")
    tuned_model = job.model_id
    if not tuned_model.startswith("jammi:fine-tuned:"):
        raise RuntimeError(f"unexpected fine-tuned model_id: {tuned_model}")
    print(f"  model_id: {tuned_model}", flush=True)

    probe = _probe_source(db, f"{source_prefix}_probe", column, dtype, probe_value)

    # (1) change, not improvement.
    base_vec = _infer_vector(db, probe, base_model, column, task)
    tuned_vec = _infer_vector(db, probe, tuned_model, column, task)
    change_diff = _max_abs_diff(base_vec, tuned_vec)
    print(f"  change (tuned vs base) max|Δ| = {change_diff:.6f}", flush=True)

    # (2) the same-input control — TWO independent forward passes through the
    # SAME (base) checkpoint over the SAME probe input.
    base_vec_repeat = _infer_vector(db, probe, base_model, column, task)
    control_diff = _max_abs_diff(base_vec, base_vec_repeat)
    print(f"  same-input control max|Δ| = {control_diff:.6f}", flush=True)

    # (3) the round trip: close THIS connection, open a NEW one to the SAME
    # server, and re-derive the tuned vector from a session that never trained
    # it — proving persistence through the catalog, not process-local state.
    db.close()
    db2 = jammi.connect(target)
    described = db2.describe_model(tuned_model)
    if described is None or described.get("task") != task:
        raise RuntimeError(f"{label}: round-trip describe_model mismatch: {described}")
    tuned_vec_roundtrip = _infer_vector(db2, probe, tuned_model, column, task)
    roundtrip_diff = _max_abs_diff(tuned_vec, tuned_vec_roundtrip)
    print(f"  round-trip (new connection) max|Δ| vs first tuned read = "
          f"{roundtrip_diff:.6f}", flush=True)

    # `db2` — the brand-new connection that just proved the round trip — is
    # handed back as the caller's next `db`, rather than closed and reopened
    # again: the round-trip claim is about the CONNECTION boundary the
    # training session crossed, not about how many connections this script
    # itself churns through.
    return {
        "task": task,
        "base_model": base_model,
        "model_id": tuned_model,
        "target_modules": target_modules,
        "epochs": EPOCHS,
        "lora_rank": LORA_RANK,
        "change_vs_base_max_abs_diff": round(change_diff, 6),
        "same_input_control_max_abs_diff": round(control_diff, 6),
        "round_trip_max_abs_diff": round(roundtrip_diff, 6),
    }, db2


def measure_corrupt_rows(db, *, label: str, task: str, column: str, dtype,
                          base_model: str, good_value, source_prefix: str) -> dict:
    """The real per-row behavior for a NULL row and a CORRUPT (undecodable)
    row, in the SAME batch as a valid row — measured, never assumed from the
    doc table. Both a null row and a genuinely undecodable row are per-row
    `_status="error"` outcomes here: the batch's one valid row still reads
    `_status="ok"`, neither failure collapses the whole `infer` call."""
    print(f"\n=== [{label}] corrupt-row behavior, task={task} ===", flush=True)
    corrupt_bytes = b"not a real " + column.encode() + b" file at all, just garbage bytes"
    src = f"{source_prefix}_mixed_rows"
    tbl = pa.table({
        "id": pa.array(["good", "null_row", "corrupt_row"], type=pa.utf8()),
        column: pa.array([good_value, None, corrupt_bytes], type=dtype),
    })
    path = ARTIFACTS / f"_{src}.parquet"
    pq.write_table(tbl, path)
    db.add_source(src, url=str(path), format="parquet")

    out = db.infer(source=src, model=base_model, columns=[column], task=task, key="id")
    statuses = out.column("_status").to_pylist()
    errors = out.column("_error").to_pylist()
    ids = out.column("_row_id").to_pylist()
    by_id = dict(zip(ids, zip(statuses, errors, strict=True), strict=True))
    null_result = {"status": by_id["null_row"][0], "error": by_id["null_row"][1]}
    corrupt_result = {"status": by_id["corrupt_row"][0], "error": by_id["corrupt_row"][1]}
    good_result = {"status": by_id["good"][0]}
    print(f"  good row:    {good_result}", flush=True)
    print(f"  null row:    {null_result}", flush=True)
    print(f"  corrupt row: {corrupt_result}", flush=True)

    return {
        "null_row": null_result,
        "corrupt_row": {
            "status": corrupt_result["status"],
            "message_contains_row_index": "row" in corrupt_result["error"].lower(),
            "message": corrupt_result["error"][:300],
        },
        "good_row_still_ok": good_result["status"] == "ok",
    }


def emit(db, target: str, vision_checkpoint: str, audio_checkpoint: str) -> None:
    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    info = db.get_server_info()
    print("server:", json.dumps(info), flush=True)
    if info.get("version") != ENGINE_VERSION:
        raise RuntimeError(
            f"server version {info.get('version')} != pinned {ENGINE_VERSION} — STOP")

    clip_base = f"local:{vision_checkpoint}"
    clap_base = f"local:{audio_checkpoint}"

    work = ARTIFACTS / "_work"
    work.mkdir(parents=True, exist_ok=True)
    image_triplets, image_probe = build_image_triplets(work)
    audio_triplets, audio_probe = build_audio_triplets(work)
    text_triplets, text_probe = build_text_triplets(work)

    towers: dict[str, dict] = {}

    vision_record, db = measure_tower(
        db, target=target, label="vision", task="image_embedding", column="image",
        dtype=pa.binary(), base_model=clip_base, triplets=image_triplets,
        probe_value=image_probe, source_prefix="vision", target_modules=CLIP_TARGET_MODULES,
    )
    towers["vision"] = vision_record

    text_record, db = measure_tower(
        db, target=target, label="text", task="text_embedding", column="text",
        dtype=pa.utf8(), base_model=clip_base, triplets=text_triplets,
        probe_value=text_probe, source_prefix="text", target_modules=CLIP_TARGET_MODULES,
    )
    towers["text"] = text_record

    audio_record, db = measure_tower(
        db, target=target, label="audio", task="audio_embedding", column="audio",
        dtype=pa.binary(), base_model=clap_base, triplets=audio_triplets,
        probe_value=audio_probe, source_prefix="audio", target_modules=CLAP_TARGET_MODULES,
    )
    towers["audio"] = audio_record

    corrupt_rows = {
        "image": measure_corrupt_rows(
            db, label="vision", task="image_embedding", column="image", dtype=pa.binary(),
            base_model=clip_base, good_value=image_probe, source_prefix="image"),
        "audio": measure_corrupt_rows(
            db, label="audio", task="audio_embedding", column="audio", dtype=pa.binary(),
            base_model=clap_base, good_value=audio_probe, source_prefix="audio"),
    }

    record = {
        "engine_version": ENGINE_VERSION,
        "vision_checkpoint": vision_checkpoint,
        "audio_checkpoint": audio_checkpoint,
        "rows_per_modality": ROWS,
        "towers": towers,
        "corrupt_rows": corrupt_rows,
    }
    (ARTIFACTS / "record.json").write_text(json.dumps(record, indent=2, sort_keys=True))

    metrics: dict[str, dict[str, float]] = {}
    for name, rec in towers.items():
        metrics[f"{name}.change_vs_base_max_abs_diff"] = {
            "value": rec["change_vs_base_max_abs_diff"], "tol": 0.5}
        metrics[f"{name}.same_input_control_max_abs_diff"] = {
            "value": rec["same_input_control_max_abs_diff"], "tol": 1e-6}
        metrics[f"{name}.round_trip_max_abs_diff"] = {
            "value": rec["round_trip_max_abs_diff"], "tol": 1e-6}
    (ARTIFACTS / "golden_metrics.json").write_text(
        json.dumps(metrics, indent=2, sort_keys=True))

    # drop the working corpora + per-probe parquet scratch files — sources
    # only, not committed cache (mirrors build_finetune_cache.py's own cleanup).
    for tmp in sorted(ARTIFACTS.glob("_*.parquet")):
        tmp.unlink(missing_ok=True)
    import shutil
    shutil.rmtree(work, ignore_errors=True)

    _write_checksums()
    print("\n=== media-tower LoRA cache (REAL checkpoints) ===", flush=True)
    for name, rec in towers.items():
        print(f"  {name:<6} change={rec['change_vs_base_max_abs_diff']:.6f}  "
              f"control={rec['same_input_control_max_abs_diff']:.6f}  "
              f"round_trip={rec['round_trip_max_abs_diff']:.6f}", flush=True)
    print("\nemitted cache:", flush=True)
    for f in sorted(ARTIFACTS.glob("*")):
        if f.is_file():
            print(f"  {f.name}  ({f.stat().st_size} bytes)", flush=True)


def _write_checksums() -> None:
    sums = {p.name: _checksum(p) for p in sorted(ARTIFACTS.glob("*"))
            if p.is_file() and p.name != "checksums.json"}
    (ARTIFACTS / "checksums.json").write_text(json.dumps(sums, indent=2, sort_keys=True))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", default="grpc://127.0.0.1:50051",
                    help="connect() target — grpc://host:port for the GPU server.")
    ap.add_argument("--vision-checkpoint", required=True,
                    help="local filesystem path to the real OpenCLIP ViT-B-32 checkpoint dir")
    ap.add_argument("--audio-checkpoint", required=True,
                    help="local filesystem path to the real CLAP HTSAT checkpoint dir")
    args = ap.parse_args()
    db = jammi.connect(args.target)
    emit(db, args.target, args.vision_checkpoint, args.audio_checkpoint)


if __name__ == "__main__":
    main()
