//! Transport-only GPU leg — device coverage of the CPU bitwise remote-vs-local
//! assertion (`assert_eq!(remote_vec, local_vec, ...)`) in
//! `grpc_remote_session.rs`'s `remote_round_trips_embeddings_and_search_like_local`.
//!
//! ## Why this is its own module, and why it is shaped differently from the
//! ## CPU assertion it covers
//!
//! On CPU, that assertion compares two INDEPENDENT `encode_query` computes (one
//! over the wire, one in-process) and is sound as a hard gate because CPU
//! floating-point compute is deterministic across repeats. On GPU that premise
//! does not hold: cross-repeat GPU float bit-equality is not a property this
//! codebase asserts (the `jammi_bench::encode_step` module doc). A GPU leg
//! that gated on two independent `encode_query` computes would gate on an
//! unproven premise, not on the wire.
//!
//! So the device leg is what is actually transport-only: ONE GPU compute
//! (`generate_embeddings`, run once over the remote transport), persisting an
//! embedding-table artifact, then TWO READ PATHS of that SAME persisted
//! artifact — no second GPU forward pass in either read:
//!   * remote gRPC serve: `DataClient::sql` — a Flight SQL `SELECT` issued
//!     over the real HTTP/2 wire, the lane `flight_annotate.rs` /
//!     `serve_e2e.rs` also cover.
//!   * local read-back: `Session::sql` on the SAME `Arc<InferenceSession>` —
//!     the identical DataFusion query executed in-process against the same
//!     Parquet artifact, no network involved.
//!
//! Both paths scan the identical persisted `FixedSizeList<Float32>` `vector`
//! column (`repeated float` on the wire is lossless), so a byte divergence
//! between them can only be the Arrow-Flight/tonic transport corrupting
//! floats — never a repeat-compute non-determinism artifact. Bitwise, zero
//! tolerance, per keyed (`_row_id`) row.
//!
//! `encode_query`'s two-compute form (remote vs local, each an independent GPU
//! forward pass) is exercised separately below, but RECORDED as an
//! observation of the GPU repeat-determinism premise, never gated.
//!
//! The checkpoint is `tiny_bert_head64` (`cookbook/fixtures/tiny_bert_head64`,
//! generated by `tests/fixtures/generate_tiny_bert_head64.py`): `hidden_size =
//! 64`, `num_attention_heads = 1`, so `head_dim == 64` — a real
//! embedding-checkpoint width, unlike the `head_dim == 16` fixtures the rest of
//! this suite's GPU serving tests use so flash/block attention arms never
//! dispatch (irrelevant here: this leg asserts no dispatch arm).
//!
//! Absent by design: any dispatch-counter delta assertion (fused arms are
//! training-only; counters never cross the wire), any new wire field, any
//! forced-arm A/B. Tenant scope is untouched — both sources here are
//! registered unscoped (tenant `None`), the same harness shape
//! `grpc_remote_session.rs` and `flight_annotate.rs` use.
//!
//! ## Gating
//!
//! Compiled only under the `live-gpu-tests` cargo feature (see its `mod` line
//! in `main.rs`) and needs the `cuda` feature and CUDA device 0.
//! [`start_gpu_engine_server`] pins `require_gpu = true`, so every RPC that
//! follows runs the real GPU-served path; on a host without that device,
//! `InferenceSession::open` fails and the test panics naming CUDA device 0 and
//! the underlying error.
//!
//! ```text
//! cargo test -p jammi-server --features cuda,live-gpu-tests --test it \
//!   grpc_remote_session_gpu -- --nocapture --test-threads=1
//! ```

use std::net::SocketAddr;
use std::sync::Arc;

use arrow::array::{Array, StringArray};
use arrow::compute::cast;
use arrow::record_batch::RecordBatch;
use arrow_schema::DataType;
use jammi_ai::session::InferenceSession;
use jammi_ai::{Modality, QueryInput, Session};
use jammi_client::DataClient;
use jammi_db::source::{FileFormat, SourceConnection, SourceType};
use jammi_db::store::vectors::extend_with_fixed_size_list_f32;
use jammi_server::grpc::session::SessionStore;
use jammi_test_utils::{cookbook_fixture, fixture, test_config};
use tempfile::TempDir;
use tokio::sync::oneshot;
use tonic::transport::Endpoint;

use crate::common::grpc::ephemeral_addr;

fn head64_model_id() -> String {
    format!("local:{}", cookbook_fixture("tiny_bert_head64").display())
}

fn patents_connection() -> SourceConnection {
    SourceConnection {
        url: Some(format!("file://{}", fixture("patents.parquet").display())),
        format: Some(FileFormat::Parquet),
        ..Default::default()
    }
}

/// A running GPU-pinned in-process server plus the shared engine `Arc` a local
/// [`Session`] wraps, and a shutdown handle. Mirrors
/// `grpc_remote_session.rs`'s `EngineServer` shape, but pinned to
/// `gpu.device = 0` / `require_gpu = true` like `grpc_embedding_gpu.rs`'s
/// `start_gpu_embedding_server`.
struct GpuEngineServer {
    addr: SocketAddr,
    shutdown: oneshot::Sender<()>,
    _dir: TempDir,
    handle: tokio::task::JoinHandle<()>,
    engine: Arc<InferenceSession>,
}

/// Spin up an in-process gRPC + Flight SQL server whose `InferenceSession` is
/// pinned to the first CUDA device (`require_gpu = true`), so every RPC against
/// it (including the Flight SQL reads below) runs the real CUDA-served path.
async fn start_gpu_engine_server() -> GpuEngineServer {
    let dir = tempfile::tempdir().expect("tempdir");
    let mut cfg = test_config(dir.path());
    cfg.gpu.device = Some(0);
    cfg.gpu.require_gpu = true;

    // `open` (not `new`) registers the compound-query SQL functions on the
    // session context — matching the production `OssServer` shape and what
    // the Flight SQL read-back below needs available.
    let session = InferenceSession::open(cfg)
        .await
        .expect("a session pinned to CUDA device 0 (require_gpu = true)");

    let store = SessionStore::new();
    let (shutdown_tx, shutdown_rx) = oneshot::channel::<()>();
    let engine = Arc::clone(&session);
    let chain = jammi_server::runtime::GrpcChain {
        addr: ephemeral_addr(),
        flight_ctx: session.context().clone(),
        flight_binding: session.tenant_binding_arc(),
        store: store.clone(),
        trigger: None,
        engine: Some(session),
        tiers: jammi_server::tiers::TierSet::all(),
        metrics: Arc::new(jammi_server::routes::health::MetricsRegistry::new().unwrap()),
        tenant_resolver: jammi_server::grpc::session::SessionIdTenantResolver::arc(store),
        admin_authorizer: None,
        limits: jammi_db::config::LimitsConfig::default(),
    };
    let (addr, handle) = crate::common::grpc::spawn_bound_chain(chain, shutdown_rx).await;

    GpuEngineServer {
        addr,
        shutdown: shutdown_tx,
        _dir: dir,
        handle,
        engine,
    }
}

/// Connect a `DataClient` to the in-process GPU server.
async fn remote(server: &GpuEngineServer) -> DataClient {
    let endpoint = Endpoint::from_shared(format!("http://{}", server.addr)).expect("endpoint");
    DataClient::connect(endpoint)
        .await
        .expect("data client connect")
}

/// Wrap the server's engine `Arc` in a local session — the SAME engine the
/// remote calls (and Flight SQL reads) reach, so any divergence is the
/// transport's fault, not a second compute or a different artifact.
fn local(server: &GpuEngineServer) -> Session {
    Session::new(Arc::clone(&server.engine))
}

/// Materialise the `(_row_id, vector)` rows of a `SELECT _row_id, vector FROM
/// "jammi.<table>" ORDER BY _row_id` result into one flat, row-ordered vector,
/// keyed by `_row_id`. Shared by both read paths so the same typed vector
/// downcast (`extend_with_fixed_size_list_f32`, the engine's one sanctioned
/// `FixedSizeList<Float32>` reader) backs the comparison on both sides.
///
/// The `_row_id` key column is read Utf8/Utf8View-agnostically: on an A100 the
/// remote Flight SQL read materialises `_row_id` as `Utf8View` while the local `Session::sql`
/// read-back of the same persisted artifact yields plain `Utf8` — DataFusion's
/// `schema_force_view_types` parquet-reader default applies independently on
/// each side of the transport. That is a transport/read-path representation
/// difference, not a logical divergence (both encode the identical row-key
/// string), so it is normalized here rather than gated: the column is cast to
/// `Utf8` before the `StringArray` downcast, the same cast-then-downcast
/// convention `jammi_db::index::exact::exact_vector_search` uses to
/// make its `_row_id` read agnostic to `Utf8`/`Utf8View`/`LargeUtf8`. Only the
/// key's logical string value is compared between read paths; the
/// `FixedSizeList<Float32>` vector column keeps its unmodified bitwise,
/// zero-tolerance assertion.
fn keyed_vectors(table_name: &str, batches: &[RecordBatch]) -> Vec<(String, Vec<f32>)> {
    let mut out = Vec::new();
    for batch in batches {
        let row_id_col = batch
            .column_by_name("_row_id")
            .unwrap_or_else(|| panic!("batch for '{table_name}' carries a _row_id column"));
        let row_ids = cast(row_id_col, &DataType::Utf8).unwrap_or_else(|err| {
            panic!("'{table_name}'._row_id could not be cast to Utf8: {err}")
        });
        let row_ids = row_ids
            .as_any()
            .downcast_ref::<StringArray>()
            .unwrap_or_else(|| panic!("'{table_name}'._row_id is not a Utf8-castable string type"));

        let mut vectors = Vec::with_capacity(row_ids.len());
        extend_with_fixed_size_list_f32(batch, table_name, "vector", &mut vectors)
            .expect("batch carries a FixedSizeList<Float32> vector column");
        assert_eq!(
            row_ids.len(),
            vectors.len(),
            "'{table_name}': one _row_id per vector row"
        );

        for (row, vector) in vectors.into_iter().enumerate() {
            out.push((row_ids.value(row).to_string(), vector));
        }
    }
    out
}

/// The device leg. `generate_embeddings` runs ONCE on the GPU over the
/// remote transport, persisting an embedding-table artifact on the
/// `tiny_bert_head64` (`head_dim == 64`) checkpoint. The SAME artifact is then
/// read two ways — remote gRPC/Flight-SQL serve vs local in-process
/// read-back — and compared bitwise, per keyed row. No second GPU compute
/// happens in either read path, so a mismatch can only be a transport defect,
/// device coverage of the CPU assertion in
/// `grpc_remote_session.rs`'s `remote_round_trips_embeddings_and_search_like_local`.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn remote_flight_read_matches_local_readback_bitwise_on_gpu() {
    let server = start_gpu_engine_server().await;
    let remote = remote(&server).await;
    let local = local(&server);
    let model_id = head64_model_id();

    local
        .add_source("patents", SourceType::File, patents_connection())
        .await
        .expect("add_source");

    // ONE compute: the GPU embeds the corpus exactly once, over the remote
    // transport, on the head_dim-64 checkpoint.
    let (table, _outcome) = remote
        .generate_embeddings(jammi_ai::local_session::EmbeddingRequest {
            source_id: "patents".to_string(),
            model_id: model_id.to_string(),
            columns: vec!["abstract".to_string()],
            key_column: "id".to_string(),
            modality: Modality::Text,
            dimensions: None,
            cache: jammi_db::store::CachePolicy::Bypass,
        })
        .await
        .expect("remote generate_embeddings on GPU");
    assert!(
        table.row_count > 0,
        "patents corpus embeds rows on the head_dim-64 GPU checkpoint"
    );

    let read_sql = format!(
        "SELECT _row_id, vector FROM \"jammi.{}\" ORDER BY _row_id",
        table.table_name
    );

    // Read path A: remote gRPC serve — Flight SQL over the real HTTP/2 wire.
    let remote_batches = remote.sql(&read_sql).await.expect("remote flight sql read");
    let remote_rows = keyed_vectors(&table.table_name, &remote_batches);

    // Read path B: LOCAL READ-BACK OF THE SAME ARTIFACT — the identical query
    // executed in-process against the same `Arc<InferenceSession>`, no network.
    let local_batches = local.sql(&read_sql).await.expect("local sql read");
    let local_rows = keyed_vectors(&table.table_name, &local_batches);

    assert!(
        !remote_rows.is_empty(),
        "the persisted GPU embedding table has at least one row to compare"
    );
    assert_eq!(
        remote_rows.len(),
        local_rows.len(),
        "remote (wire) and local (in-process) reads of the same persisted \
         artifact see the same row count"
    );
    for ((remote_key, remote_vec), (local_key, local_vec)) in
        remote_rows.iter().zip(local_rows.iter())
    {
        assert_eq!(
            remote_key, local_key,
            "both reads are ORDER BY _row_id over the same artifact, so keys align positionally"
        );
        assert_eq!(
            remote_vec, local_vec,
            "row '{remote_key}': the wire (Flight SQL) and the in-process read \
             of the SAME persisted GPU-computed artifact must be bitwise \
             identical (`repeated float`/Arrow FixedSizeList<Float32> is \
             lossless) — a divergence here is a transport defect, not a \
             compute one, since neither read path re-runs the GPU forward pass"
        );
    }

    let _ = server.shutdown.send(());
    let _ = server.handle.await;
}

/// `encode_query`'s TWO-COMPUTE form on GPU: remote and local each run an
/// independent GPU forward pass for the identical query against the identical
/// `tiny_bert_head64` checkpoint. Well-formedness (matching dimensionality,
/// finite values) is a hard gate — a NaN/Inf or dimension mismatch is a real
/// kernel bug regardless of repeat-determinism. Bitwise equality between the
/// two computes is NOT asserted: this only RECORDS the GPU repeat-determinism
/// premise (cross-repeat GPU float bit-equality is not a property this
/// codebase asserts; the `jammi_bench::encode_step` module doc) as an
/// observation.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn encode_query_two_compute_gpu_repeat_determinism_is_recorded_not_gated() {
    let server = start_gpu_engine_server().await;
    let remote = remote(&server).await;
    let local = local(&server);
    let model_id = head64_model_id();
    let query = "quantum computing applications";

    let remote_vec = remote
        .encode_query(
            &model_id,
            QueryInput::Text(query.to_string()),
            Modality::Text,
            None,
        )
        .await
        .expect("remote encode_query on GPU");
    let local_vec = local
        .encode_query(
            &model_id,
            QueryInput::Text(query.to_string()),
            Modality::Text,
            None,
        )
        .await
        .expect("local encode_query on GPU");

    // Well-formedness IS a hard gate — independent of repeat-determinism.
    assert_eq!(
        remote_vec.len(),
        local_vec.len(),
        "remote and local GPU encode_query computes share dimensionality \
         regardless of repeat-determinism"
    );
    assert!(
        remote_vec.iter().all(|v| v.is_finite()) && local_vec.iter().all(|v| v.is_finite()),
        "a NaN/Inf GPU query embedding is a real kernel bug, not a \
         determinism question: remote={remote_vec:?} local={local_vec:?}"
    );

    // Recorded observation only — see the module + function doc comments.
    // Never asserted: a `false` here is expected to be possible and is not a
    // test failure.
    let bitwise_equal = remote_vec == local_vec;
    tracing::info!(
        bitwise_equal,
        "encode_query two-compute GPU repeat-determinism observation: remote \
         vs local independent GPU forward passes on the same tiny_bert_head64 \
         checkpoint {} bitwise — recorded, not gated",
        if bitwise_equal { "matched" } else { "diverged" }
    );

    let _ = server.shutdown.send(());
    let _ = server.handle.await;
}
