[package]
name = "jammi-test-utils"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
jammi-datafusion.workspace = true
jammi-db = { workspace = true, features = ["test-hooks"] }
jammi-test-resources.workspace = true
libc.workspace = true
arrow.workspace = true
arrow-flight.workspace = true
parquet.workspace = true
futures.workspace = true
tonic.workspace = true
tempfile = "3"
uuid.workspace = true
