# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import audit_pb2 as jammi_dot_v1_dot_audit__pb2
GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jammi/v1/audit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuditServiceStub:
    """AuditService — the wire surface for the engine's per-query audit verbs.

    `AuditLog`, `AuditFetchByQueryId`, and `AuditFetchRecent` are imperative
    session methods — signing, tenant-injection, and signature-verified decode
    are non-SQL logic — so they live as typed gRPC RPCs alongside the other
    engine-backed services rather than on the Flight SQL surface (query/result
    only, per ADR-01 §3.2). The verbs name a substrate primitive — a signed
    per-query audit log — and carry no tenant-domain concept.

    Each verb delegates 1:1 to the consumer-facing `Session`/`LocalSession`
    abstraction (`audit_log` / `audit_fetch_by_query_id` / `audit_fetch_recent`);
    the service reimplements no signing, storage, or query logic. The
    `PerQueryAudit` message mirrors the Rust record field for field, including
    its server-computed `signature`.

    Tenant scope is read from the request's `SessionTenant` extension, set by the
    shared TenantInterceptor. The audit primitive requires a bound tenant — an
    unscoped call is rejected by the engine.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuditLog = channel.unary_unary(
                '/jammi.v1.audit.AuditService/AuditLog',
                request_serializer=jammi_dot_v1_dot_audit__pb2.AuditLogRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AuditFetchByQueryId = channel.unary_unary(
                '/jammi.v1.audit.AuditService/AuditFetchByQueryId',
                request_serializer=jammi_dot_v1_dot_audit__pb2.AuditFetchByQueryIdRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_audit__pb2.AuditFetchByQueryIdResponse.FromString,
                _registered_method=True)
        self.AuditFetchRecent = channel.unary_unary(
                '/jammi.v1.audit.AuditService/AuditFetchRecent',
                request_serializer=jammi_dot_v1_dot_audit__pb2.AuditFetchRecentRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_audit__pb2.AuditFetchRecentResponse.FromString,
                _registered_method=True)


class AuditServiceServicer:
    """AuditService — the wire surface for the engine's per-query audit verbs.

    `AuditLog`, `AuditFetchByQueryId`, and `AuditFetchRecent` are imperative
    session methods — signing, tenant-injection, and signature-verified decode
    are non-SQL logic — so they live as typed gRPC RPCs alongside the other
    engine-backed services rather than on the Flight SQL surface (query/result
    only, per ADR-01 §3.2). The verbs name a substrate primitive — a signed
    per-query audit log — and carry no tenant-domain concept.

    Each verb delegates 1:1 to the consumer-facing `Session`/`LocalSession`
    abstraction (`audit_log` / `audit_fetch_by_query_id` / `audit_fetch_recent`);
    the service reimplements no signing, storage, or query logic. The
    `PerQueryAudit` message mirrors the Rust record field for field, including
    its server-computed `signature`.

    Tenant scope is read from the request's `SessionTenant` extension, set by the
    shared TenantInterceptor. The audit primitive requires a bound tenant — an
    unscoped call is rejected by the engine.
    """

    def AuditLog(self, request, context):
        """Sign and persist a batch of audit records under the session's tenant,
        publishing them to the audit topic. Peer of the abstraction's `audit_log`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuditFetchByQueryId(self, request, context):
        """Fetch one audit record by query id (tenant-scoped). Peer of the
        abstraction's `audit_fetch_by_query_id`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuditFetchRecent(self, request, context):
        """Fetch the most recent audit records (tenant-scoped), newest first. Peer of
        the abstraction's `audit_fetch_recent`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuditLog': grpc.unary_unary_rpc_method_handler(
                    servicer.AuditLog,
                    request_deserializer=jammi_dot_v1_dot_audit__pb2.AuditLogRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AuditFetchByQueryId': grpc.unary_unary_rpc_method_handler(
                    servicer.AuditFetchByQueryId,
                    request_deserializer=jammi_dot_v1_dot_audit__pb2.AuditFetchByQueryIdRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_audit__pb2.AuditFetchByQueryIdResponse.SerializeToString,
            ),
            'AuditFetchRecent': grpc.unary_unary_rpc_method_handler(
                    servicer.AuditFetchRecent,
                    request_deserializer=jammi_dot_v1_dot_audit__pb2.AuditFetchRecentRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_audit__pb2.AuditFetchRecentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jammi.v1.audit.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jammi.v1.audit.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService:
    """AuditService — the wire surface for the engine's per-query audit verbs.

    `AuditLog`, `AuditFetchByQueryId`, and `AuditFetchRecent` are imperative
    session methods — signing, tenant-injection, and signature-verified decode
    are non-SQL logic — so they live as typed gRPC RPCs alongside the other
    engine-backed services rather than on the Flight SQL surface (query/result
    only, per ADR-01 §3.2). The verbs name a substrate primitive — a signed
    per-query audit log — and carry no tenant-domain concept.

    Each verb delegates 1:1 to the consumer-facing `Session`/`LocalSession`
    abstraction (`audit_log` / `audit_fetch_by_query_id` / `audit_fetch_recent`);
    the service reimplements no signing, storage, or query logic. The
    `PerQueryAudit` message mirrors the Rust record field for field, including
    its server-computed `signature`.

    Tenant scope is read from the request's `SessionTenant` extension, set by the
    shared TenantInterceptor. The audit primitive requires a bound tenant — an
    unscoped call is rejected by the engine.
    """

    @staticmethod
    def AuditLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.audit.AuditService/AuditLog',
            jammi_dot_v1_dot_audit__pb2.AuditLogRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuditFetchByQueryId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.audit.AuditService/AuditFetchByQueryId',
            jammi_dot_v1_dot_audit__pb2.AuditFetchByQueryIdRequest.SerializeToString,
            jammi_dot_v1_dot_audit__pb2.AuditFetchByQueryIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuditFetchRecent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.audit.AuditService/AuditFetchRecent',
            jammi_dot_v1_dot_audit__pb2.AuditFetchRecentRequest.SerializeToString,
            jammi_dot_v1_dot_audit__pb2.AuditFetchRecentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
