# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import catalog_pb2 as jammi_dot_v1_dot_catalog__pb2
GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jammi/v1/catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogServiceStub(object):
    """CatalogService — the engine's single control-plane surface: every
    catalog / metadata / lifecycle / observability RPC a remote client reaches.
    The verbs are imperative session methods (registry reads + lifecycle
    mutations), not SQL queries, so they live as typed gRPC RPCs distinct from
    the Flight SQL data-plane (which carries query/result only, per ADR-01
    §3.2) and the compute/stream data-plane services (embedding / inference /
    training / eval / pipeline / trigger / audit).

    Each verb delegates 1:1 to the consumer-facing `Session`
    abstraction; the service reimplements no catalog or lifecycle logic. The
    service spans five control concerns. Session: `SetTenant` / `GetTenant` /
    `ClearTenant` bind, read, and clear the calling session's tenant, and
    `GetServerInfo` is the capability handshake — the tenant trio is stateless
    w.r.t. the engine (it updates an in-process session table the
    TenantInterceptor reads on every downstream request) and `GetServerInfo`
    reports compile-time facts plus the runtime tier set, so both mount on the
    always-present core tier. Sources / models: `AddSource` / `RemoveSource` /
    `ListSources` / `DescribeSource` register and introspect data sources, and
    `ListModels` / `DescribeModel` introspect the model catalog while
    `DeleteModel` removes a model row. Channels:
    `RegisterChannel` / `AddChannelColumns` / `ListChannels` declare and
    introspect provenance channels. Mutable tables: `CreateMutableTable` /
    `DropMutableTable` / `ListMutableTables` register and introspect mutable
    companion tables. Topics: `RegisterTopic` / `DropTopic` / `ListTopics`
    register and introspect trigger-stream topics (the publish / subscribe
    compute verbs stay on TriggerService).

    Tenant scope is read from the request's `SessionTenant` extension, set by
    the shared TenantInterceptor from the `jammi-session-id` header — the same
    mechanism every other gRPC service and Flight SQL use.
    --- session -----------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetTenant = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/SetTenant',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.SetTenantRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetTenant = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/GetTenant',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.GetTenantResponse.FromString,
                _registered_method=True)
        self.ClearTenant = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/ClearTenant',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetServerInfo = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/GetServerInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.ServerInfo.FromString,
                _registered_method=True)
        self.AddSource = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/AddSource',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.AddSourceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveSource = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/RemoveSource',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.RemoveSourceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListSources = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/ListSources',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.ListSourcesRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.ListSourcesResponse.FromString,
                _registered_method=True)
        self.DescribeSource = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/DescribeSource',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.DescribeSourceRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.SourceDescriptor.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/ListModels',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.DescribeModel = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/DescribeModel',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.DescribeModelRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.Model.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/DeleteModel',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RegisterChannel = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/RegisterChannel',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.RegisterChannelRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AddChannelColumns = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/AddChannelColumns',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.AddChannelColumnsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListChannels = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/ListChannels',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.ListChannelsRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.ListChannelsResponse.FromString,
                _registered_method=True)
        self.VerifyMaterialization = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/VerifyMaterialization',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.VerifyMaterializationRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.VerifyMaterializationResponse.FromString,
                _registered_method=True)
        self.Staleness = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/Staleness',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.StalenessRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.StalenessResponse.FromString,
                _registered_method=True)
        self.DerivesFrom = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/DerivesFrom',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.DerivesFromRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.DerivesFromResponse.FromString,
                _registered_method=True)
        self.CreateMutableTable = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/CreateMutableTable',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.CreateMutableTableRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.CreateMutableTableResponse.FromString,
                _registered_method=True)
        self.DropMutableTable = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/DropMutableTable',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.DropMutableTableRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListMutableTables = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/ListMutableTables',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.ListMutableTablesRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.ListMutableTablesResponse.FromString,
                _registered_method=True)
        self.RegisterTopic = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/RegisterTopic',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.RegisterTopicRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.RegisterTopicResponse.FromString,
                _registered_method=True)
        self.DropTopic = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/DropTopic',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.DropTopicRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListTopics = channel.unary_unary(
                '/jammi.v1.catalog.CatalogService/ListTopics',
                request_serializer=jammi_dot_v1_dot_catalog__pb2.ListTopicsRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_catalog__pb2.ListTopicsResponse.FromString,
                _registered_method=True)


class CatalogServiceServicer(object):
    """CatalogService — the engine's single control-plane surface: every
    catalog / metadata / lifecycle / observability RPC a remote client reaches.
    The verbs are imperative session methods (registry reads + lifecycle
    mutations), not SQL queries, so they live as typed gRPC RPCs distinct from
    the Flight SQL data-plane (which carries query/result only, per ADR-01
    §3.2) and the compute/stream data-plane services (embedding / inference /
    training / eval / pipeline / trigger / audit).

    Each verb delegates 1:1 to the consumer-facing `Session`
    abstraction; the service reimplements no catalog or lifecycle logic. The
    service spans five control concerns. Session: `SetTenant` / `GetTenant` /
    `ClearTenant` bind, read, and clear the calling session's tenant, and
    `GetServerInfo` is the capability handshake — the tenant trio is stateless
    w.r.t. the engine (it updates an in-process session table the
    TenantInterceptor reads on every downstream request) and `GetServerInfo`
    reports compile-time facts plus the runtime tier set, so both mount on the
    always-present core tier. Sources / models: `AddSource` / `RemoveSource` /
    `ListSources` / `DescribeSource` register and introspect data sources, and
    `ListModels` / `DescribeModel` introspect the model catalog while
    `DeleteModel` removes a model row. Channels:
    `RegisterChannel` / `AddChannelColumns` / `ListChannels` declare and
    introspect provenance channels. Mutable tables: `CreateMutableTable` /
    `DropMutableTable` / `ListMutableTables` register and introspect mutable
    companion tables. Topics: `RegisterTopic` / `DropTopic` / `ListTopics`
    register and introspect trigger-stream topics (the publish / subscribe
    compute verbs stay on TriggerService).

    Tenant scope is read from the request's `SessionTenant` extension, set by
    the shared TenantInterceptor from the `jammi-session-id` header — the same
    mechanism every other gRPC service and Flight SQL use.
    --- session -----------------------------------------------------------
    """

    def SetTenant(self, request, context):
        """Bind a tenant for the calling session. Idempotent — calling twice with
        the same tenant is a no-op. Replacing an existing binding is allowed
        (the auth layer above the engine validates the caller is permitted).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenant(self, request, context):
        """Return the tenant currently bound to the calling session, or an unset
        tenant if none is bound.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearTenant(self, request, context):
        """Clear the tenant binding for the calling session. After this returns,
        subsequent requests on the same session see an unscoped tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerInfo(self, request, context):
        """Capabilities handshake: the engine's version, the feature flags this
        build was compiled with, and the storage backends it can address. Static
        per build, tenant-agnostic, and engine-independent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSource(self, request, context):
        """--- sources / models --------------------------------------------------

        Register a data source so a later GenerateEmbeddings call can scan it.
        Peer of the abstraction's `add_source`. The source carries any modality
        the engine supports; the kind here is the storage backend, not the
        content modality. Idempotent only insofar as the engine allows —
        re-registering an id that already exists is an error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSource(self, request, context):
        """Remove a registered source and all associated state (embedding tables,
        indexes). Peer of the abstraction's `remove_source`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSources(self, request, context):
        """List a `SourceDescriptor` for every source registered to the calling
        tenant. Peer of the abstraction's `list_sources`; registry introspection,
        not a SQL query. `ListSources` is `DescribeSource` applied over every
        registered source — one descriptor shape, one operator, no per-source
        special-casing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeSource(self, request, context):
        """Describe one registered source: its registry identity (id / kind /
        lifecycle status) plus the result tables embedded out of it (each carrying
        its own status / row_count / dimensions). Peer of the abstraction's
        `describe_source`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """List a `Model` record for every model registered to the calling tenant.
        Peer of the abstraction's `list_models`; registry introspection, not a SQL
        query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeModel(self, request, context):
        """Describe one registered model by id: the same `Model` projection
        `ListModels` carries, for the latest registered version. Peer of the
        abstraction's `describe_model`. An absent model returns NotFound.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Hard-delete a model row. Peer of the abstraction's `delete_model`. This
        removes the row, so it is refused with `FailedPrecondition` while any
        reference still points at the model (a result table, a training job's base
        or output model, an eval run). When `version` is unset the latest version
        is targeted. A tenant may delete ONLY a model it owns. `if_exists` makes a
        missing model a no-op rather than a NotFound error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterChannel(self, request, context):
        """--- channels ----------------------------------------------------------

        Register a provenance channel and its initial columns. Peer of the
        abstraction's `register_channel`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddChannelColumns(self, request, context):
        """Append columns to an already-registered channel (append-only). Peer of the
        abstraction's `add_channel_columns`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChannels(self, request, context):
        """List every channel registered to the calling tenant, ordered by
        `(priority, channel_id)`. Peer of the abstraction's `list_channels`;
        registry introspection, not a SQL query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyMaterialization(self, request, context):
        """--- materialization contract ------------------------------------------

        Recompute a materialised result table's artifact digest and check it (and,
        if given, an expected definition hash) against its `.materialization.json`
        manifest. Read-only; returns a verdict, never acting on one. Peer of the
        abstraction's `verify_materialization`. The verdict attests the Parquet
        data, never the ANN search index.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Staleness(self, request, context):
        """Report whether a `ready` result table is still the output of its recorded
        definition over its recorded inputs' current state. Read-only sensor;
        reports a verdict, never acting on one (recompute / accept / alarm is the
        reader's policy). Peer of the abstraction's `staleness`. Tenant-scoped: a
        peer cannot sense a table it cannot resolve.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DerivesFrom(self, request, context):
        """Return the one-hop reverse-dependency edges of a result table — every
        `ready` table that anchored on it. Read-only lineage data; the caller walks
        it transitively. Peer of the abstraction's `derives_from`. Tenant-scoped.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMutableTable(self, request, context):
        """--- mutable tables ----------------------------------------------------

        Register a mutable companion table. After this returns the table is
        queryable through Flight SQL. Peer of the abstraction's
        `create_mutable_table`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropMutableTable(self, request, context):
        """Drop a mutable companion table. Peer of the abstraction's
        `drop_mutable_table`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMutableTables(self, request, context):
        """List every mutable companion table registered to the calling tenant. Peer
        of the abstraction's `list_mutable_tables`; registry introspection, not a
        SQL query. Each entry is the same `MutableTableDefinition` the create path
        carries (minus tenant, which rides the session scope).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterTopic(self, request, context):
        """--- topics ------------------------------------------------------------

        Register a topic (provisions its backing table) for the trigger stream.
        Peer of the abstraction's `register_topic`. The schema is the contract
        every published batch must satisfy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropTopic(self, request, context):
        """Drop a topic and its backing table. Peer of the abstraction's
        `drop_topic`. `if_exists` makes a missing topic a no-op rather than a
        NotFound error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTopics(self, request, context):
        """List topics registered in the catalog. Pagination follows AIP-132.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTenant,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.SetTenantRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenant,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.GetTenantResponse.SerializeToString,
            ),
            'ClearTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearTenant,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.ServerInfo.SerializeToString,
            ),
            'AddSource': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSource,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.AddSourceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveSource': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSource,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.RemoveSourceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListSources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSources,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.ListSourcesRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.ListSourcesResponse.SerializeToString,
            ),
            'DescribeSource': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeSource,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.DescribeSourceRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.SourceDescriptor.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.ListModelsRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.ListModelsResponse.SerializeToString,
            ),
            'DescribeModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeModel,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.DescribeModelRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.Model.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.DeleteModelRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RegisterChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterChannel,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.RegisterChannelRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddChannelColumns': grpc.unary_unary_rpc_method_handler(
                    servicer.AddChannelColumns,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.AddChannelColumnsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChannels,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.ListChannelsRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.ListChannelsResponse.SerializeToString,
            ),
            'VerifyMaterialization': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyMaterialization,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.VerifyMaterializationRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.VerifyMaterializationResponse.SerializeToString,
            ),
            'Staleness': grpc.unary_unary_rpc_method_handler(
                    servicer.Staleness,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.StalenessRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.StalenessResponse.SerializeToString,
            ),
            'DerivesFrom': grpc.unary_unary_rpc_method_handler(
                    servicer.DerivesFrom,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.DerivesFromRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.DerivesFromResponse.SerializeToString,
            ),
            'CreateMutableTable': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMutableTable,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.CreateMutableTableRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.CreateMutableTableResponse.SerializeToString,
            ),
            'DropMutableTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DropMutableTable,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.DropMutableTableRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListMutableTables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMutableTables,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.ListMutableTablesRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.ListMutableTablesResponse.SerializeToString,
            ),
            'RegisterTopic': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTopic,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.RegisterTopicRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.RegisterTopicResponse.SerializeToString,
            ),
            'DropTopic': grpc.unary_unary_rpc_method_handler(
                    servicer.DropTopic,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.DropTopicRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTopics,
                    request_deserializer=jammi_dot_v1_dot_catalog__pb2.ListTopicsRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_catalog__pb2.ListTopicsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jammi.v1.catalog.CatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jammi.v1.catalog.CatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogService(object):
    """CatalogService — the engine's single control-plane surface: every
    catalog / metadata / lifecycle / observability RPC a remote client reaches.
    The verbs are imperative session methods (registry reads + lifecycle
    mutations), not SQL queries, so they live as typed gRPC RPCs distinct from
    the Flight SQL data-plane (which carries query/result only, per ADR-01
    §3.2) and the compute/stream data-plane services (embedding / inference /
    training / eval / pipeline / trigger / audit).

    Each verb delegates 1:1 to the consumer-facing `Session`
    abstraction; the service reimplements no catalog or lifecycle logic. The
    service spans five control concerns. Session: `SetTenant` / `GetTenant` /
    `ClearTenant` bind, read, and clear the calling session's tenant, and
    `GetServerInfo` is the capability handshake — the tenant trio is stateless
    w.r.t. the engine (it updates an in-process session table the
    TenantInterceptor reads on every downstream request) and `GetServerInfo`
    reports compile-time facts plus the runtime tier set, so both mount on the
    always-present core tier. Sources / models: `AddSource` / `RemoveSource` /
    `ListSources` / `DescribeSource` register and introspect data sources, and
    `ListModels` / `DescribeModel` introspect the model catalog while
    `DeleteModel` removes a model row. Channels:
    `RegisterChannel` / `AddChannelColumns` / `ListChannels` declare and
    introspect provenance channels. Mutable tables: `CreateMutableTable` /
    `DropMutableTable` / `ListMutableTables` register and introspect mutable
    companion tables. Topics: `RegisterTopic` / `DropTopic` / `ListTopics`
    register and introspect trigger-stream topics (the publish / subscribe
    compute verbs stay on TriggerService).

    Tenant scope is read from the request's `SessionTenant` extension, set by
    the shared TenantInterceptor from the `jammi-session-id` header — the same
    mechanism every other gRPC service and Flight SQL use.
    --- session -----------------------------------------------------------
    """

    @staticmethod
    def SetTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/SetTenant',
            jammi_dot_v1_dot_catalog__pb2.SetTenantRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/GetTenant',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.GetTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/ClearTenant',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/GetServerInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.ServerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/AddSource',
            jammi_dot_v1_dot_catalog__pb2.AddSourceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/RemoveSource',
            jammi_dot_v1_dot_catalog__pb2.RemoveSourceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/ListSources',
            jammi_dot_v1_dot_catalog__pb2.ListSourcesRequest.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.ListSourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/DescribeSource',
            jammi_dot_v1_dot_catalog__pb2.DescribeSourceRequest.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.SourceDescriptor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/ListModels',
            jammi_dot_v1_dot_catalog__pb2.ListModelsRequest.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/DescribeModel',
            jammi_dot_v1_dot_catalog__pb2.DescribeModelRequest.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.Model.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/DeleteModel',
            jammi_dot_v1_dot_catalog__pb2.DeleteModelRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/RegisterChannel',
            jammi_dot_v1_dot_catalog__pb2.RegisterChannelRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddChannelColumns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/AddChannelColumns',
            jammi_dot_v1_dot_catalog__pb2.AddChannelColumnsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/ListChannels',
            jammi_dot_v1_dot_catalog__pb2.ListChannelsRequest.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.ListChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyMaterialization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/VerifyMaterialization',
            jammi_dot_v1_dot_catalog__pb2.VerifyMaterializationRequest.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.VerifyMaterializationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Staleness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/Staleness',
            jammi_dot_v1_dot_catalog__pb2.StalenessRequest.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.StalenessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DerivesFrom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/DerivesFrom',
            jammi_dot_v1_dot_catalog__pb2.DerivesFromRequest.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.DerivesFromResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMutableTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/CreateMutableTable',
            jammi_dot_v1_dot_catalog__pb2.CreateMutableTableRequest.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.CreateMutableTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropMutableTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/DropMutableTable',
            jammi_dot_v1_dot_catalog__pb2.DropMutableTableRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMutableTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/ListMutableTables',
            jammi_dot_v1_dot_catalog__pb2.ListMutableTablesRequest.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.ListMutableTablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/RegisterTopic',
            jammi_dot_v1_dot_catalog__pb2.RegisterTopicRequest.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.RegisterTopicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/DropTopic',
            jammi_dot_v1_dot_catalog__pb2.DropTopicRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.catalog.CatalogService/ListTopics',
            jammi_dot_v1_dot_catalog__pb2.ListTopicsRequest.SerializeToString,
            jammi_dot_v1_dot_catalog__pb2.ListTopicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
