# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import channel_pb2 as jammi_dot_v1_dot_channel__pb2
GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jammi/v1/channel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChannelServiceStub:
    """ChannelService — the wire surface for the engine's provenance-channel
    declaration verbs.

    `RegisterChannel` and `AddChannelColumns` are imperative session methods, not
    SQL queries, so they live as typed gRPC RPCs alongside the other engine-
    backed services rather than on the Flight SQL surface (query/result only, per
    ADR-01 §3.2). The verbs name a substrate primitive — a provenance channel and
    its declared columns — and carry no tenant-domain concept.

    Each verb delegates 1:1 to the consumer-facing `Session`/`LocalSession`
    abstraction (`register_channel` / `add_channel_columns`); the service
    reimplements no catalog logic. The messages mirror the Rust `ChannelSpec` /
    `ChannelColumn` field for field.

    Tenant scope is read from the request's `SessionTenant` extension, set by the
    shared TenantInterceptor — the same mechanism every other gRPC service uses.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterChannel = channel.unary_unary(
                '/jammi.v1.channel.ChannelService/RegisterChannel',
                request_serializer=jammi_dot_v1_dot_channel__pb2.RegisterChannelRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AddChannelColumns = channel.unary_unary(
                '/jammi.v1.channel.ChannelService/AddChannelColumns',
                request_serializer=jammi_dot_v1_dot_channel__pb2.AddChannelColumnsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ChannelServiceServicer:
    """ChannelService — the wire surface for the engine's provenance-channel
    declaration verbs.

    `RegisterChannel` and `AddChannelColumns` are imperative session methods, not
    SQL queries, so they live as typed gRPC RPCs alongside the other engine-
    backed services rather than on the Flight SQL surface (query/result only, per
    ADR-01 §3.2). The verbs name a substrate primitive — a provenance channel and
    its declared columns — and carry no tenant-domain concept.

    Each verb delegates 1:1 to the consumer-facing `Session`/`LocalSession`
    abstraction (`register_channel` / `add_channel_columns`); the service
    reimplements no catalog logic. The messages mirror the Rust `ChannelSpec` /
    `ChannelColumn` field for field.

    Tenant scope is read from the request's `SessionTenant` extension, set by the
    shared TenantInterceptor — the same mechanism every other gRPC service uses.
    """

    def RegisterChannel(self, request, context):
        """Register a provenance channel and its initial columns. Peer of the
        abstraction's `register_channel`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddChannelColumns(self, request, context):
        """Append columns to an already-registered channel (append-only). Peer of the
        abstraction's `add_channel_columns`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChannelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterChannel,
                    request_deserializer=jammi_dot_v1_dot_channel__pb2.RegisterChannelRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddChannelColumns': grpc.unary_unary_rpc_method_handler(
                    servicer.AddChannelColumns,
                    request_deserializer=jammi_dot_v1_dot_channel__pb2.AddChannelColumnsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jammi.v1.channel.ChannelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jammi.v1.channel.ChannelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChannelService:
    """ChannelService — the wire surface for the engine's provenance-channel
    declaration verbs.

    `RegisterChannel` and `AddChannelColumns` are imperative session methods, not
    SQL queries, so they live as typed gRPC RPCs alongside the other engine-
    backed services rather than on the Flight SQL surface (query/result only, per
    ADR-01 §3.2). The verbs name a substrate primitive — a provenance channel and
    its declared columns — and carry no tenant-domain concept.

    Each verb delegates 1:1 to the consumer-facing `Session`/`LocalSession`
    abstraction (`register_channel` / `add_channel_columns`); the service
    reimplements no catalog logic. The messages mirror the Rust `ChannelSpec` /
    `ChannelColumn` field for field.

    Tenant scope is read from the request's `SessionTenant` extension, set by the
    shared TenantInterceptor — the same mechanism every other gRPC service uses.
    """

    @staticmethod
    def RegisterChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.channel.ChannelService/RegisterChannel',
            jammi_dot_v1_dot_channel__pb2.RegisterChannelRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddChannelColumns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.channel.ChannelService/AddChannelColumns',
            jammi_dot_v1_dot_channel__pb2.AddChannelColumnsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
