# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jammi/v1/channel.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'jammi/v1/channel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16jammi/v1/channel.proto\x12\x10jammi.v1.channel\x1a\x1bgoogle/protobuf/empty.proto\"U\n\rChannelColumn\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x36\n\tdata_type\x18\x02 \x01(\x0e\x32#.jammi.v1.channel.ChannelColumnType\"p\n\x16RegisterChannelRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\x30\n\x07\x63olumns\x18\x03 \x03(\x0b\x32\x1f.jammi.v1.channel.ChannelColumn\"`\n\x18\x41\x64\x64\x43hannelColumnsRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\t\x12\x30\n\x07\x63olumns\x18\x02 \x03(\x0b\x32\x1f.jammi.v1.channel.ChannelColumn*\xf7\x01\n\x11\x43hannelColumnType\x12#\n\x1f\x43HANNEL_COLUMN_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x43HANNEL_COLUMN_TYPE_FLOAT32\x10\x01\x12\x1f\n\x1b\x43HANNEL_COLUMN_TYPE_FLOAT64\x10\x02\x12\x1d\n\x19\x43HANNEL_COLUMN_TYPE_INT32\x10\x03\x12\x1d\n\x19\x43HANNEL_COLUMN_TYPE_INT64\x10\x04\x12\x1c\n\x18\x43HANNEL_COLUMN_TYPE_UTF8\x10\x05\x12\x1f\n\x1b\x43HANNEL_COLUMN_TYPE_BOOLEAN\x10\x06\x32\xbe\x01\n\x0e\x43hannelService\x12S\n\x0fRegisterChannel\x12(.jammi.v1.channel.RegisterChannelRequest\x1a\x16.google.protobuf.Empty\x12W\n\x11\x41\x64\x64\x43hannelColumns\x12*.jammi.v1.channel.AddChannelColumnsRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jammi.v1.channel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANNELCOLUMNTYPE']._serialized_start=373
  _globals['_CHANNELCOLUMNTYPE']._serialized_end=620
  _globals['_CHANNELCOLUMN']._serialized_start=73
  _globals['_CHANNELCOLUMN']._serialized_end=158
  _globals['_REGISTERCHANNELREQUEST']._serialized_start=160
  _globals['_REGISTERCHANNELREQUEST']._serialized_end=272
  _globals['_ADDCHANNELCOLUMNSREQUEST']._serialized_start=274
  _globals['_ADDCHANNELCOLUMNSREQUEST']._serialized_end=370
  _globals['_CHANNELSERVICE']._serialized_start=623
  _globals['_CHANNELSERVICE']._serialized_end=813
# @@protoc_insertion_point(module_scope)
