# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import embedding_pb2 as jammi_dot_v1_dot_embedding__pb2
GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jammi/v1/embedding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub(object):
    """EmbeddingService — the wire surface for the engine's embedding compute
    verbs. These are imperative session methods, not SQL queries, so they live
    as typed gRPC RPCs alongside InferenceService / TriggerService rather than on
    the Flight SQL surface (which carries query/result only, per ADR-01 §3.2).

    The surface is modality-agnostic: one GenerateEmbeddings / EncodeQuery pair
    keyed by a `Modality` selects the text, image, or audio tower, rather than a
    verb per modality. Each verb delegates 1:1 to the consumer-facing
    `Session` abstraction, which dispatches the modality onto the
    engine's concrete tower method — the service reimplements no decode,
    feature-extraction, or forward logic; it is purely a wire adapter over the
    in-process engine. Jammi stays non-generative: these encode input → vector,
    never generate.

    Source registration and model introspection — the control-plane catalog
    surface this compute lane reads — live on CatalogService, not here. This
    service carries the data-plane compute verbs only.

    Tenant scope is read from the request's `SessionTenant` extension, set by
    the shared TenantInterceptor from the `jammi-session-id` header — the same
    mechanism CatalogService / TriggerService / Flight SQL already use.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateEmbeddings = channel.unary_unary(
                '/jammi.v1.embedding.EmbeddingService/GenerateEmbeddings',
                request_serializer=jammi_dot_v1_dot_embedding__pb2.GenerateEmbeddingsRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_embedding__pb2.ResultTable.FromString,
                _registered_method=True)
        self.EncodeQuery = channel.unary_unary(
                '/jammi.v1.embedding.EmbeddingService/EncodeQuery',
                request_serializer=jammi_dot_v1_dot_embedding__pb2.EncodeQueryRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_embedding__pb2.EncodeQueryResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/jammi.v1.embedding.EmbeddingService/Search',
                request_serializer=jammi_dot_v1_dot_embedding__pb2.SearchRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_embedding__pb2.SearchResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """EmbeddingService — the wire surface for the engine's embedding compute
    verbs. These are imperative session methods, not SQL queries, so they live
    as typed gRPC RPCs alongside InferenceService / TriggerService rather than on
    the Flight SQL surface (which carries query/result only, per ADR-01 §3.2).

    The surface is modality-agnostic: one GenerateEmbeddings / EncodeQuery pair
    keyed by a `Modality` selects the text, image, or audio tower, rather than a
    verb per modality. Each verb delegates 1:1 to the consumer-facing
    `Session` abstraction, which dispatches the modality onto the
    engine's concrete tower method — the service reimplements no decode,
    feature-extraction, or forward logic; it is purely a wire adapter over the
    in-process engine. Jammi stays non-generative: these encode input → vector,
    never generate.

    Source registration and model introspection — the control-plane catalog
    surface this compute lane reads — live on CatalogService, not here. This
    service carries the data-plane compute verbs only.

    Tenant scope is read from the request's `SessionTenant` extension, set by
    the shared TenantInterceptor from the `jammi-session-id` header — the same
    mechanism CatalogService / TriggerService / Flight SQL already use.
    """

    def GenerateEmbeddings(self, request, context):
        """Scan `columns` on a registered source, run the modality's tower over
        every row (decode/feature-extraction as the modality requires → forward
        pass), persist one L2-normalized vector per row keyed by `key_column`,
        and return the result-table record. The `modality` selects which tower.
        Peer of the abstraction's `generate_embeddings`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeQuery(self, request, context):
        """Encode a single query into one L2-normalized embedding with the modality's
        tower. The `modality` selects the tower; the `input` oneof must match it —
        `text` for TEXT, `data` (raw encoded bytes) for IMAGE/AUDIO. Peer of the
        abstraction's `encode_query`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Nearest-neighbor search over a source's embedding table. The query is
        either a precomputed vector (encode-then-search) or an existing row's key
        (query-by-example; the engine resolves that row's stored vector
        internally — the vector never crosses the wire). Peer of the
        abstraction's flat `search`. This is the embedding-consumption verb on the
        gRPC surface edge runtimes reach (gRPC-web); it adds no new consumption
        model, only an additional transport for the existing capability.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbeddings,
                    request_deserializer=jammi_dot_v1_dot_embedding__pb2.GenerateEmbeddingsRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_embedding__pb2.ResultTable.SerializeToString,
            ),
            'EncodeQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeQuery,
                    request_deserializer=jammi_dot_v1_dot_embedding__pb2.EncodeQueryRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_embedding__pb2.EncodeQueryResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=jammi_dot_v1_dot_embedding__pb2.SearchRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_embedding__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jammi.v1.embedding.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jammi.v1.embedding.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """EmbeddingService — the wire surface for the engine's embedding compute
    verbs. These are imperative session methods, not SQL queries, so they live
    as typed gRPC RPCs alongside InferenceService / TriggerService rather than on
    the Flight SQL surface (which carries query/result only, per ADR-01 §3.2).

    The surface is modality-agnostic: one GenerateEmbeddings / EncodeQuery pair
    keyed by a `Modality` selects the text, image, or audio tower, rather than a
    verb per modality. Each verb delegates 1:1 to the consumer-facing
    `Session` abstraction, which dispatches the modality onto the
    engine's concrete tower method — the service reimplements no decode,
    feature-extraction, or forward logic; it is purely a wire adapter over the
    in-process engine. Jammi stays non-generative: these encode input → vector,
    never generate.

    Source registration and model introspection — the control-plane catalog
    surface this compute lane reads — live on CatalogService, not here. This
    service carries the data-plane compute verbs only.

    Tenant scope is read from the request's `SessionTenant` extension, set by
    the shared TenantInterceptor from the `jammi-session-id` header — the same
    mechanism CatalogService / TriggerService / Flight SQL already use.
    """

    @staticmethod
    def GenerateEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.embedding.EmbeddingService/GenerateEmbeddings',
            jammi_dot_v1_dot_embedding__pb2.GenerateEmbeddingsRequest.SerializeToString,
            jammi_dot_v1_dot_embedding__pb2.ResultTable.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncodeQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.embedding.EmbeddingService/EncodeQuery',
            jammi_dot_v1_dot_embedding__pb2.EncodeQueryRequest.SerializeToString,
            jammi_dot_v1_dot_embedding__pb2.EncodeQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.embedding.EmbeddingService/Search',
            jammi_dot_v1_dot_embedding__pb2.SearchRequest.SerializeToString,
            jammi_dot_v1_dot_embedding__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
