# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fine_tune_pb2 as jammi_dot_v1_dot_fine__tune__pb2
GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jammi/v1/fine_tune_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FineTuneServiceStub:
    """FineTuneService — the wire surface for the engine's fine-tuning verb.

    `StartFineTune` and `FineTuneStatus` are imperative session methods, not SQL
    queries, so they live as typed gRPC RPCs alongside SessionService /
    TriggerService / EmbeddingService / InferenceService / EvalService rather
    than on the Flight SQL surface (which carries query/result only, per ADR-01
    §3.2). Fine-tuning is a substrate primitive — training a LoRA adapter over a
    registered source — and names no tenant-domain concept.

    The two verbs delegate 1:1 to the consumer-facing `Session`/`LocalSession`
    abstraction: `StartFineTune` mirrors `Session::fine_tune` (which returns a
    `FineTuneJobId`) and `FineTuneStatus` mirrors `Session::fine_tune_status`.
    The job runs asynchronously inside the engine; the client polls
    `FineTuneStatus` by id until a terminal state. There is no progress stream —
    the abstraction exposes none, so this surface invents none. The service
    reimplements no training, LoRA, or scan logic; it is purely a wire adapter.

    Tenant scope is read from the request's `SessionTenant` extension, set by the
    shared TenantInterceptor from the `jammi-session-id` header — the same
    mechanism every other gRPC service and Flight SQL already use.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartFineTune = channel.unary_unary(
                '/jammi.v1.fine_tune.FineTuneService/StartFineTune',
                request_serializer=jammi_dot_v1_dot_fine__tune__pb2.StartFineTuneRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_fine__tune__pb2.StartFineTuneResponse.FromString,
                _registered_method=True)
        self.FineTuneStatus = channel.unary_unary(
                '/jammi.v1.fine_tune.FineTuneService/FineTuneStatus',
                request_serializer=jammi_dot_v1_dot_fine__tune__pb2.FineTuneStatusRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_fine__tune__pb2.FineTuneStatusResponse.FromString,
                _registered_method=True)


class FineTuneServiceServicer:
    """FineTuneService — the wire surface for the engine's fine-tuning verb.

    `StartFineTune` and `FineTuneStatus` are imperative session methods, not SQL
    queries, so they live as typed gRPC RPCs alongside SessionService /
    TriggerService / EmbeddingService / InferenceService / EvalService rather
    than on the Flight SQL surface (which carries query/result only, per ADR-01
    §3.2). Fine-tuning is a substrate primitive — training a LoRA adapter over a
    registered source — and names no tenant-domain concept.

    The two verbs delegate 1:1 to the consumer-facing `Session`/`LocalSession`
    abstraction: `StartFineTune` mirrors `Session::fine_tune` (which returns a
    `FineTuneJobId`) and `FineTuneStatus` mirrors `Session::fine_tune_status`.
    The job runs asynchronously inside the engine; the client polls
    `FineTuneStatus` by id until a terminal state. There is no progress stream —
    the abstraction exposes none, so this surface invents none. The service
    reimplements no training, LoRA, or scan logic; it is purely a wire adapter.

    Tenant scope is read from the request's `SessionTenant` extension, set by the
    shared TenantInterceptor from the `jammi-session-id` header — the same
    mechanism every other gRPC service and Flight SQL already use.
    """

    def StartFineTune(self, request, context):
        """Start a fine-tuning job over a registered source and return its id. The
        job trains asynchronously; poll `FineTuneStatus` with the returned id.
        Peer of the abstraction's `fine_tune`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FineTuneStatus(self, request, context):
        """Read a fine-tune job's current status by id. Peer of the abstraction's
        `fine_tune_status`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FineTuneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartFineTune': grpc.unary_unary_rpc_method_handler(
                    servicer.StartFineTune,
                    request_deserializer=jammi_dot_v1_dot_fine__tune__pb2.StartFineTuneRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_fine__tune__pb2.StartFineTuneResponse.SerializeToString,
            ),
            'FineTuneStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.FineTuneStatus,
                    request_deserializer=jammi_dot_v1_dot_fine__tune__pb2.FineTuneStatusRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_fine__tune__pb2.FineTuneStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jammi.v1.fine_tune.FineTuneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jammi.v1.fine_tune.FineTuneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FineTuneService:
    """FineTuneService — the wire surface for the engine's fine-tuning verb.

    `StartFineTune` and `FineTuneStatus` are imperative session methods, not SQL
    queries, so they live as typed gRPC RPCs alongside SessionService /
    TriggerService / EmbeddingService / InferenceService / EvalService rather
    than on the Flight SQL surface (which carries query/result only, per ADR-01
    §3.2). Fine-tuning is a substrate primitive — training a LoRA adapter over a
    registered source — and names no tenant-domain concept.

    The two verbs delegate 1:1 to the consumer-facing `Session`/`LocalSession`
    abstraction: `StartFineTune` mirrors `Session::fine_tune` (which returns a
    `FineTuneJobId`) and `FineTuneStatus` mirrors `Session::fine_tune_status`.
    The job runs asynchronously inside the engine; the client polls
    `FineTuneStatus` by id until a terminal state. There is no progress stream —
    the abstraction exposes none, so this surface invents none. The service
    reimplements no training, LoRA, or scan logic; it is purely a wire adapter.

    Tenant scope is read from the request's `SessionTenant` extension, set by the
    shared TenantInterceptor from the `jammi-session-id` header — the same
    mechanism every other gRPC service and Flight SQL already use.
    """

    @staticmethod
    def StartFineTune(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.fine_tune.FineTuneService/StartFineTune',
            jammi_dot_v1_dot_fine__tune__pb2.StartFineTuneRequest.SerializeToString,
            jammi_dot_v1_dot_fine__tune__pb2.StartFineTuneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FineTuneStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.fine_tune.FineTuneService/FineTuneStatus',
            jammi_dot_v1_dot_fine__tune__pb2.FineTuneStatusRequest.SerializeToString,
            jammi_dot_v1_dot_fine__tune__pb2.FineTuneStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
