# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jammi/v1/inference.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'jammi/v1/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import trigger_pb2 as jammi_dot_v1_dot_trigger__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18jammi/v1/inference.proto\x12\x12jammi.v1.inference\x1a\x16jammi/v1/trigger.proto\"\x98\x01\n\x0cInferRequest\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12+\n\x04task\x18\x03 \x01(\x0e\x32\x1d.jammi.v1.inference.ModelTask\x12\x0f\n\x07\x63olumns\x18\x04 \x03(\t\x12\x12\n\nkey_column\x18\x05 \x01(\t\x12\x11\n\ttenant_id\x18\x06 \x01(\t\"=\n\rInferResponse\x12,\n\x06result\x18\x01 \x01(\x0b\x32\x1c.jammi.v1.trigger.ArrowBatch*\x82\x01\n\tModelTask\x12\x1a\n\x16MODEL_TASK_UNSPECIFIED\x10\x00\x12\x12\n\x0eTEXT_EMBEDDING\x10\x01\x12\x13\n\x0fIMAGE_EMBEDDING\x10\x02\x12\x13\n\x0f\x41UDIO_EMBEDDING\x10\x03\x12\x12\n\x0e\x43LASSIFICATION\x10\x04\x12\x07\n\x03NER\x10\x05\x32`\n\x10InferenceService\x12L\n\x05Infer\x12 .jammi.v1.inference.InferRequest\x1a!.jammi.v1.inference.InferResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jammi.v1.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELTASK']._serialized_start=291
  _globals['_MODELTASK']._serialized_end=421
  _globals['_INFERREQUEST']._serialized_start=73
  _globals['_INFERREQUEST']._serialized_end=225
  _globals['_INFERRESPONSE']._serialized_start=227
  _globals['_INFERRESPONSE']._serialized_end=288
  _globals['_INFERENCESERVICE']._serialized_start=423
  _globals['_INFERENCESERVICE']._serialized_end=519
# @@protoc_insertion_point(module_scope)
