# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import embedding_pb2 as jammi_dot_v1_dot_embedding__pb2
from . import pipeline_pb2 as jammi_dot_v1_dot_pipeline__pb2
GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jammi/v1/pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PipelineServiceStub(object):
    """PipelineService — the wire surface for the engine's compute-to-data engine-
    state verbs that build durable graph/embedding artifacts or assemble a
    target's conditioning context.

    `BuildNeighborGraph`, `PropagateEmbeddings`, and `AssembleContext` are
    imperative session methods, not SQL queries, so they live as typed gRPC RPCs
    alongside SessionService / EmbeddingService / InferenceService / EvalService
    rather than on the Flight SQL surface (which carries query/result only, per
    ADR-01 §3.2). They are substrate primitives — materialising a k-NN graph,
    propagating features over a declared graph, or pooling a retrieval into a
    fixed-width context vector — and name no tenant-domain concept.

    Each verb delegates 1:1 to the engine session; the service reimplements no
    retrieval, graph, or aggregation logic — it is purely a wire adapter over the
    in-process engine. The two graph-build verbs transport only a result-table
    name (the compute stays server-side, so the materialised table is
    byte-identical to one built in-process); `AssembleContext` carries its pooled
    vector inline as IEEE-754 `float` (bit-exact for the engine's `Vec<f32>`).

    Tenant scope is read from the request's `SessionTenant` extension, set by the
    shared TenantInterceptor from the `jammi-session-id` header — the same
    mechanism every other gRPC service and Flight SQL already use.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuildNeighborGraph = channel.unary_unary(
                '/jammi.v1.pipeline.PipelineService/BuildNeighborGraph',
                request_serializer=jammi_dot_v1_dot_pipeline__pb2.BuildNeighborGraphRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_embedding__pb2.ResultTable.FromString,
                _registered_method=True)
        self.PropagateEmbeddings = channel.unary_unary(
                '/jammi.v1.pipeline.PipelineService/PropagateEmbeddings',
                request_serializer=jammi_dot_v1_dot_pipeline__pb2.PropagateEmbeddingsRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_embedding__pb2.ResultTable.FromString,
                _registered_method=True)
        self.AssembleContext = channel.unary_unary(
                '/jammi.v1.pipeline.PipelineService/AssembleContext',
                request_serializer=jammi_dot_v1_dot_pipeline__pb2.AssembleContextRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_pipeline__pb2.AssembleContextResponse.FromString,
                _registered_method=True)
        self.AsofJoin = channel.unary_unary(
                '/jammi.v1.pipeline.PipelineService/AsofJoin',
                request_serializer=jammi_dot_v1_dot_pipeline__pb2.AsofJoinRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_embedding__pb2.ResultTable.FromString,
                _registered_method=True)
        self.Recompute = channel.unary_unary(
                '/jammi.v1.pipeline.PipelineService/Recompute',
                request_serializer=jammi_dot_v1_dot_pipeline__pb2.RecomputeRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_pipeline__pb2.RecomputeReport.FromString,
                _registered_method=True)


class PipelineServiceServicer(object):
    """PipelineService — the wire surface for the engine's compute-to-data engine-
    state verbs that build durable graph/embedding artifacts or assemble a
    target's conditioning context.

    `BuildNeighborGraph`, `PropagateEmbeddings`, and `AssembleContext` are
    imperative session methods, not SQL queries, so they live as typed gRPC RPCs
    alongside SessionService / EmbeddingService / InferenceService / EvalService
    rather than on the Flight SQL surface (which carries query/result only, per
    ADR-01 §3.2). They are substrate primitives — materialising a k-NN graph,
    propagating features over a declared graph, or pooling a retrieval into a
    fixed-width context vector — and name no tenant-domain concept.

    Each verb delegates 1:1 to the engine session; the service reimplements no
    retrieval, graph, or aggregation logic — it is purely a wire adapter over the
    in-process engine. The two graph-build verbs transport only a result-table
    name (the compute stays server-side, so the materialised table is
    byte-identical to one built in-process); `AssembleContext` carries its pooled
    vector inline as IEEE-754 `float` (bit-exact for the engine's `Vec<f32>`).

    Tenant scope is read from the request's `SessionTenant` extension, set by the
    shared TenantInterceptor from the `jammi-session-id` header — the same
    mechanism every other gRPC service and Flight SQL already use.
    """

    def BuildNeighborGraph(self, request, context):
        """Materialise the k-nearest-neighbour graph of a source's embedding table and
        return the new edge table. Peer of the engine's `build_neighbor_graph`; the
        client reads the table via `sql(...)`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropagateEmbeddings(self, request, context):
        """Propagate an embedding table's features over a declared graph (the
        decoupled-GNN forward pass) into a new, searchable embedding table. Peer of
        the engine's `propagate_embeddings`; the client reads the table via
        `sql(...)`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssembleContext(self, request, context):
        """Assemble and encode a target's context set: retrieve `k` nearest neighbours
        (or a declared-edge walk / their union), pair them with `value_columns`, and
        pool the neighbour vectors permutation-invariantly into one fixed-width
        context vector. Peer of the engine's `assemble_context`; returns the pooled
        vector and the carried metadata inline (no durable handle).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsofJoin(self, request, context):
        """Assemble a point-in-time-correct table: for each row of `spine`, attach the
        `facts` row valid as-of the spine row's temporal key, within each equality
        group. Peer of the engine's `asof_join`; the compute stays server-side and
        the client reads the materialised table via `sql(...)`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recompute(self, request, context):
        """Re-invoke a result table's recorded producer over the inputs' current state
        (the action half of incremental recompute). Peer of the engine's
        `recompute`: it reads the named table's recorded producing descriptor,
        replays the producing verb, and — under `cascade = DOWNSTREAM` — sweeps every
        transitive dependent once in topological order. The compute stays
        server-side; the report names the recomputed tables (read via `sql(...)`)
        and the transitive downstream-stale set.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuildNeighborGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildNeighborGraph,
                    request_deserializer=jammi_dot_v1_dot_pipeline__pb2.BuildNeighborGraphRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_embedding__pb2.ResultTable.SerializeToString,
            ),
            'PropagateEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.PropagateEmbeddings,
                    request_deserializer=jammi_dot_v1_dot_pipeline__pb2.PropagateEmbeddingsRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_embedding__pb2.ResultTable.SerializeToString,
            ),
            'AssembleContext': grpc.unary_unary_rpc_method_handler(
                    servicer.AssembleContext,
                    request_deserializer=jammi_dot_v1_dot_pipeline__pb2.AssembleContextRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_pipeline__pb2.AssembleContextResponse.SerializeToString,
            ),
            'AsofJoin': grpc.unary_unary_rpc_method_handler(
                    servicer.AsofJoin,
                    request_deserializer=jammi_dot_v1_dot_pipeline__pb2.AsofJoinRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_embedding__pb2.ResultTable.SerializeToString,
            ),
            'Recompute': grpc.unary_unary_rpc_method_handler(
                    servicer.Recompute,
                    request_deserializer=jammi_dot_v1_dot_pipeline__pb2.RecomputeRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_pipeline__pb2.RecomputeReport.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jammi.v1.pipeline.PipelineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jammi.v1.pipeline.PipelineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PipelineService(object):
    """PipelineService — the wire surface for the engine's compute-to-data engine-
    state verbs that build durable graph/embedding artifacts or assemble a
    target's conditioning context.

    `BuildNeighborGraph`, `PropagateEmbeddings`, and `AssembleContext` are
    imperative session methods, not SQL queries, so they live as typed gRPC RPCs
    alongside SessionService / EmbeddingService / InferenceService / EvalService
    rather than on the Flight SQL surface (which carries query/result only, per
    ADR-01 §3.2). They are substrate primitives — materialising a k-NN graph,
    propagating features over a declared graph, or pooling a retrieval into a
    fixed-width context vector — and name no tenant-domain concept.

    Each verb delegates 1:1 to the engine session; the service reimplements no
    retrieval, graph, or aggregation logic — it is purely a wire adapter over the
    in-process engine. The two graph-build verbs transport only a result-table
    name (the compute stays server-side, so the materialised table is
    byte-identical to one built in-process); `AssembleContext` carries its pooled
    vector inline as IEEE-754 `float` (bit-exact for the engine's `Vec<f32>`).

    Tenant scope is read from the request's `SessionTenant` extension, set by the
    shared TenantInterceptor from the `jammi-session-id` header — the same
    mechanism every other gRPC service and Flight SQL already use.
    """

    @staticmethod
    def BuildNeighborGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.pipeline.PipelineService/BuildNeighborGraph',
            jammi_dot_v1_dot_pipeline__pb2.BuildNeighborGraphRequest.SerializeToString,
            jammi_dot_v1_dot_embedding__pb2.ResultTable.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PropagateEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.pipeline.PipelineService/PropagateEmbeddings',
            jammi_dot_v1_dot_pipeline__pb2.PropagateEmbeddingsRequest.SerializeToString,
            jammi_dot_v1_dot_embedding__pb2.ResultTable.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssembleContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.pipeline.PipelineService/AssembleContext',
            jammi_dot_v1_dot_pipeline__pb2.AssembleContextRequest.SerializeToString,
            jammi_dot_v1_dot_pipeline__pb2.AssembleContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsofJoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.pipeline.PipelineService/AsofJoin',
            jammi_dot_v1_dot_pipeline__pb2.AsofJoinRequest.SerializeToString,
            jammi_dot_v1_dot_embedding__pb2.ResultTable.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recompute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.pipeline.PipelineService/Recompute',
            jammi_dot_v1_dot_pipeline__pb2.RecomputeRequest.SerializeToString,
            jammi_dot_v1_dot_pipeline__pb2.RecomputeReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
