# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jammi/v1/trigger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jammi/v1/trigger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16jammi/v1/trigger.proto\x12\x10jammi.v1.trigger\x1a\x1fgoogle/protobuf/timestamp.proto\"\x19\n\tTopicName\x12\x0c\n\x04name\x18\x01 \x01(\t\"J\n\nArrowBatch\x12\x13\n\x0b\x64\x61ta_header\x18\x01 \x01(\x0c\x12\x11\n\tdata_body\x18\x02 \x01(\x0c\x12\x14\n\x0c\x61pp_metadata\x18\x03 \x01(\x0c\"|\n\x0ePublishRequest\x12*\n\x05topic\x18\x01 \x01(\x0b\x32\x1b.jammi.v1.trigger.TopicName\x12+\n\x05\x62\x61tch\x18\x02 \x01(\x0b\x32\x1c.jammi.v1.trigger.ArrowBatch\x12\x11\n\ttenant_id\x18\x03 \x01(\t\"S\n\x0fPublishResponse\x12\x0e\n\x06offset\x18\x01 \x01(\x04\x12\x30\n\x0c\x63ommitted_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xa3\x01\n\x10SubscribeRequest\x12*\n\x05topic\x18\x01 \x01(\x0b\x32\x1b.jammi.v1.trigger.TopicName\x12\x11\n\tpredicate\x18\x02 \x01(\t\x12\x18\n\x0b\x66rom_offset\x18\x03 \x01(\x04H\x00\x88\x01\x01\x12\x11\n\ttenant_id\x18\x04 \x01(\t\x12\x13\n\x0breplay_only\x18\x05 \x01(\x08\x42\x0e\n\x0c_from_offset\"\x7f\n\x0fSubscribedBatch\x12\x0e\n\x06offset\x18\x01 \x01(\x04\x12/\n\x0bproduced_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x05\x62\x61tch\x18\x03 \x01(\x0b\x32\x1c.jammi.v1.trigger.ArrowBatch2\xb6\x01\n\x0eTriggerService\x12N\n\x07Publish\x12 .jammi.v1.trigger.PublishRequest\x1a!.jammi.v1.trigger.PublishResponse\x12T\n\tSubscribe\x12\".jammi.v1.trigger.SubscribeRequest\x1a!.jammi.v1.trigger.SubscribedBatch0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jammi.v1.trigger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOPICNAME']._serialized_start=77
  _globals['_TOPICNAME']._serialized_end=102
  _globals['_ARROWBATCH']._serialized_start=104
  _globals['_ARROWBATCH']._serialized_end=178
  _globals['_PUBLISHREQUEST']._serialized_start=180
  _globals['_PUBLISHREQUEST']._serialized_end=304
  _globals['_PUBLISHRESPONSE']._serialized_start=306
  _globals['_PUBLISHRESPONSE']._serialized_end=389
  _globals['_SUBSCRIBEREQUEST']._serialized_start=392
  _globals['_SUBSCRIBEREQUEST']._serialized_end=555
  _globals['_SUBSCRIBEDBATCH']._serialized_start=557
  _globals['_SUBSCRIBEDBATCH']._serialized_end=684
  _globals['_TRIGGERSERVICE']._serialized_start=687
  _globals['_TRIGGERSERVICE']._serialized_end=869
# @@protoc_insertion_point(module_scope)
