# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import trigger_pb2 as jammi_dot_v1_dot_trigger__pb2
GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jammi/v1/trigger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TriggerServiceStub:
    """TriggerService — primitive pub/sub over Arrow record batches.

    Verb vocabulary is closed: RegisterTopic, DropTopic, Publish, Subscribe,
    ListTopics. No domain-shaped verbs (no Discover, no Ingest*, no Run*). See
    ADR-01 §3.4.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTopic = channel.unary_unary(
                '/jammi.v1.trigger.TriggerService/RegisterTopic',
                request_serializer=jammi_dot_v1_dot_trigger__pb2.RegisterTopicRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_trigger__pb2.RegisterTopicResponse.FromString,
                _registered_method=True)
        self.DropTopic = channel.unary_unary(
                '/jammi.v1.trigger.TriggerService/DropTopic',
                request_serializer=jammi_dot_v1_dot_trigger__pb2.DropTopicRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/jammi.v1.trigger.TriggerService/Publish',
                request_serializer=jammi_dot_v1_dot_trigger__pb2.PublishRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_trigger__pb2.PublishResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/jammi.v1.trigger.TriggerService/Subscribe',
                request_serializer=jammi_dot_v1_dot_trigger__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_trigger__pb2.SubscribedBatch.FromString,
                _registered_method=True)
        self.ListTopics = channel.unary_unary(
                '/jammi.v1.trigger.TriggerService/ListTopics',
                request_serializer=jammi_dot_v1_dot_trigger__pb2.ListTopicsRequest.SerializeToString,
                response_deserializer=jammi_dot_v1_dot_trigger__pb2.ListTopicsResponse.FromString,
                _registered_method=True)


class TriggerServiceServicer:
    """TriggerService — primitive pub/sub over Arrow record batches.

    Verb vocabulary is closed: RegisterTopic, DropTopic, Publish, Subscribe,
    ListTopics. No domain-shaped verbs (no Discover, no Ingest*, no Run*). See
    ADR-01 §3.4.
    """

    def RegisterTopic(self, request, context):
        """Register a topic (provisions its backing table) for the trigger stream.
        Peer of the abstraction's `register_topic`. The schema is the contract
        every published batch must satisfy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropTopic(self, request, context):
        """Drop a topic and its backing table. Peer of the abstraction's
        `drop_topic`. `if_exists` makes a missing topic a no-op rather than a
        NotFound error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """Publish a single batch to a topic. Unary RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe to a topic with an optional SQL predicate filter applied
        server-side. Server-streaming RPC; the stream stays open until the
        client cancels or the deadline expires.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTopics(self, request, context):
        """List topics registered in the catalog. Pagination follows AIP-132.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TriggerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTopic': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTopic,
                    request_deserializer=jammi_dot_v1_dot_trigger__pb2.RegisterTopicRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_trigger__pb2.RegisterTopicResponse.SerializeToString,
            ),
            'DropTopic': grpc.unary_unary_rpc_method_handler(
                    servicer.DropTopic,
                    request_deserializer=jammi_dot_v1_dot_trigger__pb2.DropTopicRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=jammi_dot_v1_dot_trigger__pb2.PublishRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_trigger__pb2.PublishResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=jammi_dot_v1_dot_trigger__pb2.SubscribeRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_trigger__pb2.SubscribedBatch.SerializeToString,
            ),
            'ListTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTopics,
                    request_deserializer=jammi_dot_v1_dot_trigger__pb2.ListTopicsRequest.FromString,
                    response_serializer=jammi_dot_v1_dot_trigger__pb2.ListTopicsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jammi.v1.trigger.TriggerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jammi.v1.trigger.TriggerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TriggerService:
    """TriggerService — primitive pub/sub over Arrow record batches.

    Verb vocabulary is closed: RegisterTopic, DropTopic, Publish, Subscribe,
    ListTopics. No domain-shaped verbs (no Discover, no Ingest*, no Run*). See
    ADR-01 §3.4.
    """

    @staticmethod
    def RegisterTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.trigger.TriggerService/RegisterTopic',
            jammi_dot_v1_dot_trigger__pb2.RegisterTopicRequest.SerializeToString,
            jammi_dot_v1_dot_trigger__pb2.RegisterTopicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.trigger.TriggerService/DropTopic',
            jammi_dot_v1_dot_trigger__pb2.DropTopicRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.trigger.TriggerService/Publish',
            jammi_dot_v1_dot_trigger__pb2.PublishRequest.SerializeToString,
            jammi_dot_v1_dot_trigger__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jammi.v1.trigger.TriggerService/Subscribe',
            jammi_dot_v1_dot_trigger__pb2.SubscribeRequest.SerializeToString,
            jammi_dot_v1_dot_trigger__pb2.SubscribedBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jammi.v1.trigger.TriggerService/ListTopics',
            jammi_dot_v1_dot_trigger__pb2.ListTopicsRequest.SerializeToString,
            jammi_dot_v1_dot_trigger__pb2.ListTopicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
